window.BackupManager=(()=>{
  const LISTS=['clientes','produtos','vendas','pagamentos','movimentacoes','movimentacoesEstoque','cobrancas','campanhas','progressosCampanha','recompensas'];
  const FINANCIAL=new Set(['vendas','pagamentos','movimentacoes','movimentacoesEstoque','recompensas']);
  const norm=value=>String(value??'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' '),digits=value=>String(value??'').replace(/\D/g,'');
  const stable=value=>{if(Array.isArray(value))return`[${value.map(stable).join(',')}]`;if(value&&typeof value==='object')return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${stable(value[key])}`).join(',')}}`;return JSON.stringify(value)};
  const hash=value=>{let h=2166136261;for(const char of String(value)){h^=char.charCodeAt(0);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  const deterministicId=(type,record,businessId)=>{let signature;if(type==='clientes')signature=`${digits(record.telefone)||norm(record.nome)}|${norm(record.nome)}`;else if(type==='produtos')signature=norm(record.codigo)||`${norm(record.nome)}|${norm(record.categoria)}`;else if(type==='vendas')signature=`${record.data||record.createdAt}|${record.clienteId||norm(record.clienteNome)}|${Number(record.valorFinal??record.valorTotal??0)}|${stable((record.itens||[]).map(item=>[item.produtoId||norm(item.nome),Number(item.quantidade||0),Number(item.precoFinalUnitario??item.precoUnitario??0)]))}`;else if(type==='pagamentos')signature=`${record.clienteId}|${record.data||record.createdAt}|${Number(record.valor||0)}|${norm(record.forma||record.observacao)}`;else signature=stable(record);return`${type.slice(0,3)}_${hash(`${businessId}|${type}|${signature}`)}`};
  const naturalKey=(type,record)=>type==='clientes'?(digits(record.telefone)?`tel:${digits(record.telefone)}`:`nome:${norm(record.nome)}`):type==='produtos'?(norm(record.codigo)?`cod:${norm(record.codigo)}`:`nome:${norm(record.nome)}|${norm(record.categoria)}`):'';
  const mergeRecord=(base,next)=>{const merged={...base};for(const[key,value]of Object.entries(next))if(value!==undefined&&value!==null&&value!=='')merged[key]=value;return merged};
  function normalizeList(type,list,businessId,report){const byId=new Map(),byOperation=new Map(),byNatural=new Map();for(const source of Array.isArray(list)?list:[]){if(!source||typeof source!=='object'){report.invalid++;continue}const record=structuredClone(source),hadId=Boolean(record.id);record.id=String(record.id||deterministicId(type,record,businessId));if(!hadId)record.__legacyGeneratedId=true;if(FINANCIAL.has(type))record.operationId=String(record.operationId||record.sourceOperationId||deterministicId(`${type}_op`,record,businessId));const operationKey=FINANCIAL.has(type)&&record.operationId?record.operationId:'',natural=!hadId?naturalKey(type,record):'',existingId=operationKey?byOperation.get(operationKey):natural?byNatural.get(natural):null;if(existingId||byId.has(record.id)){const target=existingId||record.id;byId.set(target,mergeRecord(byId.get(target)||{},{...record,id:target}));report.duplicates++;continue}byId.set(record.id,record);if(operationKey)byOperation.set(operationKey,record.id);if(natural)byNatural.set(natural,record.id)}return[...byId.values()]}
  function normalizeBackup(raw,currentBusinessId){if(!raw||typeof raw!=='object')throw Error('O arquivo não contém um backup válido.');const declared=String(raw.businessId||raw.backupInfo?.businessId||'').trim();if(declared&&declared!==currentBusinessId)throw Error('Este backup pertence a outro negócio.');const businessId=declared||currentBusinessId,report={duplicates:0,invalid:0},data={versao:Number(raw.versao||raw.schemaVersion||5),config:structuredClone(raw.config||{})};for(const type of LISTS)data[type]=normalizeList(type,raw[type],businessId,report);const backupId=String(raw.backupId||raw.backupInfo?.backupId||`legacy_${hash(stable(data))}`),exportedAt=raw.exportedAt||raw.backupInfo?.exportadoEm||raw.backupInfo?.exportedAt||null;return{backupId,businessId,exportedAt,schemaVersion:Number(raw.schemaVersion||raw.versao||5),data,report,source:raw}}
  const cleanRecord=item=>{const clean=structuredClone(item);delete clean.__legacyGeneratedId;return clean};
  const mergeList=(current,incoming,type)=>{const byId=new Map((current||[]).map(item=>[String(item.id),structuredClone(item)])),opToId=new Map(),naturalToId=new Map();for(const item of byId.values()){if(FINANCIAL.has(type)&&item.operationId)opToId.set(String(item.operationId),String(item.id));const natural=naturalKey(type,item);if(natural)naturalToId.set(natural,String(item.id))}let added=0,updated=0;for(const raw of incoming||[]){const item=cleanRecord(raw),naturalMatch=raw.__legacyGeneratedId&&naturalKey(type,raw)?naturalToId.get(naturalKey(type,raw)):null,id=item.operationId&&opToId.get(String(item.operationId))||naturalMatch||String(item.id);if(byId.has(id)){byId.set(id,mergeRecord(byId.get(id),{...item,id}));updated++}else{byId.set(id,{...item,id});added++}if(item.operationId)opToId.set(String(item.operationId),id);const natural=naturalKey(type,item);if(natural)naturalToId.set(natural,id)}return{items:[...byId.values()],added,updated}};
  function cleanPreparedData(prepared){const data=structuredClone(prepared.data);for(const type of LISTS)data[type]=(data[type]||[]).map(cleanRecord);return data}
  function mergeData(current,prepared,mode='merge'){if(mode==='replace')return{data:cleanPreparedData(prepared),added:LISTS.reduce((sum,key)=>sum+prepared.data[key].length,0),updated:0};const result=structuredClone(current),summary={added:0,updated:0};for(const type of LISTS){const merged=mergeList(result[type],prepared.data[type],type);result[type]=merged.items;summary.added+=merged.added;summary.updated+=merged.updated}result.config={...(result.config||{}),...(prepared.data.config||{})};return{data:result,...summary}}
  const counts=data=>({clientes:(data.clientes||[]).length,produtos:(data.produtos||[]).length,vendas:(data.vendas||[]).length,pagamentos:(data.pagamentos||[]).length,ajustes:(data.movimentacoes||[]).filter(item=>item.tipo==='ajuste_saldo').length,movimentosEstoque:(data.movimentacoesEstoque||[]).length,campanhas:(data.campanhas||[]).length,progressosCampanha:(data.progressosCampanha||[]).length,recompensas:(data.recompensas||[]).length,cobrancas:(data.cobrancas||[]).length});
  const totals=data=>({fiado:(data.clientes||[]).reduce((sum,item)=>sum+Math.abs(Math.min(0,Number(item.saldo||0))),0),estoque:(data.produtos||[]).reduce((sum,item)=>sum+Number(item.estoqueAtual||0),0),vendido:(data.vendas||[]).reduce((sum,item)=>sum+Number(item.valorFinal??item.valorTotal??0),0)});
  function preview(prepared,current){const merged=mergeData(current,prepared,'merge'),summary=counts(prepared.data);return{...summary,...prepared.report,validos:Object.values(summary).reduce((sum,value)=>sum+value,0),mesclados:prepared.report.duplicates,novos:merged.added,atualizados:merged.updated,totals:totals(prepared.data)}}
  function duplicateGroups(data){const groups=[];for(const type of ['clientes','produtos']){const seen=new Map();for(const item of data[type]||[]){const natural=naturalKey(type,item);if(!natural)continue;const key=`${type}:${natural}`;if(seen.has(key))groups.push({type,reason:'cadastro semelhante',ids:[seen.get(key),item.id]});else seen.set(key,item.id)}}for(const type of FINANCIAL){const ids=new Set(),operations=new Map(),signatures=new Map();for(const item of data[type]||[]){if(ids.has(item.id))groups.push({type,reason:'ID repetido',ids:[item.id]});ids.add(item.id);if(item.operationId&&operations.has(item.operationId))groups.push({type,reason:'operationId repetido',ids:[operations.get(item.operationId),item.id]});else if(item.operationId)operations.set(item.operationId,item.id);if(['vendas','pagamentos'].includes(type)){const signature=type==='vendas'?`${item.data||item.createdAt}|${item.clienteId||''}|${Number(item.valorFinal??item.valorTotal??0)}|${stable(item.itens||[])}`:`${item.data||item.createdAt}|${item.clienteId||''}|${Number(item.valor||0)}|${norm(item.forma||item.observacao)}`;if(signatures.has(signature)&&signatures.get(signature)!==item.id)groups.push({type,reason:'lançamento idêntico suspeito',ids:[signatures.get(signature),item.id]});else signatures.set(signature,item.id)}}}return groups}
  return{LISTS,FINANCIAL,normalizeBackup,deduplicateBackupData:normalizeBackup,mergeData,preview,counts,totals,findDuplicates:duplicateGroups,deterministicId};
})();
