(function(){
  'use strict';
  const TYPES={buy_get:{label:'Compre X e ganhe Y',icon:'shopping-cart'},points:{label:'Acúmulo de pontos',icon:'award'},quantity_discount:{label:'Desconto por quantidade',icon:'badge-percent'},nth_product:{label:'Produto X vezes',icon:'package-check'},combo:{label:'Combo promocional',icon:'shopping-basket'},custom:{label:'Campanha livre',icon:'megaphone'}};
  const now=()=>new Date().toISOString(),number=value=>Number(value||0),dateOnly=value=>value?String(value).slice(0,10):'';
  const status=campaign=>{if(campaign.status==='encerrada'||campaign.ativo===false)return'encerrada';const today=dateOnly(now()),start=dateOnly(campaign.startDate||campaign.dataInicio),end=dateOnly(campaign.endDate||campaign.dataFim);if(start&&start>today)return'agendada';if(end&&end<today)return'encerrada';if(campaign.status==='pausada')return'pausada';return'ativa'};
  const normalize=raw=>{const created=raw.createdAt||raw.criadoEm||now(),type=TYPES[raw.type]?raw.type:TYPES[raw.tipo]?raw.tipo:'custom',rules=raw.rules&&typeof raw.rules==='object'?raw.rules:{};return{...raw,id:raw.id||Utils.uuid(),operationId:raw.operationId||raw.id||Utils.uuid(),name:raw.name||raw.nome||'Campanha sem nome',nome:raw.name||raw.nome||'Campanha sem nome',description:raw.description||raw.descricao||'',descricao:raw.description||raw.descricao||'',type,tipo:type,status:raw.status||'ativa',active:raw.active??raw.ativo??true,ativo:raw.active??raw.ativo??true,published:raw.published??raw.publica??true,publica:raw.published??raw.publica??true,startDate:raw.startDate||raw.dataInicio||dateOnly(now()),dataInicio:raw.startDate||raw.dataInicio||dateOnly(now()),endDate:raw.endDate||raw.dataFim||'',dataFim:raw.endDate||raw.dataFim||'',imageUrl:raw.imageUrl||raw.imagem||null,imageIcon:raw.imageIcon||TYPES[type].icon,productIds:Array.isArray(raw.productIds)?raw.productIds:raw.produtoId?[raw.produtoId]:[],rewardProductId:raw.rewardProductId||raw.produtoPremioId||raw.produtoId||'',categoryIds:Array.isArray(raw.categoryIds)?raw.categoryIds:[],rules:{requiredQuantity:number(rules.requiredQuantity??raw.quantidadeNecessaria??5),rewardQuantity:number(rules.rewardQuantity??raw.quantidadePremio??1),pointsPerReal:number(rules.pointsPerReal??raw.pontosPorReal??1),rewardPoints:number(rules.rewardPoints??raw.pontos??100),discountPercent:number(rules.discountPercent??raw.descontoPercentual??10),requiredPurchases:number(rules.requiredPurchases??raw.quantidadeNecessaria??5),comboProductIds:Array.isArray(rules.comboProductIds)?rules.comboProductIds:[],comboPrice:number(rules.comboPrice??raw.precoCombo),customRule:rules.customRule||raw.regraLivre||''},audience:{type:raw.audience?.type||raw.participantesTipo||'all',clientIds:Array.isArray(raw.audience?.clientIds)?raw.audience.clientIds:[],groupIds:Array.isArray(raw.audience?.groupIds)?raw.audience.groupIds:[],tags:Array.isArray(raw.audience?.tags)?raw.audience.tags:[]},schedule:{recurring:Boolean(raw.schedule?.recurring),frequency:raw.schedule?.frequency||null,birthday:Boolean(raw.schedule?.birthday)},participantsCount:number(raw.participantsCount??raw.participantes),redemptionsCount:number(raw.redemptionsCount??raw.quantidadeResgates),distributedProducts:number(raw.distributedProducts),createdBy:raw.createdBy||raw.criador||window.FirebaseSession?.user?.uid||'local',createdAt:created,criadoEm:created,updatedAt:raw.updatedAt||raw.atualizadoEm||created,atualizadoEm:raw.updatedAt||raw.atualizadoEm||created}}
  const all=()=>DB.carregar().campanhas.map(normalize),get=id=>all().find(item=>item.id===id),active=()=>all().filter(c=>status(c)==='ativa');
  function eligible(campaign,client){if(!client||client.ativo===false)return false;const audience=campaign.audience||{};if(audience.type==='clients')return audience.clientIds.includes(client.id);if(audience.type==='vip')return Boolean(client.vip||client.etiquetas?.includes?.('vip')||number(client.totalComprado)>=500);return true}
  function save(data){let saved;DB.alterar(db=>{const campaign=normalize(data),index=db.campanhas.findIndex(item=>item.id===campaign.id),old=index>=0?normalize(db.campanhas[index]):null,time=now();saved={...old,...campaign,id:campaign.id||Utils.uuid(),operationId:campaign.operationId||old?.operationId||Utils.uuid(),createdAt:old?.createdAt||time,criadoEm:old?.createdAt||time,updatedAt:time,atualizadoEm:time};saved.status=status(saved);saved.active=saved.ativo=saved.status!=='encerrada';if(index>=0)db.campanhas[index]=saved;else db.campanhas.push(saved)});return saved}
  const setStatus=(id,value)=>save({...get(id),status:value,active:value!=='encerrada',ativo:value!=='encerrada'});
  const duplicate=id=>{const source=get(id);return save({...source,id:Utils.uuid(),operationId:Utils.uuid(),name:`${source.name} (cópia)`,nome:`${source.name} (cópia)`,status:'agendada',startDate:dateOnly(now()),endDate:'',participantsCount:0,redemptionsCount:0,createdAt:now()})};
  const remove=id=>DB.alterar(db=>{db.campanhas=db.campanhas.filter(item=>item.id!==id);db.progressosCampanha=db.progressosCampanha.filter(item=>item.campaignId!==id&&item.campanhaId!==id)});
  const progressId=(campaignId,clientId)=>`${clientId}__${campaignId}`;
  function compatibleQuantity(campaign,sale){const ids=new Set(campaign.productIds||[]);return(sale.itens||[]).filter(item=>!ids.size||ids.has(item.produtoId)).reduce((sum,item)=>sum+number(item.quantidade),0)}
  function comboCompleted(campaign,sale){const ids=campaign.rules?.comboProductIds||[];return ids.length&&ids.every(id=>(sale.itens||[]).some(item=>item.produtoId===id&&number(item.quantidade)>0))?1:0}
  function applyBenefits(items,clientId,options={}){const result=(items||[]).map(item=>({...item,campaignDiscounts:[...(item.campaignDiscounts||[])]}));if(options.manualAdjustment)return result;const db=DB.carregar(),client=db.clientes.find(item=>item.id===clientId);for(const campaign of active()){if(clientId&&!eligible(campaign,client))continue;if(campaign.type==='quantity_discount'){const ids=new Set(campaign.productIds||[]),matched=result.filter(item=>!ids.size||ids.has(item.produtoId)),quantity=matched.reduce((sum,item)=>sum+number(item.quantidade),0);if(quantity<Math.max(1,number(campaign.rules.requiredQuantity)))continue;const factor=Math.max(0,1-number(campaign.rules.discountPercent)/100);for(const item of matched){const base=number(item.precoFinalUnitario??item.precoOriginal??item.precoUnitario);item.precoFinalUnitario=Number((base*factor).toFixed(4));item.campaignDiscounts.push({campaignId:campaign.id,type:'quantity_discount',percent:number(campaign.rules.discountPercent)})}}
      if(campaign.type==='combo'){const ids=campaign.rules.comboProductIds?.length?campaign.rules.comboProductIds:campaign.productIds||[],matched=result.filter(item=>ids.includes(item.produtoId));if(!ids.length||!ids.every(id=>matched.some(item=>item.produtoId===id))||number(campaign.rules.comboPrice)<=0)continue;const original=matched.reduce((sum,item)=>sum+number(item.quantidade)*number(item.precoFinalUnitario??item.precoOriginal??item.precoUnitario),0),factor=original?Math.min(1,number(campaign.rules.comboPrice)/original):1;for(const item of matched){const base=number(item.precoFinalUnitario??item.precoOriginal??item.precoUnitario);item.precoFinalUnitario=Number((base*factor).toFixed(4));item.campaignDiscounts.push({campaignId:campaign.id,type:'combo',comboPrice:number(campaign.rules.comboPrice)})}}}return result}
  function applySaleInDb(db,sale){if(!sale.clienteId)return[];const client=db.clientes.find(item=>item.id===sale.clienteId);if(!client)return[];const updates=[];for(const raw of db.campanhas||[]){const campaign=normalize(raw);if(status(campaign)!=='ativa'||!eligible(campaign,client))continue;const id=progressId(campaign.id,client.id),index=db.progressosCampanha.findIndex(item=>item.id===id||((item.campaignId||item.campanhaId)===campaign.id&&(item.clientId||item.clienteId)===client.id)),before=index>=0?structuredClone(db.progressosCampanha[index]):null,progress=before?{...before,id,operationId:id}:{id,operationId:id,campaignId:campaign.id,campanhaId:campaign.id,clientId:client.id,clienteId:client.id,clientName:client.nome,progress:0,progresso:0,points:0,pontos:0,availableRewards:0,recompensasDisponiveis:0,redeemedRewards:0,resgates:0,totalEarned:0,totalRedeemed:0,salesCount:0,processedSaleIds:[],createdAt:sale.data};if(progress.processedSaleIds?.includes(sale.id))continue;let increment=0,threshold=1,rewards=0;
      if(campaign.type==='buy_get'){increment=compatibleQuantity(campaign,sale);threshold=Math.max(1,number(campaign.rules.requiredQuantity));const total=number(progress.progress)+increment;rewards=Math.floor(total/threshold);progress.progress=progress.progresso=total%threshold}
      else if(campaign.type==='points'){increment=number(sale.valorFinal??sale.valorTotal)*Math.max(0,number(campaign.rules.pointsPerReal));progress.points=progress.pontos=number(progress.points)+increment;threshold=Math.max(1,number(campaign.rules.rewardPoints));rewards=Math.floor(progress.points/threshold)-Math.floor(number(before?.points)/threshold)}
      else if(campaign.type==='nth_product'){increment=compatibleQuantity(campaign,sale)>0?1:0;threshold=Math.max(1,number(campaign.rules.requiredPurchases));const total=number(progress.progress)+increment;rewards=Math.floor(total/threshold);progress.progress=progress.progresso=total%threshold}
      else if(campaign.type==='quantity_discount'){increment=compatibleQuantity(campaign,sale);threshold=Math.max(1,number(campaign.rules.requiredQuantity));if(increment>=threshold)rewards=1;progress.progress=progress.progresso=Math.min(threshold,number(progress.progress)+increment)}
      else if(campaign.type==='combo'){increment=comboCompleted(campaign,sale);threshold=1;rewards=increment;progress.progress=progress.progresso=number(progress.progress)+increment}
      else{increment=1;progress.progress=progress.progresso=number(progress.progress)+1}
      if(increment<=0)continue;progress.availableRewards=progress.recompensasDisponiveis=number(progress.availableRewards)+Math.max(0,rewards);progress.currentProgress=number(progress.progress);progress.target=threshold;progress.rewardsAvailable=number(progress.availableRewards);progress.totalEarned=number(progress.totalEarned)+Math.max(0,rewards);progress.totalRedeemed=number(progress.redeemedRewards??progress.resgates);progress.salesCount=number(progress.salesCount)+1;progress.processedSaleIds=[...(progress.processedSaleIds||[]),sale.id].slice(-100);progress.lastSaleId=sale.id;progress.lastQualifiedSaleId=sale.id;progress.lastSaleAt=sale.data;progress.updatedAt=sale.data;progress.threshold=threshold;progress.type=campaign.type;progress.status=progress.availableRewards>0?'available':'active';if(index>=0)db.progressosCampanha[index]=progress;else db.progressosCampanha.push(progress);updates.push({progressId:id,campaignId:campaign.id,before,after:structuredClone(progress)});raw.participantsCount=(db.progressosCampanha||[]).filter(item=>(item.campaignId||item.campanhaId)===campaign.id).length;raw.participantes=raw.participantsCount;raw.updatedAt=sale.data}
    return updates}
  function revertSaleInDb(db,sale){for(const update of sale.campaignUpdates||[]){const index=db.progressosCampanha.findIndex(item=>item.id===update.progressId);if(update.before){if(index>=0)db.progressosCampanha[index]=update.before;else db.progressosCampanha.push(update.before)}else if(index>=0)db.progressosCampanha.splice(index,1)}}
  function redeem(campaignId,clientId,note=''){let reward;DB.alterar(db=>{const campaign=db.campanhas.find(item=>item.id===campaignId),progress=db.progressosCampanha.find(item=>(item.campaignId||item.campanhaId)===campaignId&&(item.clientId||item.clienteId)===clientId);if(!campaign||!progress)throw Error('Progresso não encontrado');if(number(progress.availableRewards??progress.recompensasDisponiveis)<1)throw Error('Este cliente ainda não possui prêmio disponível');const time=now(),id=Utils.uuid();progress.availableRewards=progress.recompensasDisponiveis=number(progress.availableRewards??progress.recompensasDisponiveis)-1;progress.rewardsAvailable=number(progress.availableRewards);progress.redeemedRewards=progress.resgates=number(progress.redeemedRewards??progress.resgates)+1;progress.totalRedeemed=number(progress.redeemedRewards);progress.status=progress.availableRewards>0?'available':'active';progress.updatedAt=time;campaign.redemptionsCount=campaign.quantidadeResgates=number(campaign.redemptionsCount??campaign.quantidadeResgates)+1;campaign.distributedProducts=number(campaign.distributedProducts)+Math.max(1,number(normalize(campaign).rules.rewardQuantity));campaign.updatedAt=time;reward={id,operationId:id,campaignId,campanhaId:campaignId,clientId,clienteId:clientId,type:'campaign_redemption',tipo:'resgate_campanha',quantity:Math.max(1,number(normalize(campaign).rules.rewardQuantity)),status:'redeemed',note,createdAt:time,data:time};db.recompensas.push(reward)});return reward}
  function approveRequest(requestId){const request=DB.carregar().recompensas.find(item=>item.id===requestId&&item.tipo==='solicitacao_resgate');if(!request)throw Error('Solicitação não encontrada');if(request.status!=='solicitado')throw Error('Esta solicitação já foi processada');const client=DB.carregar().clientes.find(item=>item.id===(request.clientId||request.clienteId)||item.portalRefToken===request.clientRefToken);if(!client)throw Error('Cliente da solicitação não encontrado');const reward=redeem(request.campaignId||request.campanhaId,client.id,'Resgate solicitado pelo Portal do Cliente');DB.alterar(db=>{const current=db.recompensas.find(item=>item.id===requestId);current.clientId=current.clienteId=client.id;current.status='resgatado';current.rewardId=reward.id;current.updatedAt=now()});dispatchEvent(new CustomEvent('catalog-redemption-status-request',{detail:{requestId,status:'resgatado',rewardId:reward.id,visitId:request.visitId}}));return reward}
  function metrics(){const db=DB.carregar(),campaigns=all(),progress=db.progressosCampanha||[],rewards=(db.recompensas||[]).filter(item=>item.type==='campaign_redemption'||item.tipo==='resgate_campanha'),participants=new Set(progress.map(item=>item.clientId||item.clienteId).filter(Boolean));return{active:campaigns.filter(item=>status(item)==='ativa').length,participants:participants.size,redemptions:rewards.length,distributed:rewards.reduce((sum,item)=>sum+number(item.quantity||1),0),conversion:progress.length?rewards.length/progress.length*100:0}}
  const progressFor=(campaignId,clientId)=>DB.carregar().progressosCampanha.find(item=>(item.campaignId||item.campanhaId)===campaignId&&(item.clientId||item.clienteId)===clientId)||null;
  window.Campanhas={TYPES,normalize,status,listar:all,obter:get,ativas:active,salvar:save,alterarStatus:setStatus,duplicar:duplicate,excluir:remove,elegivel:eligible,aplicarBeneficios:applyBenefits,aplicarVendaNoBanco:applySaleInDb,reverterVendaNoBanco:revertSaleInDb,resgatar:redeem,aprovarSolicitacao:approveRequest,metricas:metrics,progresso:progressFor};
})();
