import {db} from './firebase/firebase-config.js';
import {doc,getDoc,onSnapshot,serverTimestamp,setDoc,updateDoc} from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import {formatBrazilianPhone,isValidBrazilianPhone,maskPhone,normalizeBrazilianPhone,phoneIndexId,randomToken,sessionDocumentId,sessionStorageKey,trackPortalEvent} from './catalog-portal.js';

const root=document.querySelector('#catalog-app'),params=new URLSearchParams(location.search),queryToken=params.get('v'),legacyPathMatch=location.pathname.match(/\/catalogo\/([^/?#]+)/),legacyPathToken=legacyPathMatch?legacyPathMatch[1]:'',visitToken=queryToken||legacyPathToken||'',money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char])),uuid=()=>crypto.randomUUID();
const cartKey=`adiFesta:catalogCart:${visitToken}`,legacyCartKey=`adiCatalogCart:${visitToken}`,ordersKey=`adiCatalogOrders:${visitToken}`;
let catalog=null,view='catalog',category='Todos',query='',cart=read(cartKey,read(legacyCartKey,{})),orders=read(ordersKey,[]),identity=read(`adiFesta:portalIdentity:${visitToken}`,{}),portalSession=null,portalProfile=null,unsub=[],toastTimer=null,pendingOrderForm=null,submittingOrder=false,pendingOrderAttempt=null;

function read(key,fallback){try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}}
function save(){localStorage.setItem(cartKey,JSON.stringify(cart));localStorage.removeItem(legacyCartKey);localStorage.setItem(ordersKey,JSON.stringify(orders));localStorage.setItem(`adiFesta:portalIdentity:${visitToken}`,JSON.stringify(identity))}
const validVisitToken=value=>typeof value==='string'&&/^[A-Za-z0-9_-]{20,128}$/.test(value);
const publicCatalogError=(code,message)=>Object.assign(new Error(message||code),{code});
function normalizedCatalogErrorCode(error){const code=String(error?.code||'').replace('firestore/','');if(code==='permission-denied')return'permission-denied';if(code==='not-found')return'not-found';if(code==='inactive')return'inactive';if(['unavailable','network-request-failed','deadline-exceeded','failed-precondition'].includes(code)||!navigator.onLine)return'network';return'network'}
function catalogErrorMessage(code){return{'permission-denied':'Sem permissão para acessar o catálogo','not-found':'Catálogo não encontrado',inactive:'Catálogo encerrado ou indisponível',network:'Não foi possível conectar ao servidor'}[code]||'Não foi possível conectar ao servidor'}
function showCatalogError(code,error){const message=catalogErrorMessage(code);console.error('[Public catalog load]',{code,message,firestoreCode:error?.code||null,documentPath:visitToken?`publicCatalogs/${visitToken}`:null,urlToken:queryToken,legacyPathToken:queryToken?null:legacyPathToken,tokenSource:queryToken?'query-v':legacyPathToken?'legacy-path':'missing',online:navigator.onLine});root.innerHTML=`<div class="catalog-loading catalog-load-error"><span class="catalog-logo">AF</span><h2>${esc(message)}</h2><p>${code==='permission-denied'?'O link existe, mas o acesso público não foi autorizado.':code==='not-found'?'Confira se o link recebido está completo.':code==='inactive'?'Peça ao vendedor um novo catálogo ativo.':'Verifique sua internet e tente novamente.'}</p><button type="button" class="secondary-button" onclick="location.reload()">Tentar novamente</button></div>`}
function validatePublicCatalog(snapshot){
  if(!snapshot.exists())throw publicCatalogError('not-found','Documento público não encontrado.');
  if(snapshot.id!==visitToken)throw publicCatalogError('not-found','O token não corresponde ao ID do documento.');
  const data=snapshot.data()||{};
  if(data.catalogToken&&data.catalogToken!==snapshot.id)throw publicCatalogError('not-found','O token publicado não corresponde ao ID do documento.');
  if(data.active!==true)throw publicCatalogError('inactive','Catálogo inativo.');
  if(!data.visitId||!data.businessId||!data.publicName||!Array.isArray(data.items))throw publicCatalogError('not-found','Documento público incompleto.');
  return{token:snapshot.id,...data};
}
async function loadPublicCatalog(){
  if(!queryToken&&legacyPathToken)console.warn('[Public catalog load]',{code:'legacy-path-token',message:'Link antigo detectado. Novos links usam catalogo.html?v={visitToken}.',visitToken});
  if(!validVisitToken(visitToken))throw publicCatalogError('not-found','Token ausente ou inválido.');
  const reference=doc(db,'publicCatalogs',visitToken);
  if(reference.id!==visitToken)throw publicCatalogError('not-found','O token não corresponde ao ID do documento.');
  console.info('[Public catalog load]',{code:'loading',documentPath:reference.path,documentId:reference.id,urlToken:visitToken,tokenMatchesDocumentId:reference.id===visitToken,authRequired:false,operation:'getDoc'});
  const snapshot=await getDoc(reference);
  const data=validatePublicCatalog(snapshot);
  console.info('[Public catalog load]',{code:'loaded',documentPath:reference.path,documentId:snapshot.id,urlToken:visitToken,tokenMatchesDocumentId:snapshot.id===visitToken,itemCount:data.items.length,active:data.active});
  return data;
}
function toast(text,undoId=null){const el=document.querySelector('#catalog-toast');clearTimeout(toastTimer);el.innerHTML=`<span>${esc(text)}</span>${undoId?'<button type="button" data-toast-undo>Desfazer</button>':''}`;if(undoId)el.querySelector('[data-toast-undo]').onclick=()=>{changeCart(undoId,-1,null,{silent:true});el.classList.remove('show')};el.classList.add('show');toastTimer=setTimeout(()=>el.classList.remove('show'),2600)}
const icon=name=>`<i data-lucide="${name}"></i>`,count=()=>Object.values(cart).reduce((sum,quantity)=>sum+Number(quantity||0),0),total=()=>catalog.items.reduce((sum,item)=>sum+Number(cart[item.id]||0)*Number(item.salePrice),0);
const tracksStock=item=>item.controlaEstoque!==false&&item.trackStock!==false&&item.semControleEstoque!==true;
const available=item=>tracksStock(item)?Math.max(0,Number(item.availableQuantity??item.currentStock??0)-Number(item.reservedStock??0)):Number.POSITIVE_INFINITY;
function receiving(){const statusOk=['recebendo','receiving_orders','recebendo_pedidos','recebendo pedidos'].includes(String(catalog.status||'').toLowerCase()),deadline=catalog.data&&catalog.horarioLimite?new Date(`${catalog.data}T${catalog.horarioLimite}:00`):null;return catalog.active!==false&&statusOk&&(!deadline||Number.isNaN(deadline.getTime())||Date.now()<=deadline.getTime())}
const campaignProgress=campaignId=>(portalProfile?.campaigns||[]).find(item=>item.campaignId===campaignId)||null;
const visibleCampaigns=()=>{const map=new Map((catalog.campaigns||[]).map(campaign=>[campaign.id,campaign]));for(const progress of portalProfile?.campaigns||[]){const id=progress.id||progress.campaignId;map.set(id,{...(map.get(id)||{}),...progress,id})}return[...map.values()]};
function campaignTarget(campaign,progress={}){progress=progress||{};if(progress.target)return Number(progress.target);if(campaign.tipo==='points')return Number(campaign.regras?.rewardPoints||100);if(campaign.tipo==='nth_product')return Number(campaign.regras?.requiredPurchases||5);return Number(campaign.regras?.requiredQuantity||5)}
function campaignCurrent(campaign,progress={}){progress=progress||{};return campaign.tipo==='points'?Number(progress.points||0):Number(progress.currentProgress||0)}
function relevantCampaigns(){return visibleCampaigns().map(campaign=>({campaign,progress:campaignProgress(campaign.id)})).sort((a,b)=>Number(b.progress?.rewardsAvailable||0)-Number(a.progress?.rewardsAvailable||0)||(campaignTarget(a.campaign,a.progress)-campaignCurrent(a.campaign,a.progress))-(campaignTarget(b.campaign,b.progress)-campaignCurrent(b.campaign,b.progress)))}
function bestBenefit(){return relevantCampaigns().find(item=>item.progress?.rewardsAvailable>0)||relevantCampaigns().filter(item=>item.progress).sort((a,b)=>(campaignTarget(a.campaign,a.progress)-campaignCurrent(a.campaign,a.progress))-(campaignTarget(b.campaign,b.progress)-campaignCurrent(b.campaign,b.progress)))[0]||null}
function header(title='Catálogo da visita'){const quantity=count(),badge=quantity>99?'99+':quantity;return `<header class="catalog-header">${view!=='catalog'?`<button type="button" class="back-button" data-view="catalog" aria-label="Voltar">${icon('chevron-left')}</button>`:`<span class="catalog-brand">${esc(catalog.publicName||'Adi Festa')}</span>`}<div class="catalog-title"><b>${esc(title)}</b><small>${esc(catalog.local)}</small></div><button type="button" class="cart-button" data-view="cart" aria-label="${quantity?`Abrir carrinho com ${quantity} itens`:'Carrinho vazio'}">${icon('shopping-cart')}<span class="cart-count">${badge}</span></button></header>`}
function nav(){return `<nav class="catalog-bottom" aria-label="Portal do cliente"><button data-view="catalog" class="${view==='catalog'?'active':''}">${icon('shopping-basket')}<span>Catálogo</span></button><button data-view="orders" class="${view==='orders'?'active':''}">${icon('receipt-text')}<span>Meus pedidos</span></button><button data-view="benefits" class="${view==='benefits'?'active':''}">${icon('gift')}<span>Meus benefícios</span></button><button data-view="account" class="${view==='account'?'active':''}">${icon('user-round')}<span>Conta</span></button></nav>`}
function guestCard(){if(portalProfile)return'';return `<section class="guest-identify-card"><span>${icon('shield-check')}</span><div><b>Já compra com a gente?</b><p>Informe seu WhatsApp para acompanhar pedidos, campanhas e benefícios.</p></div><button data-identify>Identificar-me</button></section>`}
function benefitHighlight(){if(!portalProfile)return'';const best=bestBenefit();if(!best)return'';const target=campaignTarget(best.campaign,best.progress),current=campaignCurrent(best.campaign,best.progress),available=Number(best.progress?.rewardsAvailable||0),message=available?'Você tem um prêmio disponível!':`Faltam ${Math.max(0,target-current)} para concluir ${best.campaign.nome}.`;return `<section class="benefit-highlight"><div><span>${icon(available?'gift':'sparkles')}</span><div><b>${esc(message)}</b><small>${current} / ${target}</small></div></div><i><em style="width:${Math.min(100,current/target*100)}%"></em></i><button data-view="benefits">Ver meus benefícios</button></section>`}
function campaignForProduct(productId){return visibleCampaigns().find(campaign=>(campaign.produtoIds||[]).includes(productId)||(campaign.regras?.comboProductIds||[]).includes(productId))}
function productCard(item){const quantity=Number(cart[item.id]||0),max=Number(item.maxPerCustomer||0),stock=available(item),soldOut=tracksStock(item)&&stock<=0,disabled=!receiving()||soldOut||(max&&quantity>=max)||stock<=quantity,stockText=tracksStock(item)?(stock>0?`${stock} disponíveis`:'Esgotado'):'Disponível',campaign=campaignForProduct(item.productId);return `<article class="product-card ${disabled?'is-disabled':''} ${quantity?'is-in-cart':''}" data-catalog-item-id="${esc(item.id)}" role="button" tabindex="${disabled?'-1':'0'}" aria-label="${disabled?`${esc(item.productName)} indisponível`:`Adicionar ${esc(item.productName)} ao carrinho`}">${quantity?`<span class="qty-badge">${quantity}</span>`:''}${campaign?`<span class="benefit-product-badge" title="Esta compra conta para ${esc(campaign.nome)}">${icon('gift')}</span>`:''}<div class="product-image">${item.productImage?`<img src="${esc(item.productImage)}" alt="${esc(item.productName)}" loading="lazy">`:`<span class="product-initial">${esc(item.productName.slice(0,2).toUpperCase())}</span>`}</div><h4>${esc(item.productName)}</h4><p>${esc(item.description||item.category)}</p><div class="product-footer"><span class="product-price"><b>${money(item.salePrice)}</b><small>${stockText}</small></span>${quantity?`<span class="catalog-qty-control"><button type="button" data-action="remove-from-cart" data-catalog-item-id="${esc(item.id)}">−</button><b>${quantity}</b><button type="button" data-action="add-to-cart" data-catalog-item-id="${esc(item.id)}" ${disabled?'disabled':''}>+</button></span>`:`<button type="button" class="add-product" data-action="add-to-cart" data-catalog-item-id="${esc(item.id)}" ${disabled?'disabled':''}>+</button>`}</div></article>`}
function catalogView(){const categories=['Todos',...new Set(catalog.items.map(item=>item.category).filter(Boolean))],items=catalog.items.filter(item=>item.active!==false&&(category==='Todos'||item.category===category)&&(!query||`${item.productName} ${item.category} ${item.description}`.toLowerCase().includes(query)));return `${header()}${!navigator.onLine?'<div class="offline-banner">Você está offline. O carrinho continua disponível.</div>':''}<main class="catalog-main"><section class="visit-hero"><h2>${portalProfile?`Olá, ${esc(portalProfile.displayName)}! 👋`:'Olá! Veja o que está disponível. 👋'}</h2><p>${esc(catalog.welcomeText||'Faça seu pedido antecipadamente.')}</p><div class="visit-deadline"><span>${icon('clock')}<span>Pedidos até<b>${esc(catalog.horarioLimite||'—')}</b></span></span><span>${icon('map-pin')}<span>Chegada prevista<b>${esc(catalog.horarioChegada||'—')}</b></span></span></div></section>${benefitHighlight()}${guestCard()}<label class="catalog-search">${icon('search')}<input id="catalog-search" value="${esc(query)}" placeholder="Buscar produto ou categoria"></label><div class="category-row">${categories.map(value=>`<button data-category="${esc(value)}" class="${category===value?'active':''}">${esc(value)}</button>`).join('')}</div><div class="section-title"><h3>${category==='Todos'?'Produtos disponíveis':esc(category)}</h3><small>${items.length} itens</small></div><section class="product-grid">${items.map(productCard).join('')||'<div class="empty-state">Nenhum produto encontrado.</div>'}</section></main>${count()?`<button class="floating-cart" data-view="cart"><span>${count()} itens</span><b>${money(total())}</b></button>`:''}${nav()}`}
function cartCampaignPreview(){if(!portalProfile)return'';for(const {campaign,progress} of relevantCampaigns()){if(!progress||!['buy_get','nth_product'].includes(campaign.tipo))continue;const eligible=(catalog.items||[]).filter(item=>(campaign.produtoIds||[]).includes(item.productId)).reduce((sum,item)=>sum+Number(cart[item.id]||0),0);if(!eligible)continue;const target=campaignTarget(campaign,progress),current=campaignCurrent(campaign,progress),after=(current+eligible)%target,rewards=Math.floor((current+eligible)/target);return `<section class="cart-benefit-preview">${icon('sparkles')}<div><b>Prévia do benefício</b><p>Após a venda ser entregue: ${after} de ${target}.${rewards?` Este pedido completa ${rewards} recompensa(s)!`:` Faltarão ${target-after}.`}</p><small>O progresso real só muda quando o pedido virar uma venda entregue.</small></div></section>`}return''}
function cartView(){const items=catalog.items.filter(item=>cart[item.id]);return `${header('Meu carrinho')}<main class="catalog-main">${items.length?`<section class="cart-list">${items.map(item=>`<article class="cart-item">${item.productImage?`<img class="cart-thumb" src="${esc(item.productImage)}" alt="">`:`<span class="cart-thumb product-initial">${esc(item.productName.slice(0,2))}</span>`}<div><h3>${esc(item.productName)}</h3><small>${money(item.salePrice)} cada</small><div class="qty-control"><button data-minus="${item.id}">−</button><b>${cart[item.id]}</b><button data-add="${item.id}">+</button></div></div><span class="cart-subtotal">${money(Number(cart[item.id])*Number(item.salePrice))}</span></article>`).join('')}</section><label class="cart-note">Observação (opcional)<textarea id="cart-note" placeholder="Alguma observação para seu pedido?">${esc(read(`adiCatalogNote:${visitToken}`,'')||'')}</textarea></label>${cartCampaignPreview()}<section class="summary-box"><div class="summary-row"><span>Subtotal</span><b>${money(total())}</b></div><div class="summary-row total"><span>Total</span><b>${money(total())}</b></div></section><button class="primary-button" id="checkout">Confirmar pedido</button><button class="secondary-button" data-view="catalog">Continuar comprando</button>`:`<section class="empty-state">${icon('shopping-basket')}<h2>Seu carrinho está vazio</h2><button class="primary-button" data-view="catalog">Ver produtos</button></section>`}</main>${nav()}`}
function checkoutView(){const methods=catalog.paymentMethods||['entrega','pix','dinheiro','cartao'];return `${header('Confirmar pedido')}<main class="catalog-main"><section class="visit-hero"><h2>Está quase pronto!</h2><p>${portalProfile?'Confirme os dados do pedido.':'Informe seus dados para enviar o pedido.'}</p></section><form class="identify-form" id="order-form"><label>Nome completo<input name="nome" value="${esc(portalProfile?.displayName||identity.nome||'')}" autocomplete="name" minlength="2" maxlength="120" required></label><label>WhatsApp<input name="telefone" value="${esc(identity.telefone?formatBrazilianPhone(identity.telefone):'')}" inputmode="tel" autocomplete="tel" placeholder="(17) 99999-9999" required ${portalProfile?'readonly':''}></label><label>Loja ou ponto de encontro<input name="local" value="${esc(identity.local||portalProfile?.location||'')}" maxlength="160" placeholder="Ex.: Loja 204"></label><label>Como prefere pagar?<select name="payment">${methods.map(method=>`<option value="${normalizePaymentPreference(method)}">${({entrega:'Pagar na entrega',pix:'PIX',dinheiro:'Dinheiro',cartao:'Cartão',fiado:'Adicionar à conta'}[normalizePaymentPreference(method)]||method)}</option>`).join('')}</select></label>${portalProfile?'':`<p class="catalog-link-notice">${icon('shield-check')} Seus benefícios serão vinculados após a confirmação do pedido.</p>`}<section class="summary-box"><div class="summary-row"><span>${count()} itens</span><b>${money(total())}</b></div></section><button class="primary-button" id="submit-order" type="submit">${submittingOrder?'Enviando pedido…':'Enviar pedido'}</button><button type="button" class="secondary-button" data-view="cart">Voltar ao carrinho</button></form></main>${nav()}`}
function lockedPersonalView(title,text){return `${header(title)}<main class="catalog-main"><section class="personal-locked">${icon('shield-check')}<h2>${esc(title)}</h2><p>${esc(text)}</p><button class="primary-button" data-identify>Identificar-me</button><button class="secondary-button" data-view="catalog">Continuar como visitante</button></section></main>${nav()}`}
function ordersView(){const localOrders=orders.map(item=>item.data).filter(Boolean);if(!portalProfile&&!localOrders.length)return lockedPersonalView('Meus pedidos','Identifique-se para acompanhar seus pedidos neste aparelho.');const profileOrders=portalProfile?.orders||[],all=[...new Map([...profileOrders,...localOrders].map(order=>[order.id,order])).values()].sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt));return `${header('Meus pedidos')}<main class="catalog-main">${!portalProfile?'<p class="local-orders-note">Mostrando apenas os pedidos feitos neste aparelho.</p>':''}${all.length?all.map(order=>`<article class="order-card-public"><header><div><b>Pedido #${esc(order.publicOrderNumber)}</b><small>${new Date(order.createdAt?.toDate?.()||order.createdAt).toLocaleString('pt-BR')}</small></div><span class="status-pill">${({recebido:'Recebido',confirmado:'Confirmado',separando:'Separando',deslocamento:'Em deslocamento',entregue:'Entregue',cancelado:'Cancelado'}[order.orderStatus]||order.orderStatus)}</span></header><ul>${(order.items||[]).map(item=>`<li>${item.quantity}× ${esc(item.name)} — ${money(item.subtotal)}</li>`).join('')}</ul><div class="summary-row total"><span>Total</span><b>${money(order.total)}</b></div></article>`).join(''):'<section class="empty-state"><h2>Nenhum pedido ainda</h2><button class="primary-button" data-view="catalog">Abrir catálogo</button></section>'}</main>${nav()}`}
function benefitCard(campaign){const progress=campaignProgress(campaign.id),target=campaignTarget(campaign,progress),current=campaignCurrent(campaign,progress),available=Number(progress?.rewardsAvailable||0),pct=Math.min(100,current/target*100),started=Boolean(progress);return `<article class="public-campaign-card">${campaign.imagem?`<img src="${esc(campaign.imagem)}" alt="">`:`<span class="public-campaign-icon">${icon(campaign.icone||'gift')}</span>`}<div><span class="public-campaign-type">${available?'Prêmio disponível':started?'Em andamento':'Disponível'}</span><h3>${esc(campaign.nome)}</h3><p>${esc(campaign.descricao||'Participe e aproveite!')}</p>${portalProfile?`<div class="public-progress-head"><b>${campaign.tipo==='points'?`${current} pontos`:'Seu progresso'}</b><span>${current} / ${target}</span></div><i class="public-progress"><em style="width:${pct}%"></em></i><small>${available?`${available} recompensa(s) aguardando resgate`:`Faltam ${Math.max(0,target-current)} para completar`}</small><div class="benefit-actions"><button data-view="catalog">Comprar agora</button>${available?`<button class="primary" data-request-reward="${campaign.id}">Solicitar resgate</button>`:''}</div>`:'<small>Identifique-se para acompanhar seu progresso.</small>'}</div></article>`}
function benefitsView(){const campaigns=visibleCampaigns();return `${header(portalProfile?'Meus benefícios':'Campanhas')}<main class="catalog-main">${portalProfile?'':guestCard()}<section class="campaign-intro"><span>${icon('gift')}</span><div><h2>${portalProfile?'Seus benefícios e recompensas':'Campanhas da Adi Festa'}</h2><p>${portalProfile?'O progresso aumenta somente quando o pedido vira uma venda entregue.':'Conheça as campanhas ativas. Identifique-se para ver seu progresso.'}</p></div></section><div class="section-title"><h3>Campanhas ativas</h3><small>${campaigns.length}</small></div><section class="public-campaign-list">${campaigns.map(benefitCard).join('')||'<section class="empty-state"><h2>Nenhuma campanha ativa</h2></section>'}</section></main>${nav()}`}
function accountView(){if(!portalProfile)return lockedPersonalView('Identificar-se','Informe seu WhatsApp para acessar pedidos e benefícios.');return `${header('Conta')}<main class="catalog-main"><section class="account-card"><span class="account-avatar">${esc(portalProfile.displayName.split(/\s+/).slice(0,2).map(value=>value[0]).join(''))}</span><h2>${esc(portalProfile.displayName)}</h2><p>${esc(portalProfile.maskedPhone)}</p><span class="verified-status">${icon('badge-check')} Identificação confirmada</span><dl><dt>Local</dt><dd>${esc(identity.local||portalProfile.location||'Não informado')}</dd><dt>Conta e saldo</dt><dd>Disponível após confirmação adicional de segurança.</dd></dl><button class="secondary-button" id="switch-client">Trocar cliente</button><button class="secondary-button danger" id="portal-logout">Sair deste aparelho</button></section></main>${nav()}`}
function successView(order){return `${header('Pedido recebido')}<main class="catalog-main"><section class="order-success"><span class="success-icon">${icon('check')}</span><h2>Pedido recebido!</h2><p>Pedido <b>#${esc(order.publicOrderNumber)}</b></p>${portalProfile?'<p>Seu progresso será atualizado quando este pedido for entregue e registrado como venda.</p>':'<p>Você poderá acompanhar este pedido neste aparelho.</p>'}<button class="primary-button" data-view="orders">Ver meu pedido</button><button class="secondary-button" data-view="catalog">Continuar comprando</button></section></main>${nav()}`}
function render(successOrder=null){root.innerHTML=`<div class="catalog-shell">${view==='catalog'?catalogView():view==='cart'?cartView():view==='checkout'?checkoutView():view==='success'?successView(successOrder):view==='orders'?ordersView():view==='benefits'?benefitsView():accountView()}</div>`;window.lucide?.createIcons();bind()}

function openIdentify(){trackPortalEvent('identification_started',{visitToken});document.body.insertAdjacentHTML('beforeend',`<div class="portal-sheet-layer" id="portal-sheet"><section class="portal-sheet"><header><div><h2>Identifique-se</h2><p>Informe o número de WhatsApp usado nas suas compras.</p></div><button data-sheet-close aria-label="Fechar">${icon('x')}</button></header><form id="identify-phone-form"><label>WhatsApp<input name="phone" inputmode="tel" autocomplete="tel" placeholder="(17) 99999-9999" value="${esc(identity.telefone?formatBrazilianPhone(identity.telefone):'')}" required></label><p class="portal-sheet-message" id="identify-message"></p><button class="primary-button">Continuar</button></form></section></div>`);document.querySelector('[data-sheet-close]').onclick=closeSheet;document.querySelector('#identify-phone-form').onsubmit=event=>{event.preventDefault();identifyPhone(new FormData(event.currentTarget).get('phone'))};window.lucide?.createIcons()}
function closeSheet(){document.querySelector('#portal-sheet')?.remove()}
async function identifyPhone(value){const normalizedPhone=normalizeBrazilianPhone(value),message=document.querySelector('#identify-message'),button=document.querySelector('#identify-phone-form button');if(!isValidBrazilianPhone(normalizedPhone)){message.textContent='Informe um número com DDD.';return}button.disabled=true;message.textContent='Procurando seu cadastro…';try{const indexId=await phoneIndexId(normalizedPhone),snap=await getDoc(doc(db,'publicCatalogs',visitToken,'phoneIndex',indexId));if(!snap.exists()||snap.data().active===false){trackPortalEvent('client_not_found');showNewClient(normalizedPhone);return}trackPortalEvent('client_found');showIdentityConfirmation(normalizedPhone,snap.data())}catch(error){console.error('[Portal identify]',error);message.textContent='Não foi possível identificar você agora. Seu carrinho continua salvo.';button.disabled=false}}
function showIdentityConfirmation(phone,data){const sheet=document.querySelector('.portal-sheet');sheet.innerHTML=`<header><div><h2>Encontramos seu cadastro</h2><p>Confirme se estes dados são seus.</p></div><button data-sheet-close>${icon('x')}</button></header><section class="identity-found"><span>${icon('user-round-check')}</span><h3>${esc(data.maskedName)}</h3><p>${esc(data.maskedPhone||maskPhone(phone))}</p><button class="primary-button" id="confirm-identity">Sou eu</button><button class="secondary-button" id="wrong-identity">Não sou eu</button></section>`;sheet.querySelector('[data-sheet-close]').onclick=closeSheet;sheet.querySelector('#wrong-identity').onclick=()=>{closeSheet();openIdentify()};sheet.querySelector('#confirm-identity').onclick=()=>createPortalSession(phone,data);window.lucide?.createIcons()}
function showNewClient(phone){const contact=normalizeBrazilianPhone(catalog.contactPhone||'');const sheet=document.querySelector('.portal-sheet');sheet.innerHTML=`<header><div><h2>Não encontramos esse número</h2><p>Você pode continuar como novo cliente.</p></div><button data-sheet-close>${icon('x')}</button></header><form id="new-client-form"><label>Nome completo<input name="nome" required></label><label>WhatsApp<input name="telefone" value="${esc(formatBrazilianPhone(phone))}" readonly></label><label>Loja ou local<input name="local" value="${esc(identity.local||'')}"></label><label>Observação<textarea name="observacao"></textarea></label><button class="primary-button">Continuar como novo cliente</button><button type="button" class="secondary-button" id="correct-phone">Corrigir telefone</button>${isValidBrazilianPhone(contact)?`<a class="secondary-button portal-whatsapp" href="https://wa.me/${contact}" target="_blank" rel="noopener">Falar pelo WhatsApp</a>`:''}</form>`;sheet.querySelector('[data-sheet-close]').onclick=closeSheet;sheet.querySelector('#correct-phone').onclick=()=>{closeSheet();openIdentify()};sheet.querySelector('#new-client-form').onsubmit=event=>{event.preventDefault();const fd=new FormData(event.currentTarget);identity={nome:String(fd.get('nome')).trim(),telefone:phone,local:String(fd.get('local')).trim(),observacao:String(fd.get('observacao')).trim(),newCustomer:true};save();closeSheet();if(pendingOrderForm){const data=pendingOrderForm;pendingOrderForm=null;submitOrderData(data)}else{toast('Dados salvos. Você pode continuar comprando.');render()}};window.lucide?.createIcons()}
async function createPortalSession(phone,index){const token=randomToken(),tokenHash=await sessionDocumentId(token),expiresAt=new Date(Date.now()+30*864e5).toISOString(),payload={clientRefToken:index.clientRefToken,businessId:catalog.businessId,visitId:catalog.visitId,active:true,createdAt:serverTimestamp(),updatedAt:serverTimestamp(),lastAccessAt:serverTimestamp(),expiresAt,deviceLabel:navigator.userAgent.slice(0,120)};try{await setDoc(doc(db,'publicCatalogs',visitToken,'portalSessions',tokenHash),payload);localStorage.setItem(sessionStorageKey(visitToken),token);identity={...identity,nome:index.maskedName,telefone:phone,newCustomer:false};save();closeSheet();await validatePortalSession();trackPortalEvent('identification_completed');toast('Identificação confirmada.');if(pendingOrderForm){const data=pendingOrderForm;pendingOrderForm=null;submitOrderData(data)}else render()}catch(error){console.error('[Portal session create]',error);toast('Não foi possível criar sua sessão. Seu carrinho continua salvo.')}}
async function validatePortalSession(){const token=localStorage.getItem(sessionStorageKey(visitToken));if(!token)return false;try{const tokenHash=await sessionDocumentId(token),snap=await getDoc(doc(db,'publicCatalogs',visitToken,'portalSessions',tokenHash));if(!snap.exists())throw Error('missing');const session=snap.data();if(session.active!==true||session.businessId!==catalog.businessId||session.visitId!==catalog.visitId||new Date(session.expiresAt)<=new Date())throw Error('expired');const profileSnap=await getDoc(doc(db,'publicCatalogs',visitToken,'portalProfiles',session.clientRefToken));if(!profileSnap.exists()||profileSnap.data().active===false)throw Error('profile');portalSession={...session,tokenHash};portalProfile=profileSnap.data();identity={...identity,nome:portalProfile.displayName,telefone:identity.telefone||'',newCustomer:false};save();updateDoc(doc(db,'publicCatalogs',visitToken,'portalSessions',tokenHash),{lastAccessAt:serverTimestamp(),updatedAt:serverTimestamp()}).catch(()=>{});subscribeProfile(session.clientRefToken);return true}catch{localStorage.removeItem(sessionStorageKey(visitToken));portalSession=null;portalProfile=null;return false}}
function subscribeProfile(clientRefToken){unsub.push(onSnapshot(doc(db,'publicCatalogs',visitToken,'portalProfiles',clientRefToken),snap=>{if(!snap.exists())return;portalProfile=snap.data();if(['catalog','orders','benefits','account'].includes(view))render()}))}
async function logoutPortal(){if(!confirm('Sair deste aparelho? Seu carrinho será preservado.'))return;try{if(portalSession)await updateDoc(doc(db,'publicCatalogs',visitToken,'portalSessions',portalSession.tokenHash),{active:false,revokedAt:serverTimestamp(),updatedAt:serverTimestamp()})}catch{}localStorage.removeItem(sessionStorageKey(visitToken));portalSession=null;portalProfile=null;identity={};save();view='catalog';render();toast('Você está navegando como visitante.')}
async function requestReward(campaignId){if(!portalSession)return openIdentify();const campaign=visibleCampaigns().find(item=>item.id===campaignId),progress=campaignProgress(campaignId);if(!campaign||Number(progress?.rewardsAvailable||0)<1)return toast('Nenhum prêmio disponível para esta campanha.');const id=uuid();try{await setDoc(doc(db,'publicCatalogs',visitToken,'redemptionRequests',id),{id,campaignId,campaignName:campaign.nome,clientRefToken:portalSession.clientRefToken,portalSessionHash:portalSession.tokenHash,status:'solicitado',businessId:catalog.businessId,visitId:catalog.visitId,createdAt:serverTimestamp(),updatedAt:serverTimestamp()});trackPortalEvent('reward_requested',{campaignId});toast('Resgate solicitado. Aguarde a confirmação do vendedor.')}catch{toast('Não foi possível solicitar o resgate agora.')}}

function normalizePaymentPreference(value){
  const normalized=String(value||'').trim().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
  const aliases={'pagar na entrega':'entrega','na entrega':'entrega',entrega:'entrega',pix:'pix',dinheiro:'dinheiro',cartao:'cartao','cartão':'cartao','adicionar a conta':'fiado','adicionar à conta':'fiado',fiado:'fiado'};
  return aliases[normalized]||'entrega';
}
function generateSecureToken(length=32){
  const bytes=crypto.getRandomValues(new Uint8Array(Math.ceil(length/2)));
  return [...bytes].map(byte=>byte.toString(16).padStart(2,'0')).join('').slice(0,length);
}
function orderErrorMessage(error){
  const code=String(error?.code||'').replace('firestore/','');
  if(code==='permission-denied')return'Não foi possível registrar o pedido. Os dados enviados não foram aceitos.';
  if(code==='resource-exhausted'||code==='deadline-exceeded')return'O servidor atingiu um limite temporário. Seu carrinho continua salvo; tente novamente mais tarde.';
  if(code==='unavailable'||!navigator.onLine)return'Sem conexão. Seu carrinho continua salvo.';
  return'Não foi possível enviar o pedido. Tente novamente.';
}
function orderWriteWithTimeout(reference,payload,timeoutMs=12000){
  let timer;
  const timeout=new Promise((_,reject)=>{timer=setTimeout(()=>reject(Object.assign(new Error('Tempo limite ao registrar pedido.'),{code:'deadline-exceeded'})),timeoutMs)});
  return Promise.race([setDoc(reference,payload),timeout]).finally(()=>clearTimeout(timer));
}
function prepareOrder(form){
  const fd=new FormData(form),nome=String(fd.get('nome')||'').trim(),normalizedPhone=normalizeBrazilianPhone(fd.get('telefone'));
  if(nome.length<2||nome.length>120){toast('Informe um nome com pelo menos 2 caracteres.');return null}
  if(!isValidBrazilianPhone(normalizedPhone)||normalizedPhone.length<10||normalizedPhone.length>15){toast('Informe um WhatsApp válido com DDD.');return null}
  return{nome,telefone:normalizedPhone,local:String(fd.get('local')||'').trim(),payment:normalizePaymentPreference(fd.get('payment'))}
}
async function submitOrder(form){
  console.log('[Catalog Order] submit started');
  if(submittingOrder)return;
  const data=prepareOrder(form);
  if(!data)return;
  if(!navigator.onLine){toast('Sem conexão. Seu carrinho continua salvo.');return}
  submittingOrder=true;
  const button=form.querySelector('#submit-order');
  if(button){button.disabled=true;button.textContent='Enviando pedido…'}
  try{await submitOrderData(data)}
  finally{
    submittingOrder=false;
    if(button?.isConnected){button.disabled=false;button.textContent='Enviar pedido'}
  }
}
async function submitOrderData(data){
  const normalizedItems=catalog.items.filter(item=>cart[item.id]).map(item=>({productId:String(item.productId||''),catalogItemId:String(item.id||''),name:String(item.productName||'').slice(0,160),image:String(item.productImage||''),quantity:Number(cart[item.id]),unitPrice:Number(Number(item.salePrice).toFixed(2)),subtotal:Number((Number(cart[item.id])*Number(item.salePrice)).toFixed(2))}));
  const canonicalTotal=Number(normalizedItems.reduce((sum,item)=>sum+item.subtotal,0).toFixed(2));
  if(!normalizedItems.length){toast('Seu carrinho está vazio.');return false}
  if(!(canonicalTotal>0&&canonicalTotal<=10000)){toast('O total do pedido precisa estar entre R$ 0,01 e R$ 10.000,00.');return false}
  identity={...identity,nome:data.nome,telefone:data.telefone,local:data.local};
  save();
  const attemptKey=JSON.stringify({items:normalizedItems.map(item=>[item.catalogItemId,item.quantity,item.unitPrice]),total:canonicalTotal,nome:data.nome,telefone:data.telefone,local:data.local,payment:data.payment});
  if(!pendingOrderAttempt||pendingOrderAttempt.key!==attemptKey)pendingOrderAttempt={key:attemptKey,orderId:uuid(),orderAccessToken:generateSecureToken(32),publicOrderNumber:`AF${Date.now().toString().slice(-6)}`};
  const {orderId,orderAccessToken,publicOrderNumber}=pendingOrderAttempt,path=`publicCatalogs/${visitToken}/orders/${orderId}`;
  const payload={
    id:orderId,
    catalogToken:visitToken,
    source:'online_catalog',
    orderStatus:'recebido',
    customerName:data.nome.trim(),
    customerPhone:normalizeBrazilianPhone(data.telefone),
    customerLocation:data.local.trim(),
    items:normalizedItems,
    subtotal:Number(canonicalTotal),
    discount:0,
    fee:0,
    total:Number(canonicalTotal),
    paymentPreference:normalizePaymentPreference(data.payment),
    orderAccessToken,
    operationId:`catalog-order:${orderId}`,
    publicOrderNumber,
    visitId:catalog.visitId,
    clientRefToken:portalSession?.clientRefToken||null,
    portalSessionHash:portalSession?.tokenHash||null,
    paymentStatus:'pendente',
    note:read(`adiCatalogNote:${visitToken}`,'')||identity.observacao||'',
    createdAt:serverTimestamp(),
    updatedAt:serverTimestamp()
  };
  console.log('[Catalog Order] payload',payload);
  console.log('[Catalog Order] path',path);
  try{
    await orderWriteWithTimeout(doc(db,'publicCatalogs',visitToken,'orders',orderId),payload);
    const localOrder={...payload,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};
    orders.unshift({id:orderId,accessToken:orderAccessToken,data:localOrder});
    cart={};
    pendingOrderAttempt=null;
    localStorage.removeItem(`adiCatalogNote:${visitToken}`);
    save();
    subscribeOrder(orderId);
    trackPortalEvent('order_created',{visitToken,identified:Boolean(portalSession)});
    view='success';
    render(localOrder);
    toast('Pedido enviado com sucesso.');
    return true;
  }catch(error){
    console.error('[Catalog Order] create failed',error);
    toast(orderErrorMessage(error));
    return false;
  }
}
function subscribeOrder(id){const entry=orders.find(order=>order.id===id);if(!entry)return;unsub.push(onSnapshot(doc(db,'publicCatalogs',visitToken,'orders',id),snap=>{if(!snap.exists())return;entry.data={id:snap.id,...snap.data()};save();if(view==='orders')render()}))}
function changeCart(id,delta=1,source=null,options={}){const item=catalog.items.find(product=>String(product.id)===String(id));if(!item)return false;if(delta>0&&!receiving())return toast('Esta visita não está mais recebendo pedidos.');const current=Number(cart[item.id]||0),next=Math.max(0,current+Number(delta||0)),stock=available(item),limit=Number(item.maxPerCustomer||0);if(delta>0&&tracksStock(item)&&next>stock)return toast(`Somente ${stock} unidade(s) disponível(is).`);if(delta>0&&limit&&next>limit)return toast(`Limite de ${limit} unidade(s) por cliente.`);next?cart[item.id]=next:delete cart[item.id];save();navigator.vibrate?.(15);trackPortalEvent('product_added',{productId:item.productId,quantity:next});render();if(delta>0&&!options.silent)toast(`${item.productName} adicionado`,item.id);return true}
function bind(){root.querySelector('#catalog-search')?.addEventListener('input',event=>{query=event.target.value.toLowerCase();const position=event.target.selectionStart;render();const input=root.querySelector('#catalog-search');input.focus();input.setSelectionRange(position,position)});root.querySelector('#cart-note')?.addEventListener('input',event=>localStorage.setItem(`adiCatalogNote:${visitToken}`,JSON.stringify(event.target.value)));root.querySelector('#order-form')?.addEventListener('submit',async event=>{event.preventDefault();event.stopPropagation();await submitOrder(event.currentTarget)});root.querySelector('#portal-logout')?.addEventListener('click',logoutPortal);root.querySelector('#switch-client')?.addEventListener('click',logoutPortal)}
root.addEventListener('click',event=>{const add=event.target.closest('[data-action="add-to-cart"],[data-add]');if(add){event.stopPropagation();changeCart(add.dataset.catalogItemId||add.dataset.add,1,add);return}const remove=event.target.closest('[data-action="remove-from-cart"],[data-minus]');if(remove){event.stopPropagation();changeCart(remove.dataset.catalogItemId||remove.dataset.minus,-1,remove,{silent:true});return}const card=event.target.closest('.product-card[data-catalog-item-id]');if(card&&!event.target.closest('button,a,input,select,textarea')){changeCart(card.dataset.catalogItemId,1,card);return}const targetView=event.target.closest('[data-view]');if(targetView){view=targetView.dataset.view;trackPortalEvent(view==='cart'?'cart_opened':view==='benefits'?'benefit_viewed':'navigation',{view});render();return}if(event.target.closest('[data-identify]')){openIdentify();return}const categoryButton=event.target.closest('[data-category]');if(categoryButton){category=categoryButton.dataset.category;render();return}if(event.target.closest('#checkout')){view='checkout';render();return}const reward=event.target.closest('[data-request-reward]');if(reward){requestReward(reward.dataset.requestReward);return}});
root.addEventListener('keydown',event=>{const card=event.target.closest('.product-card[data-catalog-item-id]');if(card&&(event.key==='Enter'||event.key===' ')){event.preventDefault();changeCart(card.dataset.catalogItemId,1,card)}});
async function start(){try{catalog=await loadPublicCatalog();localStorage.setItem(`adiCatalogCache:${visitToken}`,JSON.stringify(catalog));orders.forEach(order=>subscribeOrder(order.id));const hadSession=Boolean(localStorage.getItem(sessionStorageKey(visitToken))),valid=await validatePortalSession();trackPortalEvent('catalog_opened',{visitToken,identified:Boolean(portalProfile)});render();if(hadSession&&!valid)toast('Para proteger seus dados, confirme sua identificação novamente.')}catch(error){const code=normalizedCatalogErrorCode(error);if(code==='network'){const cached=read(`adiCatalogCache:${visitToken}`,null);if(cached?.active===true&&(!cached.catalogToken||cached.catalogToken===visitToken)){catalog=cached;render();root.insertAdjacentHTML('afterbegin',`<div class="catalog-network-warning" role="status">${icon('cloud-off')}<span><b>Não foi possível conectar ao servidor</b><small>Mostrando a última versão salva.</small></span></div>`);window.lucide?.createIcons();console.warn('[Public catalog load]',{code:'network-cache',documentPath:`publicCatalogs/${visitToken}`,urlToken:visitToken});return}}showCatalogError(code,error)}}
function startDemo(){catalog={token:'demo',visitId:'demo',businessId:'adi-festa',publicName:'Adi Festa',local:'Shopping Iguatemi',nome:'Visita de hoje',horarioChegada:'14:00',horarioLimite:'13:30',status:'recebendo',active:true,welcomeText:'Veja os produtos disponíveis e faça seu pedido.',paymentMethods:['entrega','pix','dinheiro','cartao'],items:[['Cone Trufado','Doces',8,4],['Brownie recheado','Doces',6.5,8],['Ninho com Nutella','Doces',7.5,10],['Energético','Bebidas',9,0]].map((value,index)=>({id:`demo-${index}`,productId:`p-${index}`,productName:value[0],category:value[1],salePrice:value[2],availableQuantity:value[3],controlaEstoque:true,description:'Preparado com carinho pela Adi Festa',active:true})),campaigns:[{id:'camp-1',nome:'Compre 5 Cones e ganhe 1 grátis',descricao:'A cada 5 cones, você ganha 1 cone grátis!',tipo:'buy_get',icone:'shopping-cart',produtoIds:['p-0'],regras:{requiredQuantity:5,rewardQuantity:1}},{id:'camp-2',nome:'Acumule pontos e troque por prêmios',descricao:'A cada R$ 1,00 você ganha 1 ponto.',tipo:'points',icone:'award',regras:{rewardPoints:120}}]};if(params.get('identified')==='1'){portalSession={clientRefToken:'demo-client',tokenHash:'demo'};portalProfile={displayName:'Gu Oficina',maskedPhone:'•••••-32859',location:'Loja 204',campaigns:[{campaignId:'camp-1',currentProgress:3,target:5,rewardsAvailable:Number(params.get('reward')==='1')},{campaignId:'camp-2',points:72,target:120,rewardsAvailable:0}],orders:[]}}render()}
addEventListener('online',()=>catalog&&render());addEventListener('offline',()=>catalog&&render());
params.get('demo')==='1'?startDemo():start();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(error=>console.error('[Catalog service worker]',error));
