(function(){
  'use strict';
  const base=window.ClientesPage;
  if(!base)return;
  const desktopRender=base.render.bind(base),desktopBind=base.bind.bind(base);
  const mq=matchMedia('(max-width: 780px)');
  const state={query:'',filter:'todos',sort:'maiorDebito',limit:50,sheet:false};
  let observer=null;
  const icon=name=>`<i data-lucide="${name}"></i>`;
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const norm=value=>String(value??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
  const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
  const dateValue=value=>value?new Date(value).getTime()||0:0;
  const dateLabel=value=>dateValue(value)?new Date(value).toLocaleDateString('pt-BR'):'Nunca';
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  const debt=client=>Math.abs(Math.min(0,Number(client.saldo)||0));
  let dataCache=null;
  const allData=()=>dataCache||(dataCache=DB.carregar());
  const lastCharge=(client,db=allData())=>(db.cobrancas||[]).filter(x=>x.clienteId===client.id).sort((a,b)=>dateValue(b.data)-dateValue(a.data))[0]||null;
  const relative=value=>{const time=dateValue(value);if(!time)return'Nunca';const days=Math.max(0,Math.floor((Date.now()-time)/86400000));return days===0?'Hoje':days===1?'Ontem':`há ${days} dias`};
  const recentPayment=(client,db)=>{const cutoff=Date.now()-7*86400000;return(db.pagamentos||[]).some(p=>p.clienteId===client.id&&dateValue(p.data)>=cutoff)};
  function stats(){const db=allData(),clients=(db.clientes||[]).filter(c=>c.ativo!==false),debtors=clients.filter(c=>Number(c.saldo)<0),today=new Date().toISOString().slice(0,10),charges=(db.cobrancas||[]).filter(x=>String(x.data||'').slice(0,10)===today);return{db,clients,debtors,total:debtors.reduce((sum,c)=>sum+debt(c),0),charges:charges.length}}
  function filtered(){const {db,clients}=stats(),query=norm(state.query),digits=String(state.query).replace(/\D/g,'');let list=clients.filter(c=>!query||norm(`${c.nome} ${c.apelido||''} ${c.telefone||''} ${c.observacoes||c.observacao||''}`).includes(query)||(digits&&String(c.telefone||'').replace(/\D/g,'').includes(digits)));list=list.filter(c=>state.filter==='todos'||state.filter==='debito'&&Number(c.saldo)<0||state.filter==='credito'&&Number(c.saldo)>0||state.filter==='zero'&&Number(c.saldo)===0||state.filter==='nunca'&&!lastCharge(c,db)||state.filter==='semTelefone'&&String(c.telefone||'').replace(/\D/g,'').length<10||state.filter==='pagamento'&&recentPayment(c,db));const chargeTime=c=>dateValue(lastCharge(c,db)?.data);list.sort((a,b)=>state.sort==='maiorDebito'?debt(b)-debt(a):state.sort==='menorDebito'?debt(a)-debt(b):state.sort==='nomeAsc'?String(a.nome).localeCompare(String(b.nome),'pt-BR'):state.sort==='nomeDesc'?String(b.nome).localeCompare(String(a.nome),'pt-BR'):state.sort==='ultimaCompra'?dateValue(b.ultimaCompra)-dateValue(a.ultimaCompra):state.sort==='ultimaCobranca'?chargeTime(b)-chargeTime(a):Number(b.totalComprado||0)-Number(a.totalComprado||0));return list}
  function badge(client){const saldo=Number(client.saldo)||0,status=saldo<0?'debit':saldo>0?'credit':'zero',label=saldo<0?'Débito':saldo>0?'Crédito':'Sem saldo';return`<span class="mobile-client-status ${status}">${label}</span>`}
  function chip(key,label,count=''){return`<button class="mobile-filter-chip ${state.filter===key?'active':''}" type="button" data-mobile-filter="${key}"><span>${label}</span>${count!==''?`<b>${count}</b>`:''}</button>`}
  function card(client,index){const saldo=Number(client.saldo)||0,type=saldo<0?'debit':saldo>0?'credit':'zero',charge=lastCharge(client),phone=String(client.telefone||'').replace(/\D/g,''),balance=saldo<0?money(debt(client)):saldo>0?money(saldo):money(0);return`<div class="mobile-swipe-shell ${type}" data-swipe-client="${client.id}" style="--delay:${Math.min(index,12)*28}ms"><div class="swipe-action swipe-receive">${icon('circle-dollar-sign')}<span>Receber pagamento</span></div><div class="swipe-action swipe-history">${icon('history')}<span>Histórico</span></div><article class="mobile-client-card" data-mobile-card="${client.id}"><div class="mobile-client-main"><span class="mobile-client-avatar">${esc(initials(client.nome))}</span><div class="mobile-client-identity"><h3>${esc(client.nome)}</h3><p>${esc(client.telefone)||'Sem telefone'}${phone.length>=10?` <button class="mobile-phone-whatsapp" type="button" data-mobile-whatsapp="${client.id}" aria-label="Abrir WhatsApp">${icon('message-circle')}</button>`:''}</p></div><div class="mobile-client-balance">${badge(client)}<strong>${balance}</strong><small>${saldo<0?'em aberto':saldo>0?'em crédito':'conta zerada'}</small></div><button class="mobile-card-menu-trigger" type="button" data-mobile-menu="${client.id}" aria-label="Mais ações">${icon('ellipsis-vertical')}</button></div><div class="mobile-client-facts"><span>${icon('calendar-days')}<span><small>Última compra</small><b>${dateLabel(client.ultimaCompra)}</b></span></span><span>${icon('clock-3')}<span><small>Última cobrança</small><b>${relative(charge?.data)}</b></span></span></div><div class="mobile-client-actions"><button class="mobile-receive" type="button" data-mobile-receive="${client.id}" ${saldo>=0?'disabled':''}>${icon('circle-dollar-sign')} Receber</button><button class="mobile-whatsapp" type="button" data-mobile-whatsapp="${client.id}" ${phone.length<10?'disabled':''}>${icon('message-circle')} WhatsApp</button><button class="mobile-more" type="button" data-mobile-menu="${client.id}" aria-label="Mais ações">${icon('ellipsis')}</button></div><div class="mobile-card-menu" data-mobile-menu-for="${client.id}" hidden><button data-mobile-edit="${client.id}">${icon('pencil')} Editar</button><button data-mobile-history="${client.id}">${icon('history')} Histórico</button><button data-mobile-charges="${client.id}">${icon('message-square-text')} Cobranças</button><button data-mobile-adjust="${client.id}">${icon('sliders-horizontal')} Ajustar saldo</button><button class="danger" data-mobile-delete="${client.id}">${icon('trash-2')} Excluir</button></div></article></div>`}
  function sheet(){return`<div class="mobile-filter-overlay ${state.sheet?'open':''}" data-close-mobile-sheet></div><section class="mobile-filter-sheet ${state.sheet?'open':''}" aria-hidden="${!state.sheet}"><div class="sheet-handle"></div><header><div><h3>Filtros de clientes</h3><p>Encontre rapidamente quem você procura.</p></div><button type="button" data-close-mobile-sheet>${icon('x')}</button></header><div class="mobile-sheet-options"><button data-sheet-filter="debito">${icon('circle-dollar-sign')} Clientes devendo</button><button data-sheet-filter="credito">${icon('badge-dollar-sign')} Clientes com crédito</button><button data-sheet-filter="semTelefone">${icon('phone-off')} Sem telefone</button><button data-sheet-filter="nunca">${icon('bell-off')} Nunca cobrados</button><button data-sheet-filter="pagamento">${icon('circle-check')} Pagamento recente</button></div><button class="mobile-sheet-clear" type="button" data-sheet-filter="todos">Limpar filtros</button></section>`}
  function renderMobile(){const {clients,debtors,total,charges}=stats(),counts={credito:clients.filter(c=>Number(c.saldo)>0).length,zero:clients.filter(c=>Number(c.saldo)===0).length,nunca:clients.filter(c=>!lastCharge(c)).length,semTelefone:clients.filter(c=>String(c.telefone||'').replace(/\D/g,'').length<10).length,pagamento:clients.filter(c=>recentPayment(c,allData())).length},list=filtered(),shown=list.slice(0,state.limit);return`<section class="clients-page clients-mobile-page"><div class="mobile-client-kpis"><article class="danger">${icon('circle-dollar-sign')}<span><small>Em aberto</small><strong>${money(total)}</strong><em>valor total</em></span></article><article class="danger">${icon('user-round')}<span><small>Clientes devendo</small><strong>${debtors.length}</strong><em>${clients.length?Math.round(debtors.length/clients.length*100):0}% do total</em></span></article><article class="warning">${icon('bell-ring')}<span><small>Cobranças hoje</small><strong>${charges}</strong><em>registradas</em></span></article></div><div class="mobile-client-search-row"><label>${icon('search')}<input id="mobile-client-search" value="${esc(state.query)}" autocomplete="off" placeholder="Buscar cliente por nome ou telefone..."></label><button id="mobile-open-filters" type="button" aria-label="Abrir filtros">${icon('list-filter')}</button></div><div class="mobile-filter-scroller">${chip('todos','Todos',clients.length)}${chip('debito','Devendo',debtors.length)}${chip('credito','Crédito',counts.credito)}${chip('zero','Sem saldo',counts.zero)}${chip('nunca','Nunca cobrados',counts.nunca)}${chip('semTelefone','Sem telefone',counts.semTelefone)}${chip('pagamento','Pagamento recente',counts.pagamento)}</div><div class="mobile-sort-row"><label>${icon('arrow-up-down')}<span>Ordenar por</span><select id="mobile-client-sort"><option value="maiorDebito">Maior dívida</option><option value="menorDebito">Menor dívida</option><option value="nomeAsc">Nome A-Z</option><option value="nomeDesc">Nome Z-A</option><option value="ultimaCompra">Última compra</option><option value="ultimaCobranca">Última cobrança</option><option value="totalComprado">Maior total comprado</option></select></label><small>${list.length} cliente${list.length===1?'':'s'}</small></div><div class="mobile-client-list" id="mobile-client-list">${shown.map(card).join('')||`<div class="mobile-client-empty">${icon('search-x')}<h3>Nenhum cliente encontrado</h3><p>Tente mudar a busca ou os filtros.</p></div>`}</div>${shown.length<list.length?`<div class="mobile-load-sentinel" id="mobile-load-sentinel"><span></span>Carregando mais clientes...</div>`:''}${sheet()}<div class="mobile-legacy-hooks" aria-hidden="true"><button id="new-client"></button><button id="import-csv"></button><input id="search"><div id="entity-list"></div></div></section>`}
  function render(){if(mq.matches){dataCache=null;return renderMobile()}return desktopRender()}
  function refreshMobile(reset=false){dataCache=null;if(reset)state.limit=50;const app=document.querySelector('#app');if(!app)return;const y=scrollY;app.innerHTML=renderMobile();app.querySelector('.clients-page').dataset.clientsBound='true';bindMobile();scrollTo({top:y})}
  function perform(action,id){if(action==='receive'){const client=Clientes.obter(id);if(!client||Number(client.saldo)>=0)return Utils.toast('Cliente sem débito em aberto');base.receive(id)}if(action==='history')base.profile(id)}
  function bindSwipe(shell){const card=shell.querySelector('.mobile-client-card');let startX=0,delta=0,dragging=false,pointer=null;const reset=()=>{card.style.transition='transform .32s cubic-bezier(.22,.8,.25,1)';card.style.transform='translateX(0)';shell.classList.remove('drag-right','drag-left','ready');setTimeout(()=>card.style.transition='',330)};card.addEventListener('pointerdown',event=>{if(event.target.closest('button,input,select,a'))return;startX=event.clientX;pointer=event.pointerId;delta=0;dragging=true;card.setPointerCapture?.(pointer);shell.classList.add('dragging')});card.addEventListener('pointermove',event=>{if(!dragging||event.pointerId!==pointer)return;delta=Math.max(-card.offsetWidth*.82,Math.min(card.offsetWidth*.82,event.clientX-startX));if(Math.abs(delta)<8)return;card.style.transform=`translateX(${delta}px)`;shell.classList.toggle('drag-right',delta>0);shell.classList.toggle('drag-left',delta<0);shell.classList.toggle('ready',Math.abs(delta)>=card.offsetWidth*.7)});const end=event=>{if(!dragging||event.pointerId!==pointer)return;dragging=false;shell.classList.remove('dragging');const action=delta>0?'receive':'history',execute=Math.abs(delta)>=card.offsetWidth*.7;if(execute){card.style.transition='transform .22s ease';card.style.transform=`translateX(${delta>0?card.offsetWidth:-card.offsetWidth}px)`;navigator.vibrate?.(35);setTimeout(()=>{perform(action,shell.dataset.swipeClient);reset()},180)}else reset()};card.addEventListener('pointerup',end);card.addEventListener('pointercancel',end)}
  function closeMenus(){document.querySelectorAll('.mobile-card-menu').forEach(menu=>menu.hidden=true)}
  function bindMobile(){const search=document.querySelector('#mobile-client-search'),sort=document.querySelector('#mobile-client-sort');if(!search)return;sort.value=state.sort;let timer;search.addEventListener('input',event=>{clearTimeout(timer);state.query=event.target.value;timer=setTimeout(()=>refreshMobile(true),80)});sort.addEventListener('change',event=>{state.sort=event.target.value;refreshMobile(true)});document.querySelectorAll('[data-mobile-filter]').forEach(button=>button.onclick=()=>{state.filter=button.dataset.mobileFilter;state.sort=state.filter==='debito'?'maiorDebito':state.sort;refreshMobile(true)});document.querySelector('#mobile-open-filters').onclick=()=>{state.sheet=true;refreshMobile()};document.querySelectorAll('[data-close-mobile-sheet]').forEach(button=>button.onclick=()=>{state.sheet=false;refreshMobile()});document.querySelectorAll('[data-sheet-filter]').forEach(button=>button.onclick=()=>{state.filter=button.dataset.sheetFilter;state.sheet=false;refreshMobile(true)});document.querySelector('#mobile-client-list').onclick=event=>{const button=event.target.closest('button');if(!button)return;const id=button.dataset.mobileReceive||button.dataset.mobileWhatsapp||button.dataset.mobileMenu||button.dataset.mobileEdit||button.dataset.mobileHistory||button.dataset.mobileCharges||button.dataset.mobileAdjust||button.dataset.mobileDelete;if(button.dataset.mobileReceive)base.receive(id);else if(button.dataset.mobileWhatsapp)base.whatsapp(id);else if(button.dataset.mobileMenu){const menu=document.querySelector(`[data-mobile-menu-for="${CSS.escape(id)}"]`),wasHidden=menu.hidden;closeMenus();menu.hidden=!wasHidden}else if(button.dataset.mobileEdit)base.clientForm(id);else if(button.dataset.mobileHistory||button.dataset.mobileCharges)base.profile(id);else if(button.dataset.mobileAdjust)base.adjust(id);else if(button.dataset.mobileDelete)Modais.confirmar('cliente',()=>{Clientes.excluir(id);refreshMobile()})};document.querySelectorAll('.mobile-swipe-shell').forEach(bindSwipe);observer?.disconnect();const sentinel=document.querySelector('#mobile-load-sentinel');if(sentinel){observer=new IntersectionObserver(entries=>{if(entries[0].isIntersecting){state.limit+=50;refreshMobile()}},{rootMargin:'240px'});observer.observe(sentinel)}window.lucide?.createIcons()}
  function bind(){return mq.matches?bindMobile():desktopBind()}
  base.render=render;base.bind=bind;
  const originalClientForm=base.clientForm.bind(base);
  base.clientForm=id=>{originalClientForm(id);if(!mq.matches)return;const nameField=document.querySelector('#modal input[name="nome"]')?.closest('.field'),client=id?Clientes.obter(id):{};nameField?.insertAdjacentHTML('afterend',`<div class="field full"><label>Apelido</label><input name="apelido" value="${esc(client?.apelido||'')}" placeholder="Como você conhece este cliente"></div>`)};
  document.querySelector('#mobile-client-fab')?.addEventListener('click',()=>{if(Router.atual()!=='produtos')base.clientForm()});
  function search(query){state.query=query;state.limit=50;dataCache=null;observer?.disconnect();document.querySelector('#mobile-load-sentinel')?.remove();const list=filtered(),shown=list.slice(0,state.limit),root=document.querySelector('#mobile-client-list');if(!root)return;root.innerHTML=shown.map(card).join('')||`<div class="mobile-client-empty">${icon('search-x')}<h3>Nenhum cliente encontrado</h3><p>Tente mudar a busca ou os filtros.</p></div>`;const count=document.querySelector('.mobile-sort-row>small');if(count)count.textContent=`${list.length} cliente${list.length===1?'':'s'}`;document.querySelectorAll('.mobile-swipe-shell',root).forEach(bindSwipe);window.lucide?.createIcons()}
  window.ClientesMobile={applyFilter(filter='todos',sort='maiorDebito'){state.filter=filter;state.sort=sort;state.query='';state.limit=50;state.sheet=false;dataCache=null},search,refresh:refreshMobile};
  mq.addEventListener('change',()=>{if(location.hash.includes('/clientes'))base.refresh()});
})();
