(function(){
  'use strict';
  const $=selector=>document.querySelector(selector),esc=value=>Utils.escapar(value),money=value=>Utils.dinheiro(value),icon=name=>`<i data-lucide="${name}"></i>`;
  const date=value=>value?new Date(value).toLocaleDateString('pt-BR'):'Sem dados';
  const dateTime=value=>value?new Date(value).toLocaleString('pt-BR',{dateStyle:'short',timeStyle:'short'}):'Sem dados';
  function relative(value){if(!value)return'Sem dados';const days=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/86400000));return days===0?'Hoje':days===1?'Ontem':`Há ${days} dias`}
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(item=>item[0]).join('').toUpperCase();
  const metric=(iconName,label,value,help='')=>`<article class="crm-metric">${icon(iconName)}<span><small>${label}</small><strong>${value}</strong>${help?`<em>${help}</em>`:''}</span></article>`;
  function metrics(profile){const m=profile.metrics;return `<section class="crm-metrics" aria-label="Indicadores do cliente">
    ${metric('badge-dollar-sign','Valor total gasto',money(m.totalSpent))}${metric('shopping-bag','Quantidade de compras',m.purchaseCount||'Sem dados')}${metric('calculator','Ticket médio',m.purchaseCount?money(m.averageTicket):'Sem dados')}
    ${metric('calendar-plus','Primeira compra',date(m.firstPurchase))}${metric('calendar-check','Última compra',date(m.lastPurchase))}${metric('clock-3','Dias sem comprar',m.daysWithoutPurchase===null?'Sem dados':`${m.daysWithoutPurchase} dias`,CRMCliente.formatActivity(m.activity))}
    ${metric('trophy','Maior compra',m.largestPurchase?money(m.largestPurchase):'Sem dados')}${metric('hand-coins','Valor em aberto',money(m.openBalance))}${metric('message-circle','Última cobrança',relative(m.lastCharge))}
    ${metric('phone-call','Último contato',relative(m.lastContact))}${metric('package-heart','Produto mais comprado',esc(m.topProduct))}${metric('tags','Categoria favorita',esc(m.favoriteCategory))}
  </section>`}
  function insights(profile){return `<section class="crm-section"><header><div><h3>Insights automáticos</h3><p>Sinais importantes deste relacionamento.</p></div>${icon('sparkles')}</header><div class="crm-insights">${profile.insights.map(item=>`<article class="${item.tone}">${icon(item.icon)}<p>${esc(item.text)}</p></article>`).join('')||'<p class="crm-empty-inline">Ainda não há dados suficientes para gerar insights.</p>'}</div></section>`}
  function chart(profile){const max=Math.max(1,...profile.monthly.map(item=>item.value));return `<section class="crm-section crm-chart"><header><div><h3>Valor gasto por mês</h3><p>Últimos seis meses</p></div>${icon('chart-no-axes-column-increasing')}</header><div class="crm-bars" role="img" aria-label="Gráfico do valor gasto nos últimos seis meses">${profile.monthly.map(item=>`<div><span><i style="height:${Math.max(item.value?8:2,Math.round(item.value/max*100))}%"></i></span><b>${esc(item.label)}</b><small>${item.value?money(item.value):'R$ 0'}</small></div>`).join('')}</div></section>`}
  function favorites(profile){return `<section class="crm-section"><header><div><h3>Produtos favoritos</h3><p>Itens mais comprados pelo cliente.</p></div>${icon('package-heart')}</header><div class="crm-favorites">${profile.products.map((item,index)=>`<article><span>${index+1}</span><div><b>${esc(item.nome)}</b><small>${esc(item.categoria)} · Última compra ${date(item.ultimaCompra)}</small></div><strong>${item.quantidade} un.</strong></article>`).join('')||'<p class="crm-empty-inline">Sem produtos comprados.</p>'}</div></section>`}
  function campaigns(profile){const c=profile.campaigns;return `<section class="crm-section"><header><div><h3>Campanhas e fidelidade</h3><p>Participações, pontos e recompensas.</p></div>${icon('gift')}</header><div class="crm-campaign-kpis"><span><b>${c.participations}</b><small>Participações</small></span><span><b>${c.redemptions}</b><small>Resgates</small></span><span><b>${c.points.toLocaleString('pt-BR')}</b><small>Pontos atuais</small></span><span><b>${c.available}</b><small>Recompensas</small></span></div>${c.progress.length?`<div class="crm-campaign-list">${c.progress.slice(0,4).map(item=>`<div><b>${esc(item.campaignName)}</b><small>${Number(item.currentProgress??item.progress??item.progresso??0)} de ${Number(item.target??item.threshold??0)||'—'}</small></div>`).join('')}</div>`:''}</section>`}
  const renewalUnit=(unit,value)=>({days:value===1?'dia':'dias',weeks:value===1?'semana':'semanas',months:value===1?'mês':'meses',years:value===1?'ano':'anos'}[unit]||'dias');
  const renewalStatus=item=>({active:'Ativa',expired:'Vencida',paused:'Pausada',cancelled:'Cancelada'}[CustomerSubscriptions.effectiveStatus(item)]||'Ativa');
  function renewalMessage(item,client){const product=Produtos.obter(item.productId),name=item.label||product?.nome||'renovação',expiry=date(item.expiresAt),days=Math.ceil((new Date(item.expiresAt)-new Date())/86400000),timing=days>1?`vence em ${days} dias`:days===1?'vence amanhã':days===0?'vence hoje':'está vencido';return item.renewalMessage||`Olá, ${client.nome}! Seu ${name} ${timing}, em ${expiry}. Deseja renovar por mais ${item.durationValue} ${renewalUnit(item.durationUnit,item.durationValue)}?`}
  function renewalsMarkup(clientId){const items=CustomerSubscriptions.forClient(clientId);return `<section class="crm-section crm-renewals" data-crm-renewals="${clientId}"><header><div><h3>Renovações</h3><p>Vigências, vencimentos e contato para renovar.</p></div>${icon('calendar-clock')}</header><div class="crm-renewal-list">${items.map(item=>{const product=Produtos.obter(item.productId),variant=item.variantId?ProductVariations.get(item.variantId):null,status=CustomerSubscriptions.effectiveStatus(item);return `<article class="status-${status}"><div><b>${esc(item.label||product?.nome||'Renovação')}</b><small>${esc(variant?ProductVariations.displayName(variant):product?.nome||'')} · ${renewalStatus(item)}</small></div><span><b>${date(item.expiresAt)}</b><small>${money(item.contractedPrice)} / ${item.durationValue} ${renewalUnit(item.durationUnit,item.durationValue)}</small></span><div class="crm-renewal-actions"><button class="btn btn-primary" data-renew-subscription="${item.id}">${icon('refresh-cw')} Renovar</button><button class="btn btn-light" data-renewal-whatsapp="${item.id}">${icon('message-circle')} WhatsApp</button><details><summary aria-label="Mais ações">${icon('ellipsis-vertical')}</summary><button data-subscription-status="paused" data-subscription-id="${item.id}">Pausar</button><button data-subscription-status="active" data-subscription-id="${item.id}">Reativar</button><button data-subscription-status="cancelled" data-subscription-id="${item.id}">Cancelar</button></details></div></article>`}).join('')||'<p class="crm-empty-inline">Nenhuma renovação cadastrada.</p>'}</div></section>`}
  function mountRenewals(profile){const notes=$('.crm-notes');notes?.insertAdjacentHTML('beforebegin',renewalsMarkup(profile.client.id));CustomerSubscriptions.loadForClient(profile.client.id).then(()=>{const current=$(`[data-crm-renewals="${profile.client.id}"]`);if(!current)return;const shell=document.createElement('div');shell.innerHTML=renewalsMarkup(profile.client.id);current.replaceWith(shell.firstElementChild);window.lucide?.createIcons()}).catch(error=>console.warn('[Customer Subscriptions] perfil local preservado',{code:error?.code||'offline'}))}
  function timeline(profile){return `<section class="crm-section crm-timeline-section"><header><div><h3>Linha do tempo</h3><p>Histórico completo do relacionamento.</p></div>${icon('history')}</header><div class="crm-timeline" data-crm-timeline>${profile.timeline.slice(0,10).map(item=>`<article><span class="crm-event-icon type-${item.type}">${icon(item.icon)}</span><div><b>${esc(item.title)}</b><p>${esc(item.description)||'Sem detalhes'}</p><small>${dateTime(item.date)}</small></div>${item.value!==null?`<strong>${money(item.value)}</strong>`:''}</article>`).join('')||'<p class="crm-empty-inline">Nenhuma atividade registrada.</p>'}</div>${profile.timeline.length>10?`<button class="btn btn-light crm-load-timeline" type="button" data-crm-load-more="${profile.client.id}">Carregar mais</button>`:''}</section>`}
  function open(clientId){const profile=CRMCliente.build(clientId);if(!profile){Utils.toast('Cliente não encontrado.',true);return}const c=profile.client,m=profile.metrics,saldo=Number(c.saldo||0);$('#modal').innerHTML=`<div class="modal-bg crm-profile-bg"><section class="modal-box modal-wide crm-profile" role="dialog" aria-modal="true" aria-labelledby="crm-profile-title"><header class="crm-profile-top"><button class="icon-btn close" type="button" aria-label="Fechar perfil">${icon('arrow-left')}</button><div><small>Perfil inteligente</small><h2 id="crm-profile-title">${esc(c.nome)}</h2></div><button class="icon-btn" type="button" data-crm-edit="${c.id}" aria-label="Editar cliente">${icon('pencil')}</button></header><div class="crm-profile-scroll"><section class="crm-hero"><span class="crm-avatar">${esc(initials(c.nome))}</span><div><h2>${esc(c.nome)}</h2><p>${esc(c.telefone)||'Sem telefone'} · ${esc(c.email)||'Sem e-mail'}</p><div class="crm-hero-badges"><span class="activity-${m.activity}">${CRMCliente.formatActivity(m.activity)}</span><span class="balance-${saldo<0?'debit':saldo>0?'credit':'zero'}">${saldo<0?`Débito ${money(Math.abs(saldo))}`:saldo>0?`Crédito ${money(saldo)}`:'Sem saldo'}</span></div></div><button class="btn btn-primary" type="button" data-crm-contact="${c.id}">${icon('phone-call')} Registrar contato</button></section>${metrics(profile)}${insights(profile)}<div class="crm-columns">${chart(profile)}${favorites(profile)}</div>${campaigns(profile)}<section class="crm-section crm-notes"><header><div><h3>Observações</h3><p>Informações importantes do cadastro.</p></div>${icon('sticky-note')}</header><p>${esc(c.observacoes)||'Nenhuma observação cadastrada.'}</p></section>${timeline(profile)}</div><footer class="crm-profile-actions"><button class="btn btn-light close" type="button">Fechar</button><button class="btn btn-primary" type="button" data-crm-contact="${c.id}">${icon('plus')} Registrar contato</button></footer></section></div>`;
    mountRenewals(profile);bindProfile(profile);window.lucide?.createIcons();
  }
  function contactForm(clientId){const profile=CRMCliente.build(clientId),client=profile?.client;if(!client)return;$('#modal').innerHTML=`<div class="modal-bg crm-contact-bg"><section class="modal-box crm-contact-modal" role="dialog" aria-modal="true" aria-labelledby="crm-contact-title"><header class="modal-head"><div><h3 id="crm-contact-title">Registrar contato</h3><small>${esc(client.nome)}</small></div><button class="icon-btn" type="button" data-crm-cancel>${icon('x')}</button></header><form id="crm-contact-form"><div class="modal-body"><fieldset class="crm-contact-types"><legend>Tipo de contato</legend>${Object.entries(CRMCliente.contactTypes).map(([value,label],index)=>`<label><input type="radio" name="tipo" value="${value}" ${index===0?'checked':''}><span>${icon({whatsapp:'message-circle',call:'phone',in_person:'store',email:'mail',charge:'hand-coins',other:'ellipsis'}[value])}<b>${label}</b></span></label>`).join('')}</fieldset><label class="field"><span>Resumo do contato</span><textarea name="resumo" maxlength="800" required placeholder="Ex.: Cliente pediu orçamento."></textarea><small><span data-crm-count>0</span>/800 caracteres</small></label></div><footer class="modal-foot"><button class="btn btn-light" type="button" data-crm-cancel>Cancelar</button><button class="btn btn-primary" type="submit">Salvar contato</button></footer></form></section></div>`;const form=$('#crm-contact-form'),textarea=form.elements.resumo;textarea.addEventListener('input',()=>{$('[data-crm-count]').textContent=textarea.value.length});document.querySelectorAll('[data-crm-cancel]').forEach(button=>button.onclick=()=>open(clientId));form.onsubmit=event=>{event.preventDefault();const data=new FormData(form);try{CRMCliente.registerContact(clientId,{tipo:data.get('tipo'),resumo:data.get('resumo')});Utils.toast('Contato registrado na linha do tempo.');open(clientId)}catch(error){Utils.toast(error.message||'Não foi possível registrar o contato.',true)}};window.lucide?.createIcons();setTimeout(()=>textarea.focus(),50)}
  function bindProfile(profile){document.querySelectorAll('.crm-profile .close').forEach(button=>button.onclick=()=>{$('#modal').innerHTML=''});document.querySelectorAll('[data-crm-contact]').forEach(button=>button.onclick=()=>contactForm(button.dataset.crmContact));$('[data-crm-edit]')?.addEventListener('click',()=>{$('#modal').innerHTML='';window.ClientesPage?.clientForm?.(profile.client.id)});$('[data-crm-load-more]')?.addEventListener('click',buttonEvent=>{const target=$('[data-crm-timeline]');target.innerHTML=profile.timeline.map(item=>`<article><span class="crm-event-icon type-${item.type}">${icon(item.icon)}</span><div><b>${esc(item.title)}</b><p>${esc(item.description)||'Sem detalhes'}</p><small>${dateTime(item.date)}</small></div>${item.value!==null?`<strong>${money(item.value)}</strong>`:''}</article>`).join('');buttonEvent.currentTarget.remove();window.lucide?.createIcons()})}
  function intercept(event){const trigger=event.target.closest?.('[data-profile-client],[data-mobile-profile],[data-mobile-history],[data-client-charges]');if(!trigger)return;const id=trigger.dataset.profileClient||trigger.dataset.mobileProfile||trigger.dataset.mobileHistory||trigger.dataset.clientCharges;if(!id)return;event.preventDefault();event.stopImmediatePropagation();open(id)}
  document.addEventListener('click',event=>{const renew=event.target.closest?.('[data-renew-subscription]'),whatsapp=event.target.closest?.('[data-renewal-whatsapp]'),status=event.target.closest?.('[data-subscription-status]');if(renew){event.preventDefault();$('#modal').innerHTML='';Checkout.prepareRenewal(renew.dataset.renewSubscription);return}if(whatsapp){event.preventDefault();const item=CustomerSubscriptions.get(whatsapp.dataset.renewalWhatsapp),client=item&&Clientes.obter(item.clientId);if(!item||!client)return;const phone=Utils.somenteNumeros(client.telefone);if(phone.length<10)return Utils.toast('Cliente sem WhatsApp válido.',true);window.open(`https://wa.me/${Utils.telefoneWhatsApp(client.telefone)}?text=${encodeURIComponent(renewalMessage(item,client))}`,'_blank','noopener');return}if(status){event.preventDefault();try{const item=CustomerSubscriptions.changeStatus(status.dataset.subscriptionId,status.dataset.subscriptionStatus);Utils.toast('Status da renovação atualizado.');open(item.clientId)}catch(error){Utils.toast(error.message||'Não foi possível atualizar.',true)}}});
  document.addEventListener('click',intercept,true);
  if(window.ClientesPage)window.ClientesPage.profile=open;
  window.CRMClienteUI={open,contactForm};
})();
