(function(){
  'use strict';
  const cache=new Map(),DAY=86400000;
  const num=value=>Number(value||0),stamp=value=>value?new Date(value).getTime()||0:0;
  const iso=value=>value?new Date(value).toISOString():null;
  const dayDiff=value=>value?Math.max(0,Math.floor((Date.now()-stamp(value))/DAY)):null;
  const contactTypes={whatsapp:'WhatsApp',call:'Ligação',in_person:'Atendimento presencial',email:'E-mail',charge:'Cobrança',other:'Outro'};
  const eventMeta={sale:['shopping-cart','Compra realizada'],credit_sale:['badge-dollar-sign','Venda fiado'],payment:['banknote-arrow-down','Pagamento recebido'],balance_adjustment:['scale','Ajuste manual de saldo'],charge:['message-circle','Cobrança enviada'],message:['send','Mensagem enviada'],online_order:['shopping-bag','Pedido online'],campaign:['megaphone','Participação em campanha'],reward:['gift','Resgate de recompensa'],note:['sticky-note','Observação criada'],contact:['phone-call','Contato registrado']};
  const byDate=(a,b)=>stamp(b.date)-stamp(a.date);
  function signature(data,clientId){
    const groups=['vendas','pagamentos','movimentacoes','messageHistory','catalogOrders','progressosCampanha','recompensas','contatosCliente'];
    const related=groups.map(key=>{const list=(data[key]||[]).filter(item=>(item.clienteId||item.clientId)===clientId),last=list.at(-1);return`${key}:${list.length}:${last?.updatedAt||last?.data||last?.createdAt||''}`});
    const client=(data.clientes||[]).find(item=>item.id===clientId),catalog=['produtos','campanhas'].map(key=>{const list=data[key]||[],last=list.at(-1);return`${key}:${list.length}:${last?.updatedAt||last?.atualizadoEm||''}`});
    return[...related,...catalog,`client:${client?.atualizadoEm||client?.criadoEm||''}`].join('|');
  }
  function event(type,raw={}){const meta=eventMeta[type]||['activity','Atividade'];return{id:raw.id||Utils.uuid(),type,icon:meta[0],title:raw.title||meta[1],description:raw.description||'',value:raw.value??null,date:raw.date||new Date().toISOString(),sourceId:raw.sourceId||raw.id||null,meta:raw.meta||{}}}
  function clientSales(data,id){return(data.vendas||[]).filter(item=>item.clienteId===id&&!item.deletedAt).sort((a,b)=>stamp(a.data)-stamp(b.data))}
  function favoriteProducts(data,sales){const products=new Map((data.produtos||[]).map(item=>[item.id,item])),totals=new Map();for(const sale of sales)for(const item of sale.itens||[]){const current=totals.get(item.produtoId)||{produtoId:item.produtoId,nome:item.nome||products.get(item.produtoId)?.nome||'Produto',categoria:products.get(item.produtoId)?.categoria||'Sem categoria',quantidade:0,valor:0,ultimaCompra:null};current.quantidade+=num(item.quantidade);current.valor+=num(item.subtotalFinal??num(item.quantidade)*num(item.precoFinalUnitario??item.precoUnitario));if(stamp(sale.data)>stamp(current.ultimaCompra))current.ultimaCompra=sale.data;totals.set(item.produtoId,current)}return[...totals.values()].sort((a,b)=>b.quantidade-a.quantidade||b.valor-a.valor)}
  function monthly(sales){const values=new Map();for(const sale of sales){const date=new Date(sale.data);if(Number.isNaN(date.getTime()))continue;const key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;values.set(key,num(values.get(key))+num(sale.valorFinal??sale.valorTotal))}const result=[];const now=new Date();for(let offset=5;offset>=0;offset--){const date=new Date(now.getFullYear(),now.getMonth()-offset,1),key=`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}`;result.push({key,label:date.toLocaleDateString('pt-BR',{month:'short'}).replace('.',''),value:num(values.get(key))})}return result}
  function timeline(data,client,sales){const id=client.id,items=[];
    for(const sale of sales)items.push(event(sale.status==='fiado'?'credit_sale':'sale',{id:`sale:${sale.id}`,sourceId:sale.id,value:num(sale.valorFinal??sale.valorTotal),description:`${(sale.itens||[]).reduce((sum,item)=>sum+num(item.quantidade),0)} item(ns) · ${sale.formaPagamento||sale.status||'pago'}`,date:sale.data,meta:{status:sale.status}}));
    for(const payment of data.pagamentos||[])if(payment.clienteId===id)items.push(event('payment',{id:`payment:${payment.id}`,sourceId:payment.id,value:num(payment.valor),description:payment.observacao||'Saldo atualizado',date:payment.data||payment.createdAt}));
    for(const movement of data.movimentacoes||[])if(movement.clienteId===id&&!['venda','pagamento','desconto','ajuste_valor_venda'].includes(movement.tipo)){if(movement.tipo==='ajuste_saldo')items.push(event('balance_adjustment',{id:`movement:${movement.id}`,sourceId:movement.id,value:num(movement.saldoNovo),description:movement.motivo||'Saldo alterado manualmente',date:movement.data}));}
    for(const message of data.messageHistory||[])if(message.clientId===id&&message.status!=='not_sent')items.push(event(message.type==='charge'?'charge':'message',{id:`message:${message.id}`,sourceId:message.id,value:message.amountAtSend,description:message.finalMessage||contactTypes[message.type]||'WhatsApp aberto',date:message.openedWhatsAppAt||message.createdAt,meta:{messageType:message.type,status:message.status}}));
    for(const order of data.catalogOrders||[])if((order.clientId||order.clienteId)===id)items.push(event('online_order',{id:`order:${order.id}`,sourceId:order.id,value:num(order.total),description:`Pedido #${order.publicOrderNumber||String(order.id).slice(0,8)} · ${order.orderStatus||'recebido'}`,date:order.createdAt,meta:{status:order.orderStatus}}));
    for(const progress of data.progressosCampanha||[])if((progress.clientId||progress.clienteId)===id){const campaign=(data.campanhas||[]).find(item=>item.id===(progress.campaignId||progress.campanhaId));items.push(event('campaign',{id:`campaign:${progress.id}`,sourceId:progress.id,description:campaign?.name||campaign?.nome||'Campanha',date:progress.createdAt||progress.lastSaleAt||progress.updatedAt,meta:{campaignId:campaign?.id}}))}
    for(const reward of data.recompensas||[])if((reward.clientId||reward.clienteId)===id&&(reward.type==='campaign_redemption'||reward.tipo==='resgate_campanha')){const campaign=(data.campanhas||[]).find(item=>item.id===(reward.campaignId||reward.campanhaId));items.push(event('reward',{id:`reward:${reward.id}`,sourceId:reward.id,description:campaign?.name||campaign?.nome||'Recompensa da campanha',date:reward.createdAt||reward.data}))}
    for(const contact of data.contatosCliente||[])if(contact.clienteId===id)items.push(event('contact',{id:`contact:${contact.id}`,sourceId:contact.id,title:contactTypes[contact.tipo]||contactTypes.other,description:contact.resumo||'Contato registrado',date:contact.data||contact.createdAt,meta:{contactType:contact.tipo}}));
    if(client.observacoes)items.push(event('note',{id:`note:${id}`,description:client.observacoes,date:client.observacoesAtualizadaEm||client.criadoEm}));
    return items.filter(item=>stamp(item.date)).sort(byDate);
  }
  function campaignSummary(data,id){const progress=(data.progressosCampanha||[]).filter(item=>(item.clientId||item.clienteId)===id),rewards=(data.recompensas||[]).filter(item=>(item.clientId||item.clienteId)===id&&(item.type==='campaign_redemption'||item.tipo==='resgate_campanha')),points=progress.reduce((sum,item)=>sum+num(item.points??item.pontos),0),available=progress.reduce((sum,item)=>sum+num(item.availableRewards??item.recompensasDisponiveis),0);return{participations:progress.length,redemptions:rewards.length,points,available,progress:progress.map(item=>{const campaign=(data.campanhas||[]).find(c=>(c.id===(item.campaignId||item.campanhaId)));return{...item,campaignName:campaign?.name||campaign?.nome||'Campanha'}})}}
  function insights(profile,allClients){const list=[],m=profile.metrics;if(m.daysWithoutPurchase!==null&&m.daysWithoutPurchase>30)list.push({tone:m.daysWithoutPurchase>60?'danger':'warning',icon:'clock-3',text:`Este cliente não compra há ${m.daysWithoutPurchase} dias.`});if(m.totalSpent>0)list.push({tone:'success',icon:'badge-dollar-sign',text:`Este cliente já gastou ${m.totalSpent.toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}.`});const ranking=[...allClients].sort((a,b)=>num(b.totalComprado)-num(a.totalComprado)).findIndex(item=>item.id===profile.client.id)+1;if(ranking>0&&ranking<=10)list.push({tone:'violet',icon:'trophy',text:`É o ${ranking}º cliente com maior valor comprado.`});if(m.favoriteCategory&&m.favoriteCategory!=='Sem dados')list.push({tone:'info',icon:'sparkles',text:`Compra principalmente a categoria ${m.favoriteCategory}.`});if(profile.campaigns.participations)list.push({tone:'info',icon:'megaphone',text:`Participou de ${profile.campaigns.participations} campanha(s).`});if(profile.sales.length)list.push({tone:'success',icon:'shopping-cart',text:`A última compra foi de ${num(profile.sales.at(-1).valorFinal??profile.sales.at(-1).valorTotal).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})}.`});return list.slice(0,5)}
  function build(clientId,options={}){const data=options.data||DB.carregar(),client=(data.clientes||[]).find(item=>item.id===clientId);if(!client)return null;const key=`${DB.getBusinessId?.()||'local'}:${clientId}`,sig=signature(data,clientId),cached=cache.get(key);if(!options.force&&cached?.signature===sig)return cached.value;const sales=clientSales(data,clientId),products=favoriteProducts(data,sales),dates=sales.map(item=>item.data).filter(Boolean),totalSpent=sales.length?sales.reduce((sum,item)=>sum+num(item.valorFinal??item.valorTotal),0):num(client.totalComprado),purchaseCount=sales.length||num(client.quantidadeVendas),lastPurchase=dates.at(-1)||client.ultimaCompra||null,firstPurchase=dates[0]||null,lastCharge=window.Mensagens?.latestCharge?.(client,data)?.date||client.lastChargeAt||null,contacts=(data.contatosCliente||[]).filter(item=>item.clienteId===clientId),messages=(data.messageHistory||[]).filter(item=>item.clientId===clientId&&item.status!=='not_sent'),lastContact=[...contacts,...messages].map(item=>item.data||item.openedWhatsAppAt||item.createdAt).sort((a,b)=>stamp(b)-stamp(a))[0]||null,daysWithoutPurchase=dayDiff(lastPurchase),activity=!lastPurchase?'no_data':daysWithoutPurchase<=30?'active':daysWithoutPurchase<=60?'risk':'inactive',categoryTotals=new Map();for(const product of products)categoryTotals.set(product.categoria,num(categoryTotals.get(product.categoria))+product.quantidade);const favoriteCategory=[...categoryTotals].sort((a,b)=>b[1]-a[1])[0]?.[0]||'Sem dados',campaigns=campaignSummary(data,clientId),value={client,sales,metrics:{totalSpent,purchaseCount,averageTicket:purchaseCount?totalSpent/purchaseCount:0,firstPurchase,lastPurchase,daysWithoutPurchase,largestPurchase:sales.reduce((max,item)=>Math.max(max,num(item.valorFinal??item.valorTotal)),0),openBalance:Math.abs(Math.min(0,num(client.saldo))),lastCharge,lastContact,topProduct:products[0]?.nome||'Sem dados',favoriteCategory,activity},products:products.slice(0,5),campaigns,monthly:monthly(sales),timeline:timeline(data,client,sales),insights:[],exportSnapshot:{clientId:client.id,generatedAt:new Date().toISOString(),metrics:null,products:products.map(item=>({...item})),campaigns:{participations:campaigns.participations,redemptions:campaigns.redemptions,points:campaigns.points}}};value.insights=insights(value,data.clientes||[]);value.exportSnapshot.metrics={...value.metrics};cache.set(key,{signature:sig,value});return value}
  function registerContact(clientId,{tipo='other',resumo=''}){const allowed=Object.keys(contactTypes);if(!allowed.includes(tipo))tipo='other';if(!String(resumo).trim())throw Error('Informe um resumo do contato.');let saved;DB.alterar(data=>{const client=data.clientes.find(item=>item.id===clientId);if(!client)throw Error('Cliente não encontrado.');const now=new Date().toISOString(),id=Utils.uuid();data.contatosCliente??=[];saved={id,operationId:id,clienteId:clientId,clienteNome:client.nome,tipo,resumo:String(resumo).trim(),data:now,createdAt:now,updatedAt:now,createdBy:window.FirebaseSession?.user?.uid||'local'};data.contatosCliente.push(saved)});invalidate(clientId);dispatchEvent(new CustomEvent('crm-contact-created',{detail:{contact:saved}}));return saved}
  function invalidate(clientId=null){if(!clientId){cache.clear();return}const suffix=`:${clientId}`;for(const key of cache.keys())if(key.endsWith(suffix))cache.delete(key)}
  window.CRMCliente={build,registerContact,invalidate,contactTypes,eventMeta,formatActivity:activity=>({active:'Cliente ativo',risk:'Cliente em atenção',inactive:'Cliente inativo',no_data:'Sem histórico de compras'}[activity]||'Sem dados')};
  ['message-history-updated','cloud-data-updated','crm-contact-created'].forEach(name=>addEventListener(name,event=>invalidate(event.detail?.record?.clientId||event.detail?.contact?.clienteId||null)));
})();
