(function(){
  'use strict';
  const mq=matchMedia('(max-width:767px)'),$=(selector,root=document)=>root.querySelector(selector),$$=(selector,root=document)=>[...root.querySelectorAll(selector)];
  const icon=name=>`<i data-lucide="${name}"></i>`,esc=value=>Utils.escapar(String(value??'')),money=Utils.dinheiro,digits=value=>String(value||'').replace(/\D/g,'');
  const TYPE_LABELS={charge:'Cobrança',campaign:'Campanha',notice:'Aviso',custom:'Mensagem livre'},PENDING_KEY='adiFestaMessagePendingReturn_v1';
  const center={type:'charge',selected:new Set(),sort:'maior',days:'todos',min:'',max:'',phone:true,initialized:false};
  let returnShown=false;
  function client(id){return Clientes.obter(id)}
  function typeLabel(type){return TYPE_LABELS[type]||TYPE_LABELS.custom}
  function close(){document.querySelector('#modal').innerHTML=''}
  function refreshClients(){if(document.querySelector('.message-center-page'))return;window.ClientesMobile?.refresh?.()}
  function setPending(value){if(value)sessionStorage.setItem(PENDING_KEY,JSON.stringify(value));else sessionStorage.removeItem(PENDING_KEY)}
  function getPending(){try{return JSON.parse(sessionStorage.getItem(PENDING_KEY)||'null')}catch{return null}}
  function templateOptions(type,selected){return Mensagens.templates(type).map(item=>`<option value="${esc(item.id)}" ${item.id===selected?'selected':''}>${esc(item.name)}${item.isDefault?' · padrão':''}</option>`).join('')}
  function variableButtons(){return['nome','primeiro_nome','saldo','ultima_cobranca','nome_negocio','pix','data_atual'].map(name=>`<button type="button" data-message-variable="${name}">{{${name}}}</button>`).join('')}
  function duplicateWarning(clientId,continuation){const c=client(clientId),root=$('#modal');root.innerHTML=`<div class="message-overlay"><section class="message-confirm-sheet" role="dialog" aria-modal="true" aria-labelledby="charge-repeat-title"><div class="sheet-handle"></div>${icon('message-circle-warning')}<h3 id="charge-repeat-title">Cliente já cobrado hoje</h3><p>${esc(c.nome)} já possui uma cobrança registrada hoje. Deseja cobrar novamente?</p><div><button class="btn btn-light" data-repeat-cancel>Cancelar</button><button class="btn btn-primary" data-repeat-confirm>Cobrar novamente</button></div></section></div>`;$('[data-repeat-cancel]',root).onclick=close;$('[data-repeat-confirm]',root).onclick=()=>continuation();window.lucide?.createIcons()}
  function openComposer(clientId,options={}){
    if(!mq.matches)return;
    const c=client(clientId),type=options.type||'charge';if(!c)return Utils.toast('Cliente não encontrado',true);
    if(type==='charge'&&Mensagens.wasChargedToday(c)&&!options.allowRepeat)return duplicateWarning(clientId,()=>openComposer(clientId,{...options,allowRepeat:true}));
    const chosen=Mensagens.templates(type).find(item=>item.id===options.templateId)||Mensagens.defaultTemplate(type),base=options.baseMessage??chosen?.content??'',last=Mensagens.latestCharge(c),root=$('#modal'),position=options.sequenceId?`Enviando para ${Number(options.index||0)+1} de ${options.total||1}`:'Cobrança individual';
    root.innerHTML=`<div class="message-overlay"><section class="individual-message-sheet" role="dialog" aria-modal="true" aria-labelledby="message-sheet-title"><div class="sheet-handle"></div><header><div><small>${esc(position)}</small><h2 id="message-sheet-title">${esc(typeLabel(type))}</h2></div><button type="button" data-message-close aria-label="Fechar">${icon('x')}</button></header><div class="message-sheet-scroll"><section class="message-client-summary"><span>${esc(String(c.nome||'?').split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase())}</span><div><h3>${esc(c.nome)}</h3><p>${esc(c.telefone)||'Sem telefone'}</p><small>Última cobrança: ${esc(Mensagens.formatLastChargeDate(last?.date))}</small></div>${type==='charge'?`<strong>${money(Math.abs(Number(c.saldo||0)))}<small>em aberto</small></strong>`:''}</section><label class="message-model-field">Modelo<select id="message-template">${templateOptions(type,chosen?.id)}</select></label><div class="message-template-actions"><button type="button" data-template-restore>${icon('rotate-ccw')} Restaurar</button><button type="button" data-template-duplicate>${icon('copy-plus')} Duplicar</button><button type="button" data-template-save>${icon('save')} Salvar novo</button><button type="button" data-template-default>${icon('star')} Usar como padrão</button></div><label class="message-text-field">Mensagem<textarea id="message-text" rows="9" maxlength="4000">${esc(base)}</textarea><span><b id="message-count">${base.length}</b>/4000 caracteres</span></label><div class="message-variables"><small>Inserir variável</small><div>${variableButtons()}</div></div><section class="message-preview"><header>${icon('eye')} Pré-visualização</header><p id="message-preview">${esc(Mensagens.resolve(base,c))}</p></section>${!Mensagens.validPhone(c)?`<p class="message-phone-error">${icon('phone-off')} Cadastre um telefone válido antes de enviar.</p>`:''}</div><footer>${options.sequenceId?`<button class="btn btn-light" type="button" data-sequence-skip>Pular</button><button class="btn btn-light" type="button" data-sequence-end>Encerrar</button>`:''}<button class="btn btn-whatsapp" type="button" id="message-send" ${Mensagens.validPhone(c)?'':'disabled'}>${icon('message-circle')} Enviar no WhatsApp</button></footer></section></div>`;
    if(options.sequenceId){const sequence=Mensagens.getSequence(options.sequenceId),completed=sequence?.completedIds?.length||0,total=sequence?.clientIds?.length||1,contacted=(DB.carregar().messageHistory||[]).filter(item=>item.sequenceId===options.sequenceId&&item.status==='opened_whatsapp').reduce((sum,item)=>sum+Number(item.amountAtSend||0),0);$('.message-sheet-scroll',root)?.insertAdjacentHTML('afterbegin',`<section class="message-sequence-progress"><div><b>${completed} de ${total} concluídos</b>${type==='charge'?`<small>${money(contacted)} em saldos contatados</small>`:''}</div><span><i style="width:${Math.round(completed/total*100)}%"></i></span></section>`)}
    const textarea=$('#message-text',root),select=$('#message-template',root),preview=()=>{$('#message-count',root).textContent=textarea.value.length;$('#message-preview',root).textContent=Mensagens.resolve(textarea.value,c)};
    textarea.addEventListener('input',()=>{preview();if(options.sequenceId)Mensagens.updateSequence(options.sequenceId,item=>item.baseMessage=textarea.value)});select.addEventListener('change',()=>{const item=Mensagens.templates(type).find(entry=>entry.id===select.value);textarea.value=item?.content||'';if(options.sequenceId)Mensagens.updateSequence(options.sequenceId,sequence=>{sequence.templateId=item?.id||null;sequence.baseMessage=textarea.value});preview()});
    $$('[data-message-variable]',root).forEach(button=>button.onclick=()=>{const token=`{{${button.dataset.messageVariable}}}`,start=textarea.selectionStart??textarea.value.length,end=textarea.selectionEnd??start;textarea.setRangeText(token,start,end,'end');textarea.focus();preview()});
    $('[data-template-restore]',root).onclick=()=>{const item=Mensagens.restoreTemplate(select.value);textarea.value=item?.content||'';preview();Utils.toast('Modelo restaurado')};
    $('[data-template-duplicate]',root).onclick=()=>{const item=Mensagens.duplicateTemplate(select.value);select.innerHTML=templateOptions(type,item?.id);textarea.value=item?.content||textarea.value;preview();Utils.toast('Modelo duplicado')};
    $('[data-template-save]',root).onclick=()=>{const name=prompt('Nome do novo modelo:');if(!name)return;const item=Mensagens.saveTemplate({name,type,content:textarea.value});select.innerHTML=templateOptions(type,item.id);Utils.toast('Modelo salvo')};
    $('[data-template-default]',root).onclick=()=>{const item=Mensagens.saveTemplate({id:select.value,name:select.options[select.selectedIndex]?.text.replace(' · padrão',''),type,content:textarea.value,isDefault:true});select.innerHTML=templateOptions(type,item.id);Utils.toast('Modelo definido como padrão')};
    $('[data-message-close]',root).onclick=close;
    $('[data-sequence-skip]',root)?.addEventListener('click',()=>skipSequence(options.sequenceId));$('[data-sequence-end]',root)?.addEventListener('click',()=>endSequence(options.sequenceId));
    $('#message-send',root).onclick=()=>{const finalMessage=Mensagens.resolve(textarea.value,c);if(!finalMessage)return Utils.toast('Digite uma mensagem',true);if(type==='charge'&&!confirm('Ao continuar, esta cobrança será registrada como enviada hoje.'))return;const record=Mensagens.registerOpened({clientId:c.id,type,source:options.source||'individual',templateId:select.value||null,finalMessage,sequenceId:options.sequenceId||null}),url=Mensagens.whatsappUrl(c,finalMessage);if(options.sequenceId)Mensagens.updateSequence(options.sequenceId,sequence=>{sequence.pendingReturn=true;sequence.currentMessageId=record.id});setPending({messageId:record.id,clientId:c.id,clientName:c.nome,type,finalMessage,url,sequenceId:options.sequenceId||null});window.open(url,'_blank');close();Utils.toast(type==='charge'?'Cobrança registrada.':'Mensagem registrada.');refreshClients()};
    preview();setTimeout(()=>textarea.focus(),80);window.lucide?.createIcons();
  }
  function sequenceClients(type){const db=DB.carregar(),active=(db.clientes||[]).filter(item=>item.ativo!==false),phoneValid=item=>Mensagens.validPhone(item);let list=type==='charge'?active.filter(item=>Number(item.saldo)<0&&!Mensagens.wasChargedToday(item)):active;list=list.filter(item=>!center.phone||phoneValid(item));if(type==='charge'){const min=Number(center.min),max=Number(center.max);if(center.min!=='')list=list.filter(item=>Math.abs(Number(item.saldo))>=min);if(center.max!=='')list=list.filter(item=>Math.abs(Number(item.saldo))<=max);if(center.days!=='todos')list=list.filter(item=>{const charge=Mensagens.latestCharge(item);if(center.days==='nunca')return!charge;const days=charge?Math.floor((Date.now()-new Date(charge.date))/86400000):Infinity;return days>=Number(center.days)})}list.sort((a,b)=>center.sort==='menor'?Math.abs(Number(a.saldo))-Math.abs(Number(b.saldo)):center.sort==='nome'?String(a.nome).localeCompare(String(b.nome),'pt-BR'):Math.abs(Number(b.saldo))-Math.abs(Number(a.saldo)));return list}
  function centerStats(){const db=DB.carregar(),active=(db.clientes||[]).filter(item=>item.ativo!==false),debtors=active.filter(item=>Number(item.saldo)<0),today=debtors.filter(Mensagens.wasChargedToday),noPhone=(center.type==='charge'?debtors:active).filter(item=>!Mensagens.validPhone(item)),available=sequenceClients(center.type);return{active,debtors,today,noPhone,available,total:available.reduce((sum,item)=>sum+(center.type==='charge'?Math.abs(Number(item.saldo)):0),0)}}
  function resetSelection(){center.selected=new Set(sequenceClients(center.type).map(item=>item.id));center.initialized=true}
  function renderCenter(){const stats=centerStats(),list=stats.available;if(!center.initialized)resetSelection();return`<section class="message-center-page"><header class="message-center-header"><button type="button" data-message-center-back aria-label="Voltar">${icon('arrow-left')}</button><div><h2>Central de mensagens</h2><p>Envio manual e seguro pelo WhatsApp.</p></div><button type="button" data-message-center-menu aria-label="Mais opções">${icon('ellipsis-vertical')}</button></header><div class="message-type-chips">${Object.entries(TYPE_LABELS).map(([key,label])=>`<button type="button" data-message-type="${key}" class="${center.type===key?'active':''}">${label}</button>`).join('')}</div><div class="message-center-kpis"><article><small>Clientes</small><strong>${list.length}</strong><span>disponíveis</span></article>${center.type==='charge'?`<article><small>Em aberto</small><strong class="kpi-money-value">${money(stats.total)}</strong><span>na sequência</span></article><article><small>Contatados hoje</small><strong>${stats.today.length}</strong><span>${stats.today.length} excluídos</span></article>`:''}<article><small>Sem telefone</small><strong>${stats.noPhone.length}</strong><span>excluídos</span></article></div><div class="message-center-controls"><button type="button" data-center-toggle-all>${center.selected.size===list.length?'Desmarcar todos':'Selecionar todos'}</button><button type="button" data-center-filters>${icon('list-filter')} Filtros</button></div><div class="message-center-list">${list.map(item=>{const last=Mensagens.latestCharge(item);return`<label class="message-center-client"><input type="checkbox" data-center-client="${item.id}" ${center.selected.has(item.id)?'checked':''}><span class="message-check"></span><span class="message-client-avatar">${esc(String(item.nome||'?').split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase())}</span><span><b>${esc(item.nome)}</b><small>${esc(item.telefone)||'Sem telefone'} · ${Mensagens.formatLastChargeDate(last?.date)}</small></span>${center.type==='charge'?`<strong>${money(Math.abs(Number(item.saldo)))}</strong>`:''}</label>`}).join('')||`<div class="message-center-empty">${icon('message-circle-check')}<h3>Nenhum cliente disponível</h3><p>Clientes cobrados hoje e sem telefone ficam fora da sequência.</p></div>`}</div><footer><span><b>${center.selected.size}</b> selecionado${center.selected.size===1?'':'s'}</span><button type="button" class="btn btn-primary" data-center-start ${center.selected.size?'':'disabled'}>${icon('play')} Iniciar envio em sequência</button></footer></section>`}
  function openCenter(){if(!mq.matches)return Router.ir('cobrancas');center.initialized=false;const app=$('#app');app.innerHTML=renderCenter();$('#title').textContent='Central de mensagens';$('#date').textContent='Cobranças, campanhas, avisos e mensagens';bindCenter();scrollTo({top:0});window.lucide?.createIcons()}
  function refreshCenter(){const app=$('#app');if(!app)return;app.innerHTML=renderCenter();bindCenter();window.lucide?.createIcons()}
  function filterSheet(){const root=$('#modal');root.innerHTML=`<div class="message-overlay"><section class="message-filter-sheet" role="dialog" aria-modal="true"><div class="sheet-handle"></div><header><h3>Filtros da Central</h3><button type="button" data-message-close>${icon('x')}</button></header><label>Ordenação<select id="center-sort"><option value="maior">Maior dívida primeiro</option><option value="menor">Menor dívida</option><option value="nome">Nome A-Z</option></select></label>${center.type==='charge'?`<label>Última cobrança<select id="center-days"><option value="todos">Todos os períodos</option><option value="nunca">Nunca cobrados</option><option value="3">Há mais de 3 dias</option><option value="7">Há mais de 7 dias</option><option value="15">Há mais de 15 dias</option><option value="30">Há mais de 30 dias</option></select></label><div class="message-filter-values"><label>Valor mínimo<input id="center-min" inputmode="decimal" value="${esc(center.min)}"></label><label>Valor máximo<input id="center-max" inputmode="decimal" value="${esc(center.max)}"></label></div>`:''}<label class="message-filter-check"><input id="center-phone" type="checkbox" ${center.phone?'checked':''}> Somente clientes com telefone</label><button class="btn btn-primary" type="button" data-center-apply>Aplicar filtros</button></section></div>`;$('#center-sort',root).value=center.sort;if($('#center-days',root))$('#center-days',root).value=center.days;$('[data-message-close]',root).onclick=close;$('[data-center-apply]',root).onclick=()=>{center.sort=$('#center-sort',root).value;center.days=$('#center-days',root)?.value||'todos';center.min=$('#center-min',root)?.value||'';center.max=$('#center-max',root)?.value||'';center.phone=$('#center-phone',root).checked;center.initialized=false;close();refreshCenter()};window.lucide?.createIcons()}
  function bindCenter(){$$('[data-message-type]').forEach(button=>button.onclick=()=>{center.type=button.dataset.messageType;center.initialized=false;refreshCenter()});$('[data-message-center-back]')?.addEventListener('click',()=>{window.ClientesMobile?.refresh?.(true);$('#title').textContent='Clientes';$('#date').textContent='Contas, compras e contato em um só lugar.'});$('[data-center-toggle-all]')?.addEventListener('click',()=>{const ids=sequenceClients(center.type).map(item=>item.id);center.selected=center.selected.size===ids.length?new Set():new Set(ids);center.initialized=true;refreshCenter()});$$('[data-center-client]').forEach(input=>input.onchange=()=>{input.checked?center.selected.add(input.dataset.centerClient):center.selected.delete(input.dataset.centerClient);center.initialized=true;refreshCenter()});$('[data-center-filters]')?.addEventListener('click',filterSheet);$('[data-center-start]')?.addEventListener('click',startSequence)}
  function startSequence(){const ids=sequenceClients(center.type).map(item=>item.id).filter(id=>center.selected.has(id));if(!ids.length)return Utils.toast('Selecione ao menos um cliente',true);const template=Mensagens.defaultTemplate(center.type),sequence=Mensagens.createSequence({type:center.type,clientIds:ids,templateId:template?.id,baseMessage:template?.content||''});openSequenceItem(sequence.id)}
  function openSequenceItem(id){const sequence=Mensagens.getSequence(id);if(!sequence)return;if(sequence.currentIndex>=sequence.clientIds.length)return finishSequence(id);const clientId=sequence.clientIds[sequence.currentIndex];openComposer(clientId,{type:sequence.type,source:'message_center',sequenceId:id,index:sequence.currentIndex,total:sequence.clientIds.length,templateId:sequence.templateId,baseMessage:sequence.baseMessage,allowRepeat:true})}
  function skipSequence(id){const sequence=Mensagens.updateSequence(id,item=>{const clientId=item.clientIds[item.currentIndex];item.skippedIds.push(clientId);item.currentIndex++;item.pendingReturn=false});close();openSequenceItem(sequence.id)}
  function endSequence(id){Mensagens.updateSequence(id,item=>{item.status='cancelled';item.pendingReturn=false});close();setPending(null);Utils.toast('Envio em sequência encerrado');openCenter()}
  function finishSequence(id){const sequence=Mensagens.completeSequence(id),root=$('#modal'),total=sequence.clientIds.length;root.innerHTML=`<div class="message-overlay"><section class="message-finish-sheet"><div class="message-success-icon">${icon('check')}</div><h2>Envio finalizado</h2><p>${sequence.completedIds.length} de ${total} mensagens preparadas.</p><div><span>Enviados <b>${sequence.completedIds.length}</b></span><span>Pulados <b>${sequence.skippedIds.length}</b></span><span>Erros <b>${sequence.errorIds.length}</b></span></div><button type="button" class="btn btn-primary" data-finish-done>Concluir</button></section></div>`;$('[data-finish-done]',root).onclick=()=>{close();openCenter()};window.lucide?.createIcons()}
  function showReturn(){const pending=getPending();if(!pending||returnShown||document.visibilityState!=='visible')return;returnShown=true;const root=$('#modal'),c=client(pending.clientId);root.innerHTML=`<div class="message-overlay"><section class="message-return-sheet" role="dialog" aria-modal="true"><div class="message-success-icon">${icon('check')}</div><h2>Mensagem preparada</h2><p>A conversa de <b>${esc(pending.clientName||c?.nome)}</b> foi aberta no WhatsApp.</p><small>O app não consegue confirmar o envio dentro do WhatsApp.</small><button class="btn btn-primary" type="button" data-return-next>${pending.sequenceId?'Continuar para o próximo':'Concluir'}</button><button class="btn btn-light" type="button" data-return-reopen>Reabrir mensagem</button><button class="btn btn-light" type="button" data-return-not-sent>Marcar como não enviado</button></section></div>`;$('[data-return-reopen]',root).onclick=()=>window.open(pending.url,'_blank');$('[data-return-next]',root).onclick=()=>{setPending(null);returnShown=false;close();if(pending.sequenceId){const sequence=Mensagens.updateSequence(pending.sequenceId,item=>{if(!item.completedIds.includes(pending.clientId))item.completedIds.push(pending.clientId);item.currentIndex++;item.pendingReturn=false});openSequenceItem(sequence.id)}else refreshClients()};$('[data-return-not-sent]',root).onclick=()=>{Mensagens.markNotSent(pending.messageId);setPending(null);returnShown=false;close();if(pending.sequenceId){const sequence=Mensagens.updateSequence(pending.sequenceId,item=>{if(!item.errorIds.includes(pending.clientId))item.errorIds.push(pending.clientId);item.currentIndex++;item.pendingReturn=false});openSequenceItem(sequence.id)}else refreshClients()};window.lucide?.createIcons()}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')setTimeout(showReturn,180)});addEventListener('focus',()=>setTimeout(showReturn,180));document.addEventListener('keydown',event=>{if(event.key==='Escape'&&$('#modal .individual-message-sheet'))close()});
  window.MobileMessages={openComposer,openCenter,refreshCenter,showReturn,startSequence,formatLastChargeDate:Mensagens.formatLastChargeDate};
})();
