window.Mensagens=(()=>{
  'use strict';
  const TYPES=['charge','campaign','notice','custom'];
  const now=()=>new Date().toISOString(),digits=value=>String(value||'').replace(/\D/g,''),dayKey=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  let readCache=null,readCacheQueued=false;
  function readData(){if(!readCache){readCache=DB.carregar();if(!readCacheQueued){readCacheQueued=true;queueMicrotask(()=>{readCache=null;readCacheQueued=false})}}return readCache}
  const DEFAULTS=[
    {id:'charge-friendly',name:'Cobrança amigável',type:'charge',isDefault:true,content:'Olá, {{nome}}! Tudo bem? 😊\n\nSó passando para lembrar que sua conta na {{nome_negocio}} está em aberto no valor de {{saldo}}.\n\nQuando puder, me avise para combinarmos o pagamento.\n\nDesde já agradeço! 🙏'},
    {id:'charge-direct',name:'Cobrança direta',type:'charge',content:'Olá, {{primeiro_nome}}. Sua conta na {{nome_negocio}} possui {{saldo}} em aberto. Podemos combinar o pagamento? Obrigado!'},
    {id:'charge-firm',name:'Cobrança firme',type:'charge',content:'Olá, {{nome}}. Consta em aberto na {{nome_negocio}} o valor de {{saldo}}. Por favor, entre em contato para regularizarmos o pagamento.'},
    {id:'campaign-default',name:'Campanha',type:'campaign',isDefault:true,content:'Olá, {{primeiro_nome}}! Temos novidades na {{nome_negocio}} 🎉\n\nEscreva aqui os detalhes da campanha.'},
    {id:'notice-default',name:'Aviso geral',type:'notice',isDefault:true,content:'Olá, {{primeiro_nome}}! Este é um aviso da {{nome_negocio}}:\n\nEscreva aqui seu aviso.'},
    {id:'custom-default',name:'Mensagem livre',type:'custom',isDefault:true,content:'Olá, {{primeiro_nome}}!'}
  ];
  function ensureTemplates(){const db=DB.carregar(),existing=new Set((db.messageTemplates||[]).map(item=>item.id)),missing=DEFAULTS.filter(item=>!existing.has(item.id));if(!missing.length)return db.messageTemplates;DB.alterar(data=>{data.messageTemplates??=[];for(const item of missing)data.messageTemplates.push({...item,system:true,active:true,createdAt:now(),updatedAt:now()})});return DB.carregar().messageTemplates}
  function templates(type){return ensureTemplates().filter(item=>item.active!==false&&(!type||item.type===type)).sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)||a.name.localeCompare(b.name,'pt-BR'))}
  function defaultTemplate(type='charge'){return templates(type).find(item=>item.isDefault)||templates(type)[0]||DEFAULTS.find(item=>item.type===type)}
  function saveTemplate(input){const stamp=now(),type=TYPES.includes(input.type)?input.type:'custom',id=input.id||Utils.uuid();DB.alterar(db=>{db.messageTemplates??=[];if(input.isDefault)db.messageTemplates.filter(item=>item.type===type).forEach(item=>item.isDefault=false);const current=db.messageTemplates.find(item=>item.id===id),next={...(current||{}),id,name:String(input.name||current?.name||'Novo modelo').trim(),type,content:String(input.content??current?.content??''),isDefault:Boolean(input.isDefault),system:Boolean(current?.system),active:true,createdAt:current?.createdAt||stamp,updatedAt:stamp};current?Object.assign(current,next):db.messageTemplates.push(next)});dispatchEvent(new CustomEvent('message-templates-updated'));return DB.carregar().messageTemplates.find(item=>item.id===id)}
  function duplicateTemplate(id){const source=templates().find(item=>item.id===id);if(!source)return null;return saveTemplate({name:`${source.name} (cópia)`,type:source.type,content:source.content})}
  function restoreTemplate(id){const original=DEFAULTS.find(item=>item.id===id),current=templates().find(item=>item.id===id);if(!original||!current)return current;return saveTemplate({...current,content:original.content,isDefault:current.isDefault})}
  function history(clientId=null,data=null){return ((data||readData()).messageHistory||[]).filter(item=>!clientId||item.clientId===clientId).sort((a,b)=>new Date(b.openedWhatsAppAt||b.createdAt)-new Date(a.openedWhatsAppAt||a.createdAt))}
  function latestCharge(client,data=null){const db=data||readData(),messages=history(client.id,db).filter(item=>item.type==='charge'&&item.status==='opened_whatsapp'),message=messages[0],legacy=(db.cobrancas||[]).filter(item=>item.clienteId===client.id).sort((a,b)=>new Date(b.data)-new Date(a.data))[0],clientTime=client.lastChargeAt;if(message)return{...message,date:message.openedWhatsAppAt||message.createdAt};if(clientTime)return{id:client.lastChargeMessageId||'',date:clientTime,status:'opened_whatsapp'};return legacy?{...legacy,date:legacy.data}:null}
  function wasChargedToday(client,data=null){return dayKey(latestCharge(client,data)?.date)===dayKey(new Date())}
  function formatLastChargeDate(value){if(!value)return'Nunca cobrado';const date=new Date(value);if(Number.isNaN(date.getTime()))return'Nunca cobrado';const today=new Date();today.setHours(0,0,0,0);const target=new Date(date);target.setHours(0,0,0,0);const days=Math.max(0,Math.round((today-target)/86400000));if(days===0)return'Hoje';if(days===1)return'Ontem';if(days<=15)return`há ${days} dias`;return date.toLocaleDateString('pt-BR')}
  function chargeBand(client,data=null){const value=latestCharge(client,data)?.date;if(!value)return'charge-never';const today=new Date();today.setHours(0,0,0,0);const date=new Date(value);date.setHours(0,0,0,0);const days=Math.max(0,Math.round((today-date)/86400000));return days===0?'charge-today':days<=7?'charge-week':days<=15?'charge-fortnight':'charge-old'}
  function variables(client){const db=DB.carregar(),charge=latestCharge(client);return{nome:client.nome||'',primeiro_nome:String(client.nome||'').trim().split(/\s+/)[0]||'',saldo:Utils.dinheiro(Math.abs(Number(client.saldo||0))),ultima_cobranca:formatLastChargeDate(charge?.date),nome_negocio:db.config?.nome||'Seu negócio',pix:db.config?.pix||'',data_atual:new Date().toLocaleDateString('pt-BR')}}
  function resolve(text,client){const values=variables(client);return String(text||'').replace(/{{\s*([a-z_]+)\s*}}/gi,(_,key)=>values[key]??'').replace(/\n{3,}/g,'\n\n').trim()}
  function canSend(){return typeof window.TeamAccess?.has!=='function'||window.TeamAccess.has('customers.view')&&window.TeamAccess.has('customers.edit')}
  function normalizedPhone(client){return window.PhoneUtils?.normalizeBrazilianPhone?.(client?.telefone)||Utils.telefoneWhatsApp(client?.telefone)}
  function validPhone(client){const phone=normalizedPhone(client);return typeof window.PhoneUtils?.isValidBrazilianPhone==='function'?window.PhoneUtils.isValidBrazilianPhone(phone):/^55[1-9]\d\d{8,9}$/.test(phone)}
  function whatsappUrl(client,message){if(!validPhone(client))throw Error('Telefone inválido. Revise o DDD e o número do cliente.');return`https://wa.me/${normalizedPhone(client)}?text=${encodeURIComponent(message)}`}
  function activeSpaceId(){const value=window.SpaceContext?.homeId?.()||'';return value&&value!=='all_spaces'?value:null}
  function canonicalBalanceErrorMessage(error){const code=String(error?.code||'').replace(/^firestore\//,'');if(['offline-unconfirmed','unavailable','deadline-exceeded','network-request-failed'].includes(code))return'Não foi possível confirmar o saldo atualizado. Conecte-se à internet para enviar a cobrança.';if(code==='permission-denied')return'Seu acesso não permite confirmar o saldo deste cliente.';if(code==='not-found')return'Cliente não encontrado na nuvem. Atualize a lista de clientes e tente novamente.';if(code==='pending-client-write')return'Este cliente possui alterações aguardando sincronização. Sincronize antes de enviar a cobrança.';if(code==='business-mismatch')return'O cliente não pertence à empresa atual. Atualize a sessão e tente novamente.';if(code==='canonical-balance-missing')return'O saldo canônico deste cliente está indisponível. Atualize o cadastro antes de cobrar.';if(code==='unauthenticated')return'Sua sessão precisa ser renovada antes de enviar a cobrança.';return'Não foi possível confirmar o saldo canônico deste cliente. Tente novamente.'}
  async function refreshCanonicalClient(clientId){
    const id=String(clientId||''),businessId=DB.getBusinessId?.()||window.BusinessContext?.get?.().businessId||'',local=window.Clientes?.obter?.(id)||DB.carregar().clientes.find(item=>String(item.id)===id);
    console.info('[CHARGE] customerId',id);
    console.info('[CHARGE] local balance',Number(local?.saldo));
    console.info('[CHARGE] requesting canonical balance');
    if(!local)throw Error('Cliente não encontrado.');
    try{
      if(!window.SyncFirebase?.isReady?.()||typeof window.SyncFirebase.readCanonicalClient!=='function')throw Object.assign(Error('Leitor canônico indisponível.'),{code:'failed-precondition',stage:'canonical-reader'});
      const result=await window.SyncFirebase.readCanonicalClient(id),client=result?.client;
      if(!client||!Number.isFinite(Number(client.saldo)))throw Object.assign(Error('Resposta canônica sem saldo válido.'),{code:'canonical-balance-missing',stage:'canonical-response'});
      console.info('[CHARGE] confirmed balance',Number(client.saldo));
      return client;
    }catch(error){const code=String(error?.code||'unknown').replace(/^firestore\//,'');console.error('[CHARGE ERROR]',{code,message:String(error?.message||'Falha desconhecida.'),stage:error?.stage||'canonical-client-read',businessId,customerId:id});const visible=Error(canonicalBalanceErrorMessage(error));visible.code=code;visible.stage=error?.stage||'canonical-client-read';throw visible}
  }
  function openWhatsApp(url,options={}){
    if(!/^https:\/\/wa\.me\//i.test(String(url||'')))return{opened:false,method:'invalid_url'};
    console.info('[WHATSAPP] opening external url');
    let popup=null;
    try{popup=window.open(url,'_blank');if(popup){try{popup.opener=null}catch(error){console.debug('[WHATSAPP] opener isolation unavailable',error)}return{opened:true,method:'popup'}}}
    catch(error){console.error('[WHATSAPP] popup open failed',error)}
    const mobile=options.mobile??matchMedia('(max-width:767px)').matches??false;
    if(mobile){try{window.location.assign(url);return{opened:true,method:'same_tab'}}catch(error){console.error('[WHATSAPP] external navigation failed',error)}}
    return{opened:false,method:'blocked'};
  }
  function requeueExistingRecord(record){
    if(typeof window.SyncFirebase?.captureExternalChange!=='function')return;
    const after=structuredClone(DB.carregar()),before=structuredClone(after),operationId=String(record.operationId||'');
    before.messageHistory=(before.messageHistory||[]).filter(item=>String(item.operationId||'')!==operationId);
    before.cobrancas=(before.cobrancas||[]).filter(item=>String(item.operationId||'')!==operationId&&item.messageId!==record.id);
    before.movimentacoes=(before.movimentacoes||[]).filter(item=>String(item.operationId||'')!==operationId);
    const client=before.clientes.find(item=>item.id===record.clientId),previous=(before.messageHistory||[]).filter(item=>item.clientId===record.clientId&&item.type==='charge'&&item.status==='opened_whatsapp').sort((a,b)=>new Date(b.openedWhatsAppAt||b.createdAt)-new Date(a.openedWhatsAppAt||a.createdAt))[0];
    if(client&&record.type==='charge'){client.lastChargeAt=previous?.openedWhatsAppAt||previous?.createdAt||null;client.lastChargeMessageId=previous?.id||null}
    window.SyncFirebase.captureExternalChange(before,after);
  }
  function registerOpened({clientId,type='charge',source='individual',templateId=null,finalMessage,sequenceId=null,operationId=null}){
    if(!canSend())throw Error('Seu acesso não permite registrar cobranças. Peça ao proprietário para revisar sua permissão de clientes.');
    const stableOperationId=String(operationId||Utils.uuid()),existing=(DB.carregar().messageHistory||[]).find(item=>String(item.operationId)===stableOperationId);
    if(existing){requeueExistingRecord(existing);return existing}
    const stamp=now(),id=Utils.uuid(),businessId=DB.getBusinessId?.()||window.BusinessContext?.get?.().businessId||'',actor=window.TeamAccess?.actor?.()||{},spaceId=activeSpaceId();let record;
    DB.alterar(db=>{db.messageHistory??=[];const duplicate=db.messageHistory.find(item=>String(item.operationId)===stableOperationId);if(duplicate){record=duplicate;return}const client=db.clientes.find(item=>item.id===clientId);if(!client)throw Error('Cliente não encontrado');if(!validPhone(client))throw Error('Telefone inválido. Revise o DDD e o número do cliente.');record={id,operationId:stableOperationId,idempotencyKey:stableOperationId,businessId,spaceId,actorUid:actor.actorUid||null,actorNameSnapshot:actor.actorNameSnapshot||null,actorRoleSnapshot:actor.actorRoleSnapshot||null,clientId:client.id,customerId:client.id,clientName:client.nome,phone:normalizedPhone(client),type:TYPES.includes(type)?type:'custom',messageType:TYPES.includes(type)?type:'custom',channel:'whatsapp',source,templateId:templateId||null,sequenceId:sequenceId||null,finalMessage:String(finalMessage||''),amountAtSend:type==='charge'?Math.abs(Number(client.saldo||0)):null,status:'opened_whatsapp',sentAt:stamp,openedWhatsAppAt:stamp,createdAt:stamp,updatedAt:stamp};db.messageHistory.push(record);if(type==='charge'){client.lastChargeAt=stamp;client.lastChargeMessageId=id;client.atualizadoEm=stamp;db.cobrancas??=[];db.cobrancas.push({id:Utils.uuid(),operationId:stableOperationId,messageId:id,businessId,spaceId,actorUid:actor.actorUid||null,clienteId:client.id,customerId:client.id,clienteNome:client.nome,valorCobrado:record.amountAtSend,mensagem:record.finalMessage,channel:'whatsapp',status:'opened_whatsapp',sentAt:stamp,data:stamp});db.movimentacoes??=[];db.movimentacoes.push({id:Utils.uuid(),operationId:stableOperationId,businessId,spaceId,actorUid:actor.actorUid||null,clienteId:client.id,clienteNome:client.nome,tipo:'cobranca_whatsapp_aberta',valor:record.amountAtSend,status:'opened_whatsapp',messageId:id,data:stamp})}});dispatchEvent(new CustomEvent('message-history-updated',{detail:{record}}));console.info('[WHATSAPP] charge event recorded');return record}
  function markNotSent(id){DB.alterar(db=>{const item=(db.messageHistory||[]).find(entry=>entry.id===id);if(!item)return;const stamp=now();item.status='not_sent';item.updatedAt=stamp;db.cobrancas=(db.cobrancas||[]).filter(entry=>entry.messageId!==id);const movement=(db.movimentacoes||[]).find(entry=>entry.messageId===id);if(movement){movement.status='not_sent';movement.updatedAt=stamp}if(item.type==='charge'){const client=db.clientes.find(entry=>entry.id===item.clientId),previous=(db.messageHistory||[]).filter(entry=>entry.clientId===item.clientId&&entry.type==='charge'&&entry.status==='opened_whatsapp'&&entry.id!==id).sort((a,b)=>new Date(b.openedWhatsAppAt||b.createdAt)-new Date(a.openedWhatsAppAt||a.createdAt))[0];if(client){client.lastChargeAt=previous?.openedWhatsAppAt||previous?.createdAt||null;client.lastChargeMessageId=previous?.id||null;client.atualizadoEm=stamp}}});dispatchEvent(new CustomEvent('message-history-updated',{detail:{id,status:'not_sent'}}))}
  function createSequence({type,clientIds,templateId,baseMessage,operationId=null}){if(!canSend())throw Error('Seu acesso não permite iniciar esta sequência.');const stableOperationId=String(operationId||Utils.uuid()),existing=(DB.carregar().messageSequences||[]).find(item=>String(item.operationId)===stableOperationId);if(existing){if(typeof window.SyncFirebase?.captureExternalChange==='function'){const after=structuredClone(DB.carregar()),before=structuredClone(after);before.messageSequences=(before.messageSequences||[]).filter(item=>String(item.operationId)!==stableOperationId);window.SyncFirebase.captureExternalChange(before,after)}return existing}const stamp=now(),actor=window.TeamAccess?.actor?.()||{},sequence={id:Utils.uuid(),operationId:stableOperationId,idempotencyKey:stableOperationId,businessId:DB.getBusinessId?.()||window.BusinessContext?.get?.().businessId||'',spaceId:activeSpaceId(),actorUid:actor.actorUid||null,actorNameSnapshot:actor.actorNameSnapshot||null,actorRoleSnapshot:actor.actorRoleSnapshot||null,type,channel:'whatsapp',clientIds:[...new Set(clientIds)],templateId:templateId||null,baseMessage:String(baseMessage||''),status:'active',currentIndex:0,completedIds:[],skippedIds:[],errorIds:[],pendingReturn:false,currentMessageId:null,createdAt:stamp,updatedAt:stamp};DB.alterar(db=>{db.messageSequences??=[];db.messageSequences.push(sequence)});return sequence}
  function updateSequence(id,mutator){let result;DB.alterar(db=>{const sequence=(db.messageSequences||[]).find(item=>item.id===id);if(!sequence)return;mutator(sequence);sequence.updatedAt=now();result={...sequence}});return result}
  function getSequence(id){return (DB.carregar().messageSequences||[]).find(item=>item.id===id)||null}
  function completeSequence(id){return updateSequence(id,sequence=>{sequence.status='completed';sequence.pendingReturn=false;sequence.finishedAt=now()})}
  addEventListener('message-history-updated',()=>{readCache=null;readCacheQueued=false});
  return{TYPES,DEFAULTS,ensureTemplates,templates,defaultTemplate,saveTemplate,duplicateTemplate,restoreTemplate,history,latestCharge,wasChargedToday,formatLastChargeDate,chargeBand,variables,resolve,canSend,normalizedPhone,validPhone,whatsappUrl,refreshCanonicalClient,openWhatsApp,registerOpened,markNotSent,createSequence,updateSequence,getSequence,completeSequence,dayKey};
})();
