window.Mensagens=(()=>{
  'use strict';
  const TYPES=['charge','campaign','notice','custom'];
  const now=()=>new Date().toISOString(),digits=value=>String(value||'').replace(/\D/g,''),dayKey=value=>{const d=new Date(value);return Number.isNaN(d.getTime())?'':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  let readCache=null,readCacheQueued=false;
  function readData(){if(!readCache){readCache=DB.carregar();if(!readCacheQueued){readCacheQueued=true;queueMicrotask(()=>{readCache=null;readCacheQueued=false})}}return readCache}
  const DEFAULTS=[
    {id:'charge-friendly',name:'Cobrança amigável',type:'charge',isDefault:true,content:'Olá, {{nome}}! Tudo bem? 😊\n\nSó passando para lembrar que sua conta na {{nome_negocio}} está em aberto no valor de {{saldo}}.\n\nQuando puder, me avise para combinarmos o pagamento.\n\nDesde já agradeço! 🙏'},
    {id:'charge-direct',name:'Cobrança direta',type:'charge',content:'Olá, {{primeiro_nome}}. Sua conta na {{nome_negocio}} possui {{saldo}} em aberto. Podemos combinar o pagamento? Obrigado!'},
    {id:'charge-firm',name:'Cobrança firme',type:'charge',content:'Olá, {{nome}}. Consta em aberto na {{nome_negocio}} o valor de {{saldo}}. Por favor, entre em contato para regularizarmos o pagamento.'},
    {id:'campaign-default',name:'Campanha',type:'campaign',isDefault:true,content:'Olá, {{primeiro_nome}}! Temos novidades na {{nome_negocio}} 🎉\n\nEscreva aqui os detalhes da campanha.'},
    {id:'notice-default',name:'Aviso geral',type:'notice',isDefault:true,content:'Olá, {{primeiro_nome}}! Este é um aviso da {{nome_negocio}}:\n\nEscreva aqui seu aviso.'},
    {id:'custom-default',name:'Mensagem livre',type:'custom',isDefault:true,content:'Olá, {{primeiro_nome}}!'}
  ];
  function ensureTemplates(){const db=DB.carregar(),existing=new Set((db.messageTemplates||[]).map(item=>item.id)),missing=DEFAULTS.filter(item=>!existing.has(item.id));if(!missing.length)return db.messageTemplates;DB.alterar(data=>{data.messageTemplates??=[];for(const item of missing)data.messageTemplates.push({...item,system:true,active:true,createdAt:now(),updatedAt:now()})});return DB.carregar().messageTemplates}
  function templates(type){return ensureTemplates().filter(item=>item.active!==false&&(!type||item.type===type)).sort((a,b)=>Number(b.isDefault)-Number(a.isDefault)||a.name.localeCompare(b.name,'pt-BR'))}
  function defaultTemplate(type='charge'){return templates(type).find(item=>item.isDefault)||templates(type)[0]||DEFAULTS.find(item=>item.type===type)}
  function saveTemplate(input){const stamp=now(),type=TYPES.includes(input.type)?input.type:'custom',id=input.id||Utils.uuid();DB.alterar(db=>{db.messageTemplates??=[];if(input.isDefault)db.messageTemplates.filter(item=>item.type===type).forEach(item=>item.isDefault=false);const current=db.messageTemplates.find(item=>item.id===id),next={...(current||{}),id,name:String(input.name||current?.name||'Novo modelo').trim(),type,content:String(input.content??current?.content??''),isDefault:Boolean(input.isDefault),system:Boolean(current?.system),active:true,createdAt:current?.createdAt||stamp,updatedAt:stamp};current?Object.assign(current,next):db.messageTemplates.push(next)});dispatchEvent(new CustomEvent('message-templates-updated'));return DB.carregar().messageTemplates.find(item=>item.id===id)}
  function duplicateTemplate(id){const source=templates().find(item=>item.id===id);if(!source)return null;return saveTemplate({name:`${source.name} (cópia)`,type:source.type,content:source.content})}
  function restoreTemplate(id){const original=DEFAULTS.find(item=>item.id===id),current=templates().find(item=>item.id===id);if(!original||!current)return current;return saveTemplate({...current,content:original.content,isDefault:current.isDefault})}
  function history(clientId=null,data=null){return ((data||readData()).messageHistory||[]).filter(item=>!clientId||item.clientId===clientId).sort((a,b)=>new Date(b.openedWhatsAppAt||b.createdAt)-new Date(a.openedWhatsAppAt||a.createdAt))}
  function latestCharge(client,data=null){const db=data||readData(),messages=history(client.id,db).filter(item=>item.type==='charge'&&item.status==='opened_whatsapp'),message=messages[0],legacy=(db.cobrancas||[]).filter(item=>item.clienteId===client.id).sort((a,b)=>new Date(b.data)-new Date(a.data))[0],clientTime=client.lastChargeAt;if(message)return{...message,date:message.openedWhatsAppAt||message.createdAt};if(clientTime)return{id:client.lastChargeMessageId||'',date:clientTime,status:'opened_whatsapp'};return legacy?{...legacy,date:legacy.data}:null}
  function wasChargedToday(client,data=null){return dayKey(latestCharge(client,data)?.date)===dayKey(new Date())}
  function formatLastChargeDate(value){if(!value)return'Nunca cobrado';const date=new Date(value);if(Number.isNaN(date.getTime()))return'Nunca cobrado';const today=new Date();today.setHours(0,0,0,0);const target=new Date(date);target.setHours(0,0,0,0);const days=Math.max(0,Math.round((today-target)/86400000));if(days===0)return'Hoje';if(days===1)return'Ontem';if(days<=15)return`há ${days} dias`;return date.toLocaleDateString('pt-BR')}
  function chargeBand(client,data=null){const value=latestCharge(client,data)?.date;if(!value)return'charge-never';const today=new Date();today.setHours(0,0,0,0);const date=new Date(value);date.setHours(0,0,0,0);const days=Math.max(0,Math.round((today-date)/86400000));return days===0?'charge-today':days<=7?'charge-week':days<=15?'charge-fortnight':'charge-old'}
  function variables(client){const db=DB.carregar(),charge=latestCharge(client);return{nome:client.nome||'',primeiro_nome:String(client.nome||'').trim().split(/\s+/)[0]||'',saldo:Utils.dinheiro(Math.abs(Number(client.saldo||0))),ultima_cobranca:formatLastChargeDate(charge?.date),nome_negocio:db.config?.nome||'Adi Festa',pix:db.config?.pix||'',data_atual:new Date().toLocaleDateString('pt-BR')}}
  function resolve(text,client){const values=variables(client);return String(text||'').replace(/{{\s*([a-z_]+)\s*}}/gi,(_,key)=>values[key]??'').replace(/\n{3,}/g,'\n\n').trim()}
  function validPhone(client){return digits(client?.telefone).length>=10}
  function whatsappUrl(client,message){return`https://wa.me/${Utils.telefoneWhatsApp(client.telefone)}?text=${encodeURIComponent(message)}`}
  function registerOpened({clientId,type='charge',source='individual',templateId=null,finalMessage,sequenceId=null}){const stamp=now(),operationId=Utils.uuid(),id=Utils.uuid();let record;DB.alterar(db=>{db.messageHistory??=[];const client=db.clientes.find(item=>item.id===clientId);if(!client)throw Error('Cliente não encontrado');record={id,operationId,clientId:client.id,clientName:client.nome,phone:client.telefone||'',type:TYPES.includes(type)?type:'custom',source,templateId:templateId||null,sequenceId:sequenceId||null,finalMessage:String(finalMessage||''),amountAtSend:type==='charge'?Math.abs(Number(client.saldo||0)):null,status:'opened_whatsapp',openedWhatsAppAt:stamp,createdAt:stamp,updatedAt:stamp};db.messageHistory.push(record);if(type==='charge'){client.lastChargeAt=stamp;client.lastChargeMessageId=id;client.atualizadoEm=stamp;db.cobrancas??=[];db.cobrancas.push({id:Utils.uuid(),operationId,messageId:id,clienteId:client.id,clienteNome:client.nome,valorCobrado:record.amountAtSend,mensagem:record.finalMessage,status:'opened_whatsapp',data:stamp});db.movimentacoes??=[];db.movimentacoes.push({id:Utils.uuid(),operationId,clienteId:client.id,clienteNome:client.nome,tipo:'cobranca_whatsapp_aberta',valor:record.amountAtSend,status:'opened_whatsapp',messageId:id,data:stamp})}});dispatchEvent(new CustomEvent('message-history-updated',{detail:{record}}));return record}
  function markNotSent(id){DB.alterar(db=>{const item=(db.messageHistory||[]).find(entry=>entry.id===id);if(!item)return;item.status='not_sent';item.updatedAt=now();db.cobrancas=(db.cobrancas||[]).filter(entry=>entry.messageId!==id);if(item.type==='charge'){const client=db.clientes.find(entry=>entry.id===item.clientId),previous=(db.messageHistory||[]).filter(entry=>entry.clientId===item.clientId&&entry.type==='charge'&&entry.status==='opened_whatsapp'&&entry.id!==id).sort((a,b)=>new Date(b.openedWhatsAppAt||b.createdAt)-new Date(a.openedWhatsAppAt||a.createdAt))[0];if(client){client.lastChargeAt=previous?.openedWhatsAppAt||previous?.createdAt||null;client.lastChargeMessageId=previous?.id||null;client.atualizadoEm=now()}}});dispatchEvent(new CustomEvent('message-history-updated',{detail:{id,status:'not_sent'}}))}
  function createSequence({type,clientIds,templateId,baseMessage}){const stamp=now(),sequence={id:Utils.uuid(),operationId:Utils.uuid(),type,clientIds:[...clientIds],templateId:templateId||null,baseMessage:String(baseMessage||''),status:'active',currentIndex:0,completedIds:[],skippedIds:[],errorIds:[],pendingReturn:false,currentMessageId:null,createdAt:stamp,updatedAt:stamp};DB.alterar(db=>{db.messageSequences??=[];db.messageSequences.push(sequence)});return sequence}
  function updateSequence(id,mutator){let result;DB.alterar(db=>{const sequence=(db.messageSequences||[]).find(item=>item.id===id);if(!sequence)return;mutator(sequence);sequence.updatedAt=now();result={...sequence}});return result}
  function getSequence(id){return (DB.carregar().messageSequences||[]).find(item=>item.id===id)||null}
  function completeSequence(id){return updateSequence(id,sequence=>{sequence.status='completed';sequence.pendingReturn=false;sequence.finishedAt=now()})}
  addEventListener('message-history-updated',()=>{readCache=null;readCacheQueued=false});
  return{TYPES,DEFAULTS,ensureTemplates,templates,defaultTemplate,saveTemplate,duplicateTemplate,restoreTemplate,history,latestCharge,wasChargedToday,formatLastChargeDate,chargeBand,variables,resolve,validPhone,whatsappUrl,registerOpened,markNotSent,createSequence,updateSequence,getSequence,completeSequence,dayKey};
})();
