(function(){
  'use strict';
  const VERSION=2,MODES={
    physical_store:{label:'Loja física',description:'Vendas em loja, balcão, quiosque ou ponto comercial.',icon:'store'},
    external_sales:{label:'Venda externa',description:'Visitas a clientes, empresas ou pontos de venda.',icon:'map-pinned'},
    delivery_orders:{label:'Entrega e pedidos',description:'Pedidos para entrega ou retirada.',icon:'truck'}
  },CREDIT_MODES={
    enabled:{label:'Sim, trabalho com fiado',description:'Meus clientes compram e pagam depois.'},
    disabled:{label:'Não, recebo no momento da venda',description:'Normalmente recebo no momento da compra.'},
    occasional:{label:'Às vezes, apenas registro pendências',description:'Quero anotar valores ocasionais sem deixar o fiado como foco.'}
  };
  const BASE_MODULES={inventory:true,onlineCatalog:false,onlineOrders:false,delivery:false,pickup:false,physicalStore:false,scheduledVisits:false,campaigns:false,loyalty:false,crm:true,inPersonSales:true,creditSales:false};
  const now=()=>new Date().toISOString(),icon=name=>`<i data-lucide="${name}"></i>`,esc=value=>window.Utils?.escapar?.(String(value??''))??String(value??'');
  function legacy(){return(DB.getBusinessId?.()||window.FirebaseSession?.businessId||'')==='adi-festa'}
  function inferMode(raw){if(MODES[raw.operationMode])return raw.operationMode;if(raw.profile==='physical_store')return'physical_store';if(raw.profile==='delivery_store')return'delivery_orders';if(['credit_sales','itinerant'].includes(raw.profile))return'external_sales';if(raw.modules?.delivery||raw.modules?.onlineOrders)return'delivery_orders';if(raw.modules?.physicalStore)return'physical_store';return legacy()?'external_sales':'physical_store'}
  function inferCredit(raw){if(CREDIT_MODES[raw.creditMode])return raw.creditMode;if(raw.modules?.creditSales===true||raw.profile==='credit_sales'||legacy())return'enabled';return'disabled'}
  function derivedModules(mode,credit,old={}){return{...BASE_MODULES,...old,physicalStore:mode==='physical_store',scheduledVisits:mode==='external_sales',delivery:mode==='delivery_orders',onlineOrders:mode==='delivery_orders'||old.onlineOrders===true,onlineCatalog:mode==='delivery_orders'||old.onlineCatalog===true,pickup:mode==='delivery_orders'||old.pickup===true,creditSales:credit!=='disabled'}}
  function normalize(raw={}){const operationMode=inferMode(raw),creditMode=inferCredit(raw),hadLegacyConfig=Boolean(raw.migrationVersion||raw.schemaVersion||raw.profile||raw.operationMode||raw.modules),data=DB.carregar(),hasExistingData=Boolean(data.clientes?.length||data.produtos?.length||data.vendas?.length),completed=raw.operationOnboardingCompleted===true||legacy()||hasExistingData||hadLegacyConfig&&raw.operationOnboardingCompleted!==false;return{operationMode,creditMode,operationOnboardingCompleted:completed,modules:derivedModules(operationMode,creditMode,raw.modules),smartCardMode:raw.smartCardMode==='custom'?'custom':'automatic',cardMetrics:Array.isArray(raw.cardMetrics)?raw.cardMetrics:[],createdAt:raw.createdAt||now(),updatedAt:raw.updatedAt||now(),schemaVersion:VERSION,migrationVersion:VERSION}}
  function get(){return normalize(DB.carregar().config.operation)}
  function emit(operation,reason){dispatchEvent(new CustomEvent('operation-settings-changed',{detail:{operation,reason}}))}
  function ensure(){const current=DB.carregar().config.operation;if(current?.migrationVersion>=VERSION)return normalize(current);let saved;DB.alterar(data=>{saved=normalize(data.config.operation||{});data.config.operation=saved});emit(saved,'migration');return saved}
  function save(patch={}){let saved;DB.alterar(data=>{saved=normalize({...normalize(data.config.operation||{}),...patch,updatedAt:now()});data.config.operation=saved});emit(saved,'user');return saved}
  function applyRemote(raw){let saved;DB.alterar(data=>{saved=normalize(raw);data.config.operation=saved});emit(saved,'cloud');return saved}
  function enabled(name){const op=get();if(name==='creditSales')return op.creditMode==='enabled';return op.modules[name]===true}
  function allowsCredit(){return get().creditMode!=='disabled'}
  function can(permission){const session=window.FirebaseSession||{},role=session.profile?.role||'owner',permissions=session.profile?.permissions||{};if(role==='owner'||role==='platform_admin')return true;if(role==='admin')return permission!=='exportCRM'||permissions.exportCRM===true;return permissions[permission]===true}
  function cardMetrics(){const op=get();if(op.smartCardMode==='custom'&&op.cardMetrics.length)return op.cardMetrics;if(op.creditMode==='enabled')return['openBalance','lastCharge','lastPurchase','totalSpent','lastContact'];return['totalSpent','lastPurchase','lastContact','averageTicket','purchaseCount']}
  function renderSettings(){const op=get(),mode=MODES[op.operationMode],credit=CREDIT_MODES[op.creditMode];return`<section class="operation-settings-card operation-summary-card"><header><span>${icon(mode.icon)}</span><div><h3>Modelo de operação</h3><p>${esc(mode.label)}</p></div></header><div class="operation-summary"><span><small>Como sua empresa trabalha</small><b>${esc(mode.description)}</b></span><span><small>Fiado</small><b>${esc(credit.label.replace(/^Sim, |^Não, /,''))}</b></span></div><button type="button" class="btn btn-light" data-edit-operation>${icon('settings-2')} Alterar modelo</button></section>`}
  function optionCards(items,selected,attribute){return Object.entries(items).map(([id,item])=>`<button type="button" class="operation-choice ${selected===id?'active':''}" ${attribute}="${id}">${icon(item.icon||'circle-check')}<span><b>${esc(item.label)}</b><small>${esc(item.description)}</small></span>${icon(selected===id?'circle-check-big':'circle')}</button>`).join('')}
  function editor({onboarding=false}={}){const current=get(),root=document.createElement('div');root.className=`operation-flow ${onboarding?'onboarding':''}`;root.innerHTML=`<section class="operation-flow-card" role="dialog" aria-modal="true"><header>${!onboarding?'<button type="button" data-operation-close aria-label="Fechar">'+icon('x')+'</button>':''}<span class="operation-step-label">Etapa <b>1</b> de 2</span><h1>Como sua empresa trabalha?</h1><p>Isso nos ajuda a mostrar o que é mais importante para você.</p></header><div class="operation-flow-body" data-operation-step="1">${optionCards(MODES,current.operationMode,'data-operation-mode')}</div><div class="operation-flow-body" data-operation-step="2" hidden><h2>Você costuma deixar clientes pagarem depois?</h2><p>Isso não é obrigatório e pode ser alterado quando quiser.</p>${optionCards(CREDIT_MODES,current.creditMode,'data-credit-mode')}</div><footer><small>Você poderá alterar isso depois nas Configurações.</small><button type="button" class="btn btn-primary" data-operation-next>Continuar</button></footer></section>`;document.body.append(root);
    let step=1,mode=current.operationMode,credit=current.creditMode;const choose=(selector,key)=>root.querySelectorAll(selector).forEach(button=>button.onclick=()=>{if(key==='mode')mode=button.dataset.operationMode;else credit=button.dataset.creditMode;root.querySelectorAll(selector).forEach(item=>item.classList.toggle('active',item===button))});choose('[data-operation-mode]','mode');choose('[data-credit-mode]','credit');root.querySelector('[data-operation-close]')?.addEventListener('click',()=>root.remove());root.querySelector('[data-operation-next]').onclick=()=>{if(step===1){step=2;root.querySelector('[data-operation-step="1"]').hidden=true;root.querySelector('[data-operation-step="2"]').hidden=false;root.querySelector('.operation-step-label b').textContent='2';root.querySelector('header h1').textContent='Pagamento posterior';root.querySelector('header p').textContent='Escolha o comportamento que combina com a sua empresa.';root.querySelector('[data-operation-next]').textContent='Finalizar';return}save({operationMode:mode,creditMode:credit,operationOnboardingCompleted:true});root.remove();Utils.toast(onboarding?'Configuração concluída.':'Modelo de operação atualizado.');dispatchEvent(new Event('hashchange'))};window.lucide?.createIcons();
  }
  function bindSettings(root=document){root.querySelector('[data-edit-operation]')?.addEventListener('click',()=>{if(!can('manageOperationSettings'))return Utils.toast('Seu perfil não pode alterar a operação.',true);editor()})}
  function maybeShowOnboarding(){const op=ensure();if(op.operationOnboardingCompleted||legacy()||document.querySelector('.operation-flow'))return;editor({onboarding:true})}
  window.OperationMode={VERSION,MODES,CREDIT_MODES,get,ensure,save,applyRemote,enabled,allowsCredit,can,cardMetrics,normalize,renderSettings,bindSettings,maybeShowOnboarding,openEditor:editor};
  addEventListener('operation-settings-loaded',maybeShowOnboarding);
})();
