(function(){
  'use strict';
  const VERSION=1;
  const MODULES={creditSales:false,inventory:true,onlineCatalog:false,onlineOrders:false,delivery:false,pickup:false,physicalStore:false,scheduledVisits:false,campaigns:false,loyalty:false,crm:true,inPersonSales:true};
  const PROFILES={
    physical_store:{label:'Loja física',modules:{inventory:true,physicalStore:true,inPersonSales:true,crm:true,campaigns:true,pickup:true}},
    delivery_store:{label:'Loja com entrega',modules:{inventory:true,onlineCatalog:true,onlineOrders:true,delivery:true,crm:true}},
    credit_sales:{label:'Venda fiado',modules:{creditSales:true,inPersonSales:true,crm:true}},
    itinerant:{label:'Vendedor itinerante',modules:{onlineCatalog:true,onlineOrders:true,scheduledVisits:true,delivery:true,crm:true}},
    custom:{label:'Personalizado',modules:{}}
  };
  const LABELS={creditSales:'Trabalha com vendas fiado',inventory:'Controla estoque',onlineCatalog:'Possui catálogo online',onlineOrders:'Aceita pedidos online',delivery:'Faz entregas',pickup:'Permite retirada',physicalStore:'Possui loja física',scheduledVisits:'Faz visitas ou atendimento itinerante',campaigns:'Utiliza campanhas',loyalty:'Utiliza fidelidade e pontos',crm:'Utiliza CRM e relacionamento',inPersonSales:'Realiza vendas presenciais'};
  const now=()=>new Date().toISOString();
  function legacy(){return (DB.getBusinessId?.()||'')==='adi-festa'}
  function normalize(raw={}){const base=legacy()?{...MODULES,creditSales:true,campaigns:true,loyalty:true,onlineCatalog:true,onlineOrders:true}:{...MODULES};return{profile:raw.profile||'custom',modules:{...base,...(raw.modules||{})},smartCardMode:raw.smartCardMode==='custom'?'custom':'automatic',cardMetrics:Array.isArray(raw.cardMetrics)?raw.cardMetrics:[],createdAt:raw.createdAt||now(),updatedAt:raw.updatedAt||now(),schemaVersion:VERSION,migrationVersion:VERSION}}
  function get(){return normalize(DB.carregar().config.operation)}
  function ensure(){const current=DB.carregar().config.operation;if(current?.migrationVersion>=VERSION)return normalize(current);let saved;DB.alterar(data=>{saved=normalize(data.config.operation);data.config.operation=saved});dispatchEvent(new CustomEvent('operation-settings-changed',{detail:{operation:saved,reason:'migration'}}));return saved}
  function save(patch={}){let saved;DB.alterar(data=>{const current=normalize(data.config.operation),profile=patch.profile||current.profile,profileModules=patch.profile&&patch.profile!=='custom'?PROFILES[profile]?.modules||{}:{};saved=normalize({...current,...patch,profile,modules:{...current.modules,...profileModules,...(patch.modules||{})},updatedAt:now()});data.config.operation=saved});dispatchEvent(new CustomEvent('operation-settings-changed',{detail:{operation:saved,reason:'user'}}));return saved}
  function applyRemote(raw){let saved;DB.alterar(data=>{saved=normalize(raw);data.config.operation=saved});dispatchEvent(new CustomEvent('operation-settings-changed',{detail:{operation:saved,reason:'cloud'}}));return saved}
  function enabled(name){return get().modules[name]===true}
  function can(permission){const session=window.FirebaseSession||{},role=session.profile?.role||'owner',permissions=session.profile?.permissions||{};if(role==='owner'||role==='platform_admin')return true;if(role==='admin')return permission!=='exportCRM'||permissions.exportCRM===true;return permissions[permission]===true}
  function cardMetrics(){const op=get(),m=op.modules;if(op.smartCardMode==='custom'&&op.cardMetrics.length)return op.cardMetrics;if(m.creditSales)return['openBalance','lastCharge','lastPurchase','totalSpent','lastContact'];return['totalSpent','lastPurchase','lastContact','averageTicket','purchaseCount']}
  const icon=n=>`<i data-lucide="${n}"></i>`;
  function renderSettings(){const op=get();return`<section class="operation-settings-card"><header><span>${icon('workflow')}</span><div><h3>Operação da empresa</h3><p>Como sua empresa trabalha?</p></div></header><div class="operation-profiles">${Object.entries(PROFILES).map(([id,p])=>`<button type="button" class="${op.profile===id?'active':''}" data-operation-profile="${id}">${p.label}</button>`).join('')}</div><div class="operation-switches">${Object.entries(LABELS).map(([id,label])=>`<label><span>${label}</span><input type="checkbox" data-operation-module="${id}" ${op.modules[id]?'checked':''}></label>`).join('')}</div><label class="operation-card-mode"><span>Cards inteligentes</span><select data-operation-card-mode><option value="automatic" ${op.smartCardMode==='automatic'?'selected':''}>Automático</option><option value="custom" ${op.smartCardMode==='custom'?'selected':''}>Personalizado</option></select></label><button type="button" class="btn btn-primary" data-save-operation>${icon('check')} Salvar operação</button></section>`}
  function bindSettings(root=document){root.querySelectorAll('[data-operation-profile]').forEach(button=>button.onclick=()=>{const profile=button.dataset.operationProfile,modules={...MODULES,...(PROFILES[profile]?.modules||{})};root.querySelectorAll('[data-operation-module]').forEach(input=>input.checked=modules[input.dataset.operationModule]);root.querySelectorAll('[data-operation-profile]').forEach(item=>item.classList.toggle('active',item===button))});root.querySelector('[data-save-operation]')?.addEventListener('click',event=>{if(!can('manageOperationSettings'))return Utils.toast('Seu perfil não pode alterar a operação.',true);const selected=root.querySelector('[data-operation-profile].active')?.dataset.operationProfile||'custom',modules={};root.querySelectorAll('[data-operation-module]').forEach(input=>modules[input.dataset.operationModule]=input.checked);save({profile:selected,modules,smartCardMode:root.querySelector('[data-operation-card-mode]').value});Utils.toast('Modo de operação atualizado.');event.currentTarget.innerHTML=`${icon('check-circle')} Salvo`;setTimeout(()=>dispatchEvent(new Event('hashchange')),350)})}
  window.OperationMode={VERSION,MODULES,PROFILES,LABELS,get,ensure,save,applyRemote,enabled,can,cardMetrics,normalize,renderSettings,bindSettings};
  addEventListener('firebase-auth-ready',()=>ensure(),{once:true});
})();
