(function(){
  'use strict';
  // Product image upload postponed until catalog demand is validated.
  const $=(selector,root=document)=>root.querySelector(selector);
  const esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
  const source=product=>product?.imageThumbUrl||product?.productImage||product?.imageUrl||product?.productMainImage||product?.imagem||product?.image||'';
  function versionedUrl(url,updatedAt){if(!url||!updatedAt)return url||'';try{const parsed=new URL(url,location.href);parsed.searchParams.set('v',String(new Date(updatedAt).getTime()||updatedAt));return parsed.href}catch{return url}}
  function markup(product,{className='product-photo',preferMain=false,alt}={}){const url=versionedUrl(preferMain?(product?.imageUrl||product?.imagem):source(product),product?.imageUpdatedAt),label=alt??product?.nome??product?.productName??'';return `<span class="${esc(className)} product-photo-shell">${url?`<img src="${esc(url)}" alt="${esc(label)}" loading="lazy" decoding="async" onerror="this.hidden=true;this.nextElementSibling.hidden=false">`:''}<span class="product-photo-fallback" ${url?'hidden':''}>${esc(initials(label))}</span></span>`}
  function openForm(id,defaults={}){
    const product=id?Produtos.obter(id):{},root=$('#modal'),initialBarcode=defaults.barcode??product?.barcode??'';
    root.innerHTML=`<div class="modal-bg"><section class="modal-box product-form-modal"><header class="modal-head"><h3>${id?'Editar produto':'Novo produto'}</h3><button class="icon-btn close" type="button" aria-label="Fechar"><i data-lucide="x"></i></button></header><form><div class="modal-body"><div class="form-grid"><div class="field full"><label>Nome *</label><input name="nome" required value="${esc(product?.nome||'')}"></div><div class="field"><label>Código interno</label><input name="codigo" value="${esc(product?.codigo||'')}"></div><div class="field"><label>Categoria</label><input name="categoria" value="${esc(product?.categoria||'Doces')}"></div><div class="field full"><label>Código de barras</label><div class="barcode-field-row"><input name="barcode" inputmode="text" autocomplete="off" value="${esc(initialBarcode)}" placeholder="EAN, UPC, Code 128…"><button type="button" data-scan-form-barcode aria-label="Ler código pela câmera"><i data-lucide="scan-barcode"></i></button></div><input type="hidden" name="barcodeType" value="${esc(defaults.barcodeType??product?.barcodeType??'')}"><small class="barcode-field-status">Não informado</small></div><div class="field"><label>Preço de venda *</label><input name="preco" required inputmode="decimal" value="${esc(product?.preco??'')}"></div><div class="field"><label>Custo unitário</label><input name="custo" inputmode="decimal" value="${esc(product?.custo??'')}"></div><div class="field"><label>Estoque atual</label><input name="estoqueAtual" inputmode="decimal" value="${esc(product?.estoqueAtual??product?.estoque??0)}"></div><div class="field"><label>Estoque mínimo</label><input name="estoqueMinimo" inputmode="decimal" value="${esc(product?.estoqueMinimo??0)}"></div><label class="check full"><input type="checkbox" name="semControleEstoque" ${product?.semControleEstoque?'checked':''}><span>Não controlar estoque deste produto</span></label><div class="field full"><label>Observação</label><textarea name="observacao">${esc(product?.observacao||product?.observacoes||'')}</textarea></div></div></div><footer class="modal-foot"><button type="button" class="btn btn-light cancel">Cancelar</button><button class="btn btn-primary">Salvar produto</button></footer></form></section></div>`;
    root.querySelectorAll('.close,.cancel').forEach(button=>button.onclick=()=>Modais.fechar());
    const barcodeInput=$('[name="barcode"]',root),barcodeType=$('[name="barcodeType"]',root),barcodeStatus=$('.barcode-field-status',root);
    const validateBarcode=()=>{const code=window.normalizeBarcode?.(barcodeInput.value)||barcodeInput.value.trim();barcodeInput.value=code;barcodeStatus.className='barcode-field-status';if(!code){barcodeType.value='';barcodeStatus.textContent='Não informado';return true}if(code!==String(initialBarcode))barcodeType.value=window.BarcodeIndex?.inferType?.(code)||'manual';const duplicate=window.BarcodeIndex?.conflict?.(code,id);if(duplicate){barcodeStatus.textContent=`Já cadastrado em ${duplicate.nome}`;barcodeStatus.classList.add('duplicate');return false}barcodeStatus.textContent='Código disponível';barcodeStatus.classList.add('available');return true};
    barcodeInput.addEventListener('input',validateBarcode);barcodeInput.addEventListener('blur',validateBarcode);
    $('[data-scan-form-barcode]',root).onclick=()=>window.BarcodeUI?.open?.({title:'Código do produto',onDetected:result=>{barcodeInput.value=result.value;barcodeType.value=result.format;validateBarcode();return{message:'Código preenchido no produto'}}});
    $('form',root).onsubmit=event=>{event.preventDefault();if(!validateBarcode())return Utils.toast('Este código já pertence a outro produto.',true);const form=event.currentTarget,data=Object.fromEntries(new FormData(form));try{const saved=Produtos.salvar({id:id||undefined,...data,semControleEstoque:new FormData(form).has('semControleEstoque'),favorito:product?.favorito,ativo:true});Modais.fechar();Utils.toast('Produto salvo');defaults.onSaved?.(saved);if(matchMedia('(max-width:767px)').matches&&window.Router?.atual?.()==='produtos')window.ProdutosMobile?.refresh?.(true);else dispatchEvent(new CustomEvent('cloud-data-updated',{detail:{source:'product-form',collection:'products'}}))}catch(error){Utils.toast(error.message||'Não foi possível salvar o produto.',true)}};
    validateBarcode();
    window.lucide?.createIcons();setTimeout(()=>$('input[name="nome"]',root)?.focus(),50);
  }
  function enhance(root=document){if(!window.Produtos)return;root.querySelectorAll('.mobile-product-card,.pick-product,.entity-card.product-card,.editable-cart,.product-detail-modal').forEach(element=>{if(element.dataset.photoEnhanced)return;const id=element.dataset.productCard||element.dataset.add||element.querySelector('[data-edit-product]')?.dataset.editProduct||element.querySelector('[data-item-qty]')?.dataset.itemQty||element.querySelector('[data-detail-edit]')?.dataset.detailEdit,product=id&&Produtos.obter(id);if(!product)return;const target=element.matches('.mobile-product-card')?element.querySelector('.mobile-product-avatar'):element.matches('.pick-product,.editable-cart')?element:element.querySelector('.entity-head,.modal-body');if(!target)return;const holder=document.createElement('span');holder.innerHTML=markup(product,{className:element.matches('.mobile-product-card')?'enhanced-mobile-product-photo':element.matches('.pick-product')?'sale-product-photo':element.matches('.editable-cart')?'sale-cart-photo':'desktop-product-photo'});target.prepend(holder.firstElementChild);element.dataset.photoEnhanced='true'})}
  window.ProductImages={markup,source,openForm,versionedUrl,enhance};
  let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;enhance(document)})}).observe(document.documentElement,{childList:true,subtree:true});addEventListener('DOMContentLoaded',()=>enhance());
})();
