(function(){
  'use strict';
  const ACCEPTED=new Set(['image/jpeg','image/png','image/webp']),MAX_BYTES=12*1024*1024;
  const $=(selector,root=document)=>root.querySelector(selector),esc=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
  const initials=name=>String(name||'?').trim().split(/\s+/).slice(0,2).map(part=>part[0]).join('').toUpperCase();
  const source=product=>product?.imageThumbUrl||product?.productImage||product?.imageUrl||product?.productMainImage||product?.imagem||product?.image||'';
  function versionedUrl(url,updatedAt){if(!url||!updatedAt)return url||'';try{const parsed=new URL(url,location.href);parsed.searchParams.set('v',String(new Date(updatedAt).getTime()||updatedAt));return parsed.href}catch{return url}}
  function markup(product,{className='product-photo',preferMain=false,alt}={}){const url=versionedUrl(preferMain?(product?.imageUrl||product?.imagem):(source(product)),product?.imageUpdatedAt),label=alt??product?.nome??product?.productName??'';return `<span class="${esc(className)} product-photo-shell">${url?`<img src="${esc(url)}" alt="${esc(label)}" loading="lazy" decoding="async" onerror="this.hidden=true;this.nextElementSibling.hidden=false">`:''}<span class="product-photo-fallback" ${url?'hidden':''}>${esc(initials(label))}</span></span>`}
  function validate(file){if(!file||!ACCEPTED.has(String(file.type).toLowerCase()))throw Error('Selecione uma imagem válida. Use JPG, PNG ou WebP.');if(file.size>MAX_BYTES)throw Error('A imagem é muito grande. Escolha uma foto de até 12 MB.');return true}
  async function decode(file){validate(file);try{if('createImageBitmap'in window)return await createImageBitmap(file,{imageOrientation:'from-image'})}catch{}return await new Promise((resolve,reject)=>{const url=URL.createObjectURL(file),image=new Image;image.onload=()=>{URL.revokeObjectURL(url);resolve(image)};image.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Não foi possível ler esta imagem.'))};image.src=url})}
  const toBlob=(canvas,type,quality)=>new Promise(resolve=>canvas.toBlob(resolve,type,quality));
  async function processProductImage(file,settings={}){const image=settings.image||await decode(file),rotation=((Number(settings.rotation||0)%360)+360)%360,quarter=rotation===90||rotation===270,iw=image.width||image.naturalWidth,ih=image.height||image.naturalHeight,rw=quarter?ih:iw,rh=quarter?iw:ih,cropSide=Math.min(rw,rh),zoom=Math.max(1,Number(settings.zoom||1)),output=Math.max(1,Math.min(800,Math.round(cropSide))),offsetX=Number(settings.offsetX||0),offsetY=Number(settings.offsetY||0);
    const render=size=>{const canvas=document.createElement('canvas');canvas.width=canvas.height=size;const ctx=canvas.getContext('2d',{alpha:false});ctx.fillStyle='#fff';ctx.fillRect(0,0,size,size);const scale=(size/cropSide)*zoom;ctx.save();ctx.translate(size/2+offsetX*size,size/2+offsetY*size);ctx.rotate(rotation*Math.PI/180);ctx.scale(scale,scale);ctx.drawImage(image,-iw/2,-ih/2);ctx.restore();return canvas};
    const mainCanvas=render(output),thumbCanvas=render(Math.min(320,output));let type='image/webp',extension='webp',mainBlob=await toBlob(mainCanvas,type,.82),thumbBlob=await toBlob(thumbCanvas,type,.76);if(!mainBlob||mainBlob.type!=='image/webp'){type='image/jpeg';extension='jpg';mainBlob=await toBlob(mainCanvas,type,.84);thumbBlob=await toBlob(thumbCanvas,type,.78)}if(!mainBlob||!thumbBlob)throw Error('Não foi possível otimizar esta imagem.');return{mainBlob,thumbBlob,width:output,height:output,contentType:type,extension}}
  function imageSection(state,product){const preview=state.remove?'':state.previewUrl||source(product);return `<section class="product-image-field"><div class="product-image-heading"><div><b>Foto do produto</b><small>A imagem será otimizada automaticamente.</small></div><span>1:1</span></div><div class="product-image-preview ${preview?'has-image':''}" id="product-image-preview">${preview?`<img src="${esc(preview)}" alt="Prévia da foto" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><div class="product-image-empty" hidden><i data-lucide="image-off"></i><b>Imagem indisponível</b></div>`:`<div class="product-image-empty"><i data-lucide="image-plus"></i><b>Adicionar foto</b><small>Use uma imagem quadrada</small></div>`}</div><div class="product-image-actions">${preview?`<button type="button" data-photo-gallery><i data-lucide="refresh-cw"></i> Trocar</button><button type="button" data-photo-adjust><i data-lucide="crop"></i> Ajustar</button><button type="button" class="danger" data-photo-remove><i data-lucide="trash-2"></i> Remover</button>`:`<button type="button" data-photo-camera><i data-lucide="camera"></i> Tirar foto</button><button type="button" data-photo-gallery><i data-lucide="images"></i> Galeria</button>`}</div><p>Formatos aceitos: JPG, PNG e WebP. Máximo de 12 MB.</p><input class="visually-hidden" id="product-camera-input" type="file" accept="image/*" capture="environment"><input class="visually-hidden" id="product-gallery-input" type="file" accept="image/jpeg,image/png,image/webp"></section>`}
  function cropper(state,onConfirm){let drag=null,pointers=new Map(),pinchDistance=0,pinchZoom=1;const layer=document.createElement('div');layer.className='product-crop-layer';layer.innerHTML=`<section class="product-crop-sheet" role="dialog" aria-modal="true" aria-label="Ajustar foto"><header><div><h3>Ajustar foto</h3><p>Arraste, aproxime ou gire a imagem.</p></div><button type="button" data-crop-close aria-label="Fechar"><i data-lucide="x"></i></button></header><div class="product-crop-stage" id="product-crop-stage"><img src="${esc(state.originalUrl)}" alt="Foto para ajustar" draggable="false"></div><label class="product-zoom"><span>Zoom</span><input type="range" min="1" max="3" value="${state.crop.zoom}" step=".01"></label><div class="product-crop-tools"><button type="button" data-crop-rotate><i data-lucide="rotate-cw"></i> Girar</button><button type="button" data-crop-reset><i data-lucide="refresh-ccw"></i> Restaurar</button></div><footer><button type="button" class="btn btn-light" data-crop-close>Cancelar</button><button type="button" class="btn btn-primary" data-crop-confirm>Usar foto</button></footer></section>`;document.body.append(layer);const stage=$('#product-crop-stage',layer),img=$('img',stage),range=$('input[type="range"]',layer);
    const update=()=>{img.style.transform=`translate(calc(-50% + ${state.crop.offsetX*100}%),calc(-50% + ${state.crop.offsetY*100}%)) rotate(${state.crop.rotation}deg) scale(${state.crop.zoom})`};
    stage.onpointerdown=event=>{pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});stage.setPointerCapture?.(event.pointerId);if(pointers.size===1)drag={x:event.clientX,y:event.clientY,ox:state.crop.offsetX,oy:state.crop.offsetY};if(pointers.size===2){const values=[...pointers.values()];pinchDistance=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y);pinchZoom=state.crop.zoom}};
    stage.onpointermove=event=>{if(!pointers.has(event.pointerId))return;pointers.set(event.pointerId,{x:event.clientX,y:event.clientY});if(pointers.size===2){const values=[...pointers.values()],distance=Math.hypot(values[0].x-values[1].x,values[0].y-values[1].y);state.crop.zoom=Math.min(3,Math.max(1,pinchZoom*(distance/Math.max(1,pinchDistance))));range.value=state.crop.zoom}else if(drag){state.crop.offsetX=Math.max(-.5,Math.min(.5,drag.ox+(event.clientX-drag.x)/stage.clientWidth));state.crop.offsetY=Math.max(-.5,Math.min(.5,drag.oy+(event.clientY-drag.y)/stage.clientHeight))}update()};
    const end=event=>{pointers.delete(event.pointerId);if(!pointers.size)drag=null};stage.onpointerup=stage.onpointercancel=end;range.oninput=()=>{state.crop.zoom=Number(range.value);update()};$('[data-crop-rotate]',layer).onclick=()=>{state.crop.rotation=(state.crop.rotation+90)%360;update()};$('[data-crop-reset]',layer).onclick=()=>{Object.assign(state.crop,{zoom:1,rotation:0,offsetX:0,offsetY:0});range.value=1;update()};layer.querySelectorAll('[data-crop-close]').forEach(button=>button.onclick=()=>layer.remove());$('[data-crop-confirm]',layer).onclick=async()=>{const button=$('[data-crop-confirm]',layer);button.disabled=true;button.textContent='Otimizando…';try{await onConfirm();layer.remove()}catch(error){Utils.toast(error.message||'Não foi possível ajustar a foto.',true);button.disabled=false;button.textContent='Usar foto'}};update();window.lucide?.createIcons()}
  function openForm(id){const existing=id?Produtos.obter(id):null,product=existing||{},productId=id||Utils.uuid(),state={file:null,image:null,originalUrl:null,previewUrl:null,processed:null,remove:false,crop:{zoom:1,rotation:0,offsetX:0,offsetY:0}},root=$('#modal');
    const body=()=>`${imageSection(state,product)}<div class="form-grid"><div class="field full"><label>Nome *</label><input name="nome" required value="${esc(product.nome||'')}"></div><div class="field"><label>Código</label><input name="codigo" value="${esc(product.codigo||'')}"></div><div class="field"><label>Categoria</label><input name="categoria" value="${esc(product.categoria||'')}"></div><div class="field"><label>Preço de venda *</label><input name="preco" type="number" inputmode="decimal" min="0" step=".01" required value="${product.preco??''}"></div><div class="field"><label>Custo unitário</label><input name="custo" type="number" inputmode="decimal" min="0" step=".01" value="${product.custo??''}"></div><div class="field"><label>Estoque atual</label><input name="estoqueAtual" type="number" inputmode="decimal" step="1" value="${product.estoqueAtual??product.estoque??0}"></div><div class="field"><label>Estoque mínimo</label><input name="estoqueMinimo" type="number" inputmode="decimal" min="0" step="1" value="${product.estoqueMinimo??0}"></div><label class="product-control-toggle full"><input name="semControleEstoque" type="checkbox" ${product.semControleEstoque?'checked':''}><span>Não controlar estoque deste produto</span></label><div class="field full"><label>Observação</label><textarea name="observacao">${esc(product.observacao||product.observacoes||'')}</textarea></div></div>`;
    root.innerHTML=`<div class="modal-bg"><section class="modal-box product-form-modal"><header class="modal-head"><h3>${id?'Editar produto':'Novo produto'}</h3><button class="icon-btn close" type="button"><i data-lucide="x"></i></button></header><form><div class="modal-body">${body()}</div><div class="product-upload-progress" hidden><span><i></i></span><small>Enviando imagem… <b>0%</b></small></div><footer class="modal-foot"><button type="button" class="btn btn-light cancel">Cancelar</button><button class="btn btn-primary" data-save-product>Salvar produto</button></footer></form></section></div>`;
    const modalBody=$('.modal-body',root),form=$('form',root);root.querySelectorAll('.close,.cancel').forEach(button=>button.onclick=()=>{cleanup();Modais.fechar()});
    const cleanup=()=>{if(state.originalUrl)URL.revokeObjectURL(state.originalUrl);if(state.previewUrl)URL.revokeObjectURL(state.previewUrl)};
    const rebindImage=()=>{const section=$('.product-image-field',modalBody);section.outerHTML=imageSection(state,product);bindImage()};
    const confirmCrop=async()=>{state.processed=await processProductImage(state.file,{...state.crop,image:state.image});if(state.previewUrl)URL.revokeObjectURL(state.previewUrl);state.previewUrl=URL.createObjectURL(state.processed.mainBlob);state.remove=false;rebindImage()};
    const choose=async file=>{try{validate(file);state.file=file;state.image=await decode(file);if(state.originalUrl)URL.revokeObjectURL(state.originalUrl);state.originalUrl=URL.createObjectURL(file);Object.assign(state.crop,{zoom:1,rotation:0,offsetX:0,offsetY:0});cropper(state,confirmCrop)}catch(error){Utils.toast(error.message||'Não foi possível ler esta imagem.',true)}};
    async function adjust(){if(!state.file){try{const response=await fetch(source(product));if(!response.ok)throw Error();const blob=await response.blob();validate(blob);state.file=new File([blob],'produto-atual',{type:blob.type});state.image=await decode(state.file);state.originalUrl=URL.createObjectURL(state.file)}catch{Utils.toast('Não foi possível carregar a foto atual para ajuste. Você pode escolher outra imagem.',true);return}}cropper(state,confirmCrop)}
    function bindImage(){const camera=$('#product-camera-input',root),gallery=$('#product-gallery-input',root);$('[data-photo-camera]',root)?.addEventListener('click',()=>camera.click());$('[data-photo-gallery]',root)?.addEventListener('click',()=>gallery.click());camera.onchange=()=>choose(camera.files[0]);gallery.onchange=()=>choose(gallery.files[0]);$('[data-photo-adjust]',root)?.addEventListener('click',adjust);$('[data-photo-remove]',root)?.addEventListener('click',()=>{if(confirm('Deseja remover a foto deste produto?')){state.remove=true;state.file=null;state.processed=null;if(state.previewUrl){URL.revokeObjectURL(state.previewUrl);state.previewUrl=null}rebindImage()}});window.lucide?.createIcons()}
    form.onsubmit=async event=>{event.preventDefault();const button=$('[data-save-product]',root),progress=$('.product-upload-progress',root),data=Object.fromEntries(new FormData(form));button.disabled=true;try{let imageData={};if(state.processed){if(!navigator.onLine)throw Error('A foto precisa de internet para ser enviada. Conecte-se e tente salvar novamente.');if(!window.ProductImageStorage)throw Error('O envio de fotos ainda está carregando. Tente novamente em instantes.');progress.hidden=false;imageData=await ProductImageStorage.upload(productId,state.processed,{operationId:Utils.uuid(),onProgress:value=>{progress.querySelector('i').style.width=`${value}%`;progress.querySelector('b').textContent=`${value}%`},oldProduct:product})}else if(state.remove){if(!navigator.onLine)throw Error('Conecte-se à internet para remover a foto.');await window.ProductImageStorage?.remove(product);imageData={imagem:'',imageUrl:null,imageStoragePath:null,imageThumbUrl:null,imageThumbStoragePath:null,imageUpdatedAt:new Date().toISOString(),imageUploadStatus:'none',imageOperationId:Utils.uuid()}}Produtos.salvar({id:productId,...data,semControleEstoque:new FormData(form).has('semControleEstoque'),favorito:product.favorito,ativo:true,...imageData});cleanup();Modais.fechar();Utils.toast('Produto salvo');if(matchMedia('(max-width:767px)').matches)ProdutosMobile?.refresh(true);else dispatchEvent(new CustomEvent('cloud-data-updated',{detail:{source:'product-form'}}))}catch(error){Utils.toast(error.message||'Não foi possível salvar o produto.',true);button.disabled=false;progress.hidden=true}};
    bindImage();window.lucide?.createIcons();setTimeout(()=>$('input[name="nome"]',root)?.focus(),50)
  }
  function enhance(root=document){if(!window.Produtos)return;root.querySelectorAll('.mobile-product-card,.pick-product,.entity-card.product-card,.editable-cart,.product-detail-modal').forEach(element=>{if(element.dataset.photoEnhanced)return;const id=element.dataset.productCard||element.dataset.add||element.querySelector('[data-edit-product]')?.dataset.editProduct||element.querySelector('[data-item-qty]')?.dataset.itemQty||element.querySelector('[data-detail-edit]')?.dataset.detailEdit,product=id&&Produtos.obter(id);if(!product)return;const target=element.matches('.mobile-product-card')?element.querySelector('.mobile-product-avatar'):element.matches('.pick-product,.editable-cart')?element:element.querySelector('.entity-head,.modal-body');if(!target)return;const holder=document.createElement('span');holder.innerHTML=markup(product,{className:element.matches('.mobile-product-card')?'enhanced-mobile-product-photo':element.matches('.pick-product')?'sale-product-photo':element.matches('.editable-cart')?'sale-cart-photo':'desktop-product-photo'});target.prepend(holder.firstElementChild);element.dataset.photoEnhanced='true'});root.querySelectorAll('img:not([data-photo-fallback-bound])').forEach(image=>{image.dataset.photoFallbackBound='true';image.addEventListener('error',()=>{image.hidden=true;const parent=image.parentElement;if(parent&&!parent.querySelector('.product-photo-fallback')){const fallback=document.createElement('span');fallback.className='product-photo-fallback';fallback.textContent=initials(image.alt||'?');parent.append(fallback)}})})}
  window.ProductImages={validate,processProductImage,markup,source,openForm,versionedUrl,enhance};
  let enhanceQueued=false;const observer=new MutationObserver(()=>{if(enhanceQueued)return;enhanceQueued=true;queueMicrotask(()=>{enhanceQueued=false;enhance(document)})});observer.observe(document.documentElement,{childList:true,subtree:true});addEventListener('DOMContentLoaded',()=>enhance());
  addEventListener('error',event=>{const image=event.target;if(!(image instanceof HTMLImageElement)||image.dataset.safeFallback==='true')return;image.dataset.safeFallback='true';image.hidden=true;const parent=image.parentElement;if(parent&&!parent.querySelector('.product-photo-fallback')){const fallback=document.createElement('span');fallback.className='product-photo-fallback';fallback.textContent=initials(image.alt||'?');parent.append(fallback)}},true);
})();
