window.DB=(()=>{
  const CHAVE='adiFestaDB_v1',VERSAO=5,agora=()=>new Date().toISOString();
  const configBase=()=>({nome:'Adi Festa'});
  const produtoDemo=(id,nome,preco,custo,estoqueAtual,estoqueMinimo,categoria)=>({id,nome,preco,custo,estoque:estoqueAtual,estoqueAtual,estoqueMinimo,categoria,ativo:true,criadoEm:agora(),atualizadoEm:agora()});
  const exemplo=()=>({versao:VERSAO,config:configBase(),clientes:[{id:'c1',nome:'Mariana Silva',telefone:'(17) 99665-5784',telefone2:'',email:'',endereco:'Shopping Center',complemento:'Loja ao lado',documento:'',observacoes:'Cliente frequente',totalComprado:78,quantidadeVendas:3,saldo:-36,ultimaCompra:agora(),ativo:true,criadoEm:agora(),atualizadoEm:agora()},{id:'c2',nome:'Carlos Souza',telefone:'(17) 98888-4321',telefone2:'',email:'',endereco:'',complemento:'',documento:'',observacoes:'',totalComprado:20,quantidadeVendas:1,saldo:0,ultimaCompra:agora(),ativo:true,criadoEm:agora(),atualizadoEm:agora()}],produtos:[produtoDemo('p1','Brigadeiro gourmet',6,2.1,38,10,'Doces'),produtoDemo('p2','Brownie recheado',10,4,22,8,'Doces'),produtoDemo('p3','Bolo no pote',14,5.5,15,6,'Bolos')],vendas:[],pagamentos:[],movimentacoes:[],movimentacoesEstoque:[],cobrancas:[]});
  const bloquearCargaAutomatica=config=>Object.assign(config,{demonstracaoRemovida:true,kyteImportacao:'Customers_20251012_20260705.csv',kyteSaldosImportacao:'Clientes.xlsx-v1',saldoCorrecoes:'confirmadas-v1',saldoNegativoEhDebito:true});
  const numero=v=>Number.isFinite(Number(v))?Number(v):0;
  const migrar=dados=>{
    const d=dados&&typeof dados==='object'?dados:{};
    d.versao=VERSAO;
    d.config=d.config&&typeof d.config==='object'?d.config:configBase();
    d.clientes=Array.isArray(d.clientes)?d.clientes:[];
    d.produtos=Array.isArray(d.produtos)?d.produtos:[];
    d.vendas=Array.isArray(d.vendas)?d.vendas:[];
    d.pagamentos=Array.isArray(d.pagamentos)?d.pagamentos:[];
    d.movimentacoes=Array.isArray(d.movimentacoes)?d.movimentacoes:[];
    d.movimentacoesEstoque=Array.isArray(d.movimentacoesEstoque)?d.movimentacoesEstoque:[];
    d.cobrancas=Array.isArray(d.cobrancas)?d.cobrancas:[];
    d.campanhas=Array.isArray(d.campanhas)?d.campanhas:[];
    d.progressosCampanha=Array.isArray(d.progressosCampanha)?d.progressosCampanha:Array.isArray(d.campaignProgress)?d.campaignProgress:[];
    d.recompensas=Array.isArray(d.recompensas)?d.recompensas:Array.isArray(d.rewards)?d.rewards:[];
    d.clientes=d.clientes.map(c=>({id:c.id||Utils.uuid(),nome:c.nome||'',telefone:c.telefone||'',telefone2:c.telefone2||'',email:c.email||'',endereco:c.endereco||'',complemento:c.complemento||'',documento:c.documento||'',observacoes:c.observacoes??c.observacao??'',totalComprado:numero(c.totalComprado),quantidadeVendas:numero(c.quantidadeVendas),saldo:numero(c.saldo??c.saldoPendente),ultimaCompra:c.ultimaCompra||null,ativo:c.ativo!==false,criadoEm:c.criadoEm||agora(),atualizadoEm:c.atualizadoEm||c.criadoEm||agora()}));
    d.produtos=d.produtos.map(p=>{const estoqueBase=p.estoqueAtual??p.estoque,estoqueAtual=estoqueBase===null||estoqueBase===''||estoqueBase===undefined?0:numero(estoqueBase);return{...p,id:p.id||Utils.uuid(),nome:p.nome||'',preco:numero(p.preco),custo:p.custo===null||p.custo===''?null:numero(p.custo),estoque:estoqueAtual,estoqueAtual,estoqueMinimo:numero(p.estoqueMinimo),categoria:p.categoria||'',ativo:p.ativo!==false,criadoEm:p.criadoEm||agora(),atualizadoEm:p.atualizadoEm||p.criadoEm||agora()}});
    d.vendas.forEach(v=>{v.clienteNome||=d.clientes.find(c=>c.id===v.clienteId)?.nome||'Venda avulsa';v.itens=Array.isArray(v.itens)?v.itens:[];v.subtotalOriginal??=numero(v.valorTotal);v.descontoTotal??=0;v.valorFinal??=numero(v.valorTotal);v.custoTotal??=v.itens.reduce((s,i)=>s+numero(i.custoTotal),0);v.lucro??=numero(v.valorFinal)-numero(v.custoTotal);v.valorTotal=numero(v.valorFinal);v.saldoAnterior??=0;v.saldoAtual??=v.status==='fiado'?-Math.abs(numero(v.valorFinal)):0});
    d.cobrancas=d.cobrancas.map(c=>({id:c.id||Utils.uuid(),clienteId:c.clienteId||'',clienteNome:c.clienteNome||'',valorCobrado:numero(c.valorCobrado),mensagem:c.mensagem||'',status:c.status||'enviado',data:c.data||agora()}));
    return d;
  };
  const salvar=dados=>{const normalizado=migrar(dados);normalizado.config.appSchemaVersion=Math.max(2,Number(normalizado.config.appSchemaVersion||0));normalizado.config.recentClientIds=Array.isArray(normalizado.config.recentClientIds)?normalizado.config.recentClientIds:[];normalizado.produtos.forEach(p=>{p.favorito=Boolean(p.favorito);p.semControleEstoque=Boolean(p.semControleEstoque);p.codigo=p.codigo||'';p.palavrasChave=p.palavrasChave||'';p.imagem=p.imagem||''});localStorage.setItem(CHAVE,JSON.stringify(normalizado));return normalizado};
  const carregar=()=>{try{const bruto=localStorage.getItem(CHAVE),dados=JSON.parse(bruto)||exemplo();if(bruto&&Number(dados.versao||0)<VERSAO&&!localStorage.getItem('adiFestaDB_auto_backup_schema_5'))localStorage.setItem('adiFestaDB_auto_backup_schema_5',bruto);return salvar(dados)}catch{return salvar(exemplo())}};
  const alterar=funcao=>{const dados=carregar();funcao(dados);return salvar(dados)};
  const validarBackup=d=>{if(!d||typeof d!=='object')throw Error('O arquivo nao contem um backup valido');const listas=['clientes','produtos','vendas','pagamentos','movimentacoes'];const ausentes=listas.filter(c=>!Array.isArray(d[c]));if(ausentes.length)throw Error(`Backup incompleto: faltam ${ausentes.join(', ')}`);if(!d.config||typeof d.config!=='object')throw Error('Backup incompleto: faltam as configuracoes');return true};
  const criarBackup=()=>{const d=structuredClone(carregar());d.backupInfo={app:'Adi Festa Controle',versao:VERSAO,exportadoEm:agora(),inclui:['clientes','produtos','vendas','pagamentos','movimentacoes','movimentacoesEstoque','cobrancas','campanhas','progressosCampanha','recompensas','config']};return d};
  const restaurarBackup=d=>{validarBackup(d);return salvar(d)};
  const limpar=()=>salvar({versao:VERSAO,config:bloquearCargaAutomatica(configBase()),clientes:[],produtos:[],vendas:[],pagamentos:[],movimentacoes:[],movimentacoesEstoque:[],cobrancas:[]});
  const restaurar=()=>{const d=exemplo();bloquearCargaAutomatica(d.config);return salvar(d)};
  return{carregar,salvar,alterar,limpar,restaurar,criarBackup,validarBackup,restaurarBackup,VERSAO};
})();
