import { auth, db, BUSINESS_ID } from './firebase-config.js';
import { onAuthStateChanged, signInWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js';
import { doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import './sync.js';

const gate=document.querySelector('#auth-gate');
const friendly=code=>({ 'auth/user-not-found':'E-mail não encontrado.','auth/wrong-password':'Senha incorreta.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/too-many-requests':'Muitas tentativas. Aguarde e tente novamente.','auth/network-request-failed':'Sem internet. Verifique sua conexão.' }[code]||'Não foi possível entrar agora. Tente novamente.');
function screen(html){gate.innerHTML=html;gate.hidden=false;document.documentElement.classList.add('auth-pending')}
function login(message=''){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Adi Festa Controle</h1><p>Entre para acessar suas vendas e clientes.</p><form id="login-form"><label>E-mail<input name="email" type="email" autocomplete="email" required inputmode="email"></label><label>Senha<div class="password-field"><input name="password" type="password" autocomplete="current-password" required><button type="button" id="toggle-password" aria-label="Mostrar senha">👁</button></div></label><p class="auth-error" id="auth-error">${message}</p><button class="btn btn-primary" id="login-submit">Entrar</button></form></section>`);document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('[name=password]');p.type=p.type==='password'?'text':'password'};document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const b=document.querySelector('#login-submit'),f=new FormData(e.currentTarget);b.disabled=true;b.textContent='Entrando…';try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch(error){login(friendly(error.code))}}}
function unauthorized(){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Acesso aguardando autorização</h1><p>Seu usuário ainda não foi autorizado neste sistema. Peça ao administrador para liberar sua conta.</p><button class="btn btn-light" id="logout-unauthorized">Sair da conta</button></section>`);document.querySelector('#logout-unauthorized').onclick=()=>signOut(auth)}
function allowed(user,profile){window.SyncFirebase.setUser(user);window.FirebaseSession={user,profile,businessId:profile.businessId||BUSINESS_ID};window.FirebaseAuthActions={signOut:()=>signOut(auth)};gate.hidden=true;document.documentElement.classList.remove('auth-pending');document.querySelector('.local-badge').innerHTML='<i data-lucide="cloud"></i> Sincronizado';document.querySelector('.avatar').textContent=(profile.name||user.email||'A')[0].toUpperCase();window.lucide?.createIcons();const original=DB.alterar;DB.alterar=function(fn){const result=original(fn);window.SyncFirebase.schedule();return result};}
screen('<section class="auth-card auth-loading"><div class="auth-logo">AF</div><p>Verificando acesso…</p></section>');
onAuthStateChanged(auth,async user=>{if(!user)return login();try{const profile=(await getDoc(doc(db,'users',user.uid))).data();if(!profile||profile.active!==true||profile.role!=='admin')return unauthorized();allowed(user,profile)}catch{login('Não foi possível validar sua autorização. Verifique a internet.') }});
