import { auth, db, BUSINESS_ID } from './firebase-config.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js';
import { doc, getDoc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import './sync.js';

const gate=document.querySelector('#auth-gate');
const OWNER_EMAIL='murillo.charles97@gmail.com';
const friendly=code=>({ 'auth/user-not-found':'E-mail não encontrado.','auth/wrong-password':'Senha incorreta.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/too-many-requests':'Muitas tentativas. Aguarde e tente novamente.','auth/network-request-failed':'Sem internet. Verifique sua conexão.' }[code]||'Não foi possível entrar agora. Tente novamente.');
function screen(html){gate.innerHTML=html;gate.hidden=false;document.documentElement.classList.add('auth-pending')}
function login(message=''){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Adi Festa Controle</h1><p>Entre para acessar suas vendas e clientes.</p><form id="login-form"><label>E-mail<input name="email" type="email" autocomplete="email" required inputmode="email"></label><label>Senha<div class="password-field"><input name="password" type="password" autocomplete="current-password" required><button type="button" id="toggle-password" aria-label="Mostrar senha">👁</button></div></label><p class="auth-error" id="auth-error">${message}</p><button class="btn btn-primary" id="login-submit">Entrar</button><button class="btn btn-light" type="button" id="show-register">Criar meu acesso</button></form></section>`);document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('[name=password]');p.type=p.type==='password'?'text':'password'};document.querySelector('#show-register').onclick=()=>register();document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const b=document.querySelector('#login-submit'),f=new FormData(e.currentTarget);b.disabled=true;b.textContent='Entrando…';try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch(error){login(friendly(error.code))}}}
async function bootstrap(user,name){const batch=writeBatch(db),now=serverTimestamp();batch.set(doc(db,'users',user.uid),{uid:user.uid,name,email:user.email,role:'admin',active:true,businessId:BUSINESS_ID,createdAt:now,updatedAt:now});batch.set(doc(db,'businesses',BUSINESS_ID),{name:'Adi Festa',ownerId:user.uid,createdAt:now,updatedAt:now,schemaVersion:2});await batch.commit()}
function register(message=''){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Criar acesso</h1><p>Cadastre o primeiro administrador da Adi Festa.</p><form id="register-form"><label>Nome<input name="name" required autocomplete="name"></label><label>E-mail autorizado<input name="email" type="email" value="${OWNER_EMAIL}" readonly></label><label>Senha<div class="password-field"><input name="password" type="password" minlength="6" autocomplete="new-password" required><button type="button" id="toggle-password" aria-label="Mostrar senha">👁</button></div></label><label>Confirmar senha<input name="confirm" type="password" minlength="6" autocomplete="new-password" required></label><p class="auth-error">${message}</p><button class="btn btn-primary" id="register-submit">Criar conta</button><button class="btn btn-light" type="button" id="back-login">Voltar para entrar</button></form></section>`);document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('[name=password]');p.type=p.type==='password'?'text':'password'};document.querySelector('#back-login').onclick=()=>login();document.querySelector('#register-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm'))return register('As senhas não são iguais.');const b=document.querySelector('#register-submit');b.disabled=true;b.textContent='Criando…';try{const result=await createUserWithEmailAndPassword(auth,OWNER_EMAIL,f.get('password'));await bootstrap(result.user,f.get('name'));location.reload()}catch(error){register(friendly(error.code))}}}
function unauthorized(user){const owner=user?.email===OWNER_EMAIL;screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>${owner?'Concluir configuração':'Acesso aguardando autorização'}</h1><p>${owner?'Sua conta existe, mas o perfil administrativo ainda precisa ser concluído.':'Seu usuário ainda não foi autorizado neste sistema.'}</p>${owner?'<button class="btn btn-primary" id="finish-bootstrap">Concluir meu acesso</button>':''}<button class="btn btn-light" id="logout-unauthorized">Sair da conta</button></section>`);if(owner)document.querySelector('#finish-bootstrap').onclick=async()=>{try{await bootstrap(user,'Administrador');location.reload()}catch{Utils.toast('Não foi possível concluir. Verifique as regras do Firestore.',true)}};document.querySelector('#logout-unauthorized').onclick=()=>signOut(auth)}
function allowed(user,profile){window.SyncFirebase.setUser(user);window.FirebaseSession={user,profile,businessId:profile.businessId||BUSINESS_ID};window.FirebaseAuthActions={signOut:()=>signOut(auth)};gate.hidden=true;document.documentElement.classList.remove('auth-pending');document.querySelector('.local-badge').innerHTML='<i data-lucide="cloud"></i> Sincronizado';document.querySelector('.avatar').textContent=(profile.name||user.email||'A')[0].toUpperCase();window.lucide?.createIcons();const original=DB.alterar;DB.alterar=function(fn){const result=original(fn);window.SyncFirebase.schedule();return result};}
screen('<section class="auth-card auth-loading"><div class="auth-logo">AF</div><p>Verificando acesso…</p></section>');
onAuthStateChanged(auth,async user=>{if(!user)return login();try{const profile=(await getDoc(doc(db,'users',user.uid))).data();if(!profile||profile.active!==true||profile.role!=='admin')return unauthorized(user);allowed(user,profile)}catch{unauthorized(user)}});
