import { auth, db, BUSINESS_ID } from './firebase-config.js';
import { onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, signOut } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-auth.js';
import { doc, getDoc, setDoc, writeBatch, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import './sync.js';

const gate=document.querySelector('#auth-gate');
const OWNER_EMAIL='murillo.charles97@gmail.com';
const friendly=code=>({'auth/invalid-email':'Informe um e-mail válido.','auth/user-not-found':'E-mail ou senha incorretos.','auth/wrong-password':'E-mail ou senha incorretos.','auth/invalid-credential':'E-mail ou senha incorretos.','auth/user-disabled':'Esta conta está desativada.','auth/too-many-requests':'Muitas tentativas. Aguarde e tente novamente.','auth/network-request-failed':'Não foi possível conectar. Verifique sua internet.'}[code]||'Não foi possível entrar agora. Tente novamente.');
function screen(html){gate.innerHTML=html;gate.hidden=false;document.documentElement.classList.add('auth-pending')}
function login(message=''){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Adi Festa Controle</h1><p>Entre para acessar suas vendas e clientes.</p><form id="login-form"><label>E-mail<input name="email" type="email" autocomplete="email" required inputmode="email"></label><label>Senha<div class="password-field"><input name="password" type="password" autocomplete="current-password" required><button type="button" id="toggle-password" aria-label="Mostrar senha">👁</button></div></label><p class="auth-error" id="auth-error">${message}</p><button class="btn btn-primary" id="login-submit">Entrar</button><button class="btn btn-light" type="button" id="show-register">Criar meu acesso</button></form></section>`);document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('[name=password]');p.type=p.type==='password'?'text':'password'};document.querySelector('#show-register').onclick=()=>register();document.querySelector('#login-form').onsubmit=async e=>{e.preventDefault();const b=document.querySelector('#login-submit'),f=new FormData(e.currentTarget);b.disabled=true;b.textContent='Entrando…';try{await signInWithEmailAndPassword(auth,f.get('email'),f.get('password'))}catch(error){login(friendly(error.code))}}}
async function bootstrap(user,name){const batch=writeBatch(db),now=serverTimestamp();batch.set(doc(db,'users',user.uid),{uid:user.uid,name,email:user.email,role:'admin',active:true,businessId:BUSINESS_ID,createdAt:now,updatedAt:now});batch.set(doc(db,'businesses',BUSINESS_ID),{id:BUSINESS_ID,name:'Adi Festa',ownerId:user.uid,active:true,createdAt:now,updatedAt:now,schemaVersion:2},{merge:true});await batch.commit()}
function register(message=''){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Criar acesso</h1><p>Cadastre o primeiro administrador da Adi Festa.</p><form id="register-form"><label>Nome<input name="name" required autocomplete="name"></label><label>E-mail autorizado<input name="email" type="email" value="${OWNER_EMAIL}" readonly></label><label>Senha<div class="password-field"><input name="password" type="password" minlength="6" autocomplete="new-password" required><button type="button" id="toggle-password" aria-label="Mostrar senha">👁</button></div></label><label>Confirmar senha<input name="confirm" type="password" minlength="6" autocomplete="new-password" required></label><p class="auth-error">${message}</p><button class="btn btn-primary" id="register-submit">Criar conta</button><button class="btn btn-light" type="button" id="back-login">Voltar para entrar</button></form></section>`);document.querySelector('#toggle-password').onclick=()=>{const p=document.querySelector('[name=password]');p.type=p.type==='password'?'text':'password'};document.querySelector('#back-login').onclick=()=>login();document.querySelector('#register-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(f.get('password')!==f.get('confirm'))return register('As senhas não são iguais.');const b=document.querySelector('#register-submit');b.disabled=true;b.textContent='Criando…';try{const result=await createUserWithEmailAndPassword(auth,OWNER_EMAIL,f.get('password'));await bootstrap(result.user,f.get('name'));location.reload()}catch(error){register(friendly(error.code))}}}
function unauthorized(user,message='Seu usuário ainda não foi autorizado neste sistema.',canBootstrap=false){screen(`<section class="auth-card"><div class="auth-logo">AF</div><h1>Acesso não autorizado</h1><p>${message}</p>${canBootstrap?'<button class="btn btn-primary" id="finish-bootstrap">Concluir meu acesso</button>':''}<button class="btn btn-light" id="logout-unauthorized">Sair da conta</button></section>`);if(canBootstrap)document.querySelector('#finish-bootstrap').onclick=async()=>{try{await bootstrap(user,'Administrador');location.reload()}catch(error){console.error('[Firebase bootstrap]',{code:error.code,message:error.message});Utils.toast('Não foi possível concluir. Verifique as regras do Firestore.',true)}};document.querySelector('#logout-unauthorized').onclick=()=>signOut(auth)}
let badgeSubscription=null;
function updateCloudBadge(syncState){const badge=document.querySelector('.local-badge');if(!badge)return;const count=Number(syncState.queueTotal||0),map=syncState.status==='error'?['cloud-off','Nuvem','error']:syncState.status==='offline'?['cloud-off','Nuvem','offline']:['testing','waiting','syncing'].includes(syncState.status)?['refresh-cw','Nuvem','syncing']:syncState.testPassed&&syncState.status==='success'?['cloud-check','Nuvem','success']:['cloud','Nuvem','idle'];const[icon,text,status]=map;badge.dataset.syncStatus=status;badge.setAttribute('role','button');badge.setAttribute('tabindex','0');badge.setAttribute('aria-label',`${text}. ${count} alterações pendentes`);badge.innerHTML=`<i data-lucide="${icon}"></i> ${text}${count?`<b class="cloud-count">${count}</b>`:''}`;window.lucide?.createIcons()}
async function logout(){let pending=window.SyncFirebase.getFirebaseDiagnostic().pendingOperations;if(!pending&&!confirm('Deseja realmente sair desta conta?'))return false;if(pending&&navigator.onLine){try{await window.SyncFirebase.synchronizeNow()}catch(error){console.error('[Sync before logout]',error)}}pending=window.SyncFirebase.getFirebaseDiagnostic().pendingOperations;if(pending&&!confirm(`Existem ${pending} alterações ainda não sincronizadas.\nElas continuam salvas neste aparelho.\n\nDeseja sair mesmo assim?`))return false;window.SyncFirebase.stop();badgeSubscription?.();badgeSubscription=null;window.FirebaseSession=null;location.hash='#/inicio';screen('<section class="auth-card auth-loading"><div class="auth-logo">AF</div><p>Saindo da conta…</p></section>');await signOut(auth);return true}
function allowed(user,profile){window.FirebaseSession={user,profile,businessId:profile.businessId};window.FirebaseAuthActions={signOut:logout};window.SyncFirebase.setUser(user,profile);gate.hidden=true;document.documentElement.classList.remove('auth-pending');document.querySelector('.avatar').textContent=(profile.name||user.email||'A')[0].toUpperCase();badgeSubscription?.();badgeSubscription=window.SyncFirebase.subscribe(updateCloudBadge);window.lucide?.createIcons();dispatchEvent(new CustomEvent('firebase-auth-ready',{detail:{uid:user.uid,businessId:profile.businessId}}));}
screen('<section class="auth-card auth-loading"><div class="auth-logo">AF</div><p>Verificando acesso…</p></section>');
onAuthStateChanged(auth,async user=>{window.SyncFirebase.setAuthReady(true);if(!user){window.SyncFirebase.stop();return login()}try{const reference=doc(db,'users',user.uid),snapshot=await getDoc(reference);if(!snapshot.exists())return unauthorized(user,'Seu usuário ainda não foi autorizado neste sistema.',user.email===OWNER_EMAIL);let profile=snapshot.data();if(!profile.uid&&user.email===OWNER_EMAIL&&profile.active===true&&profile.role==='admin'&&profile.businessId===BUSINESS_ID){await setDoc(reference,{uid:user.uid,updatedAt:serverTimestamp()},{merge:true});profile={...profile,uid:user.uid}}if(profile.uid!==user.uid)return unauthorized(user,'O perfil cadastrado não corresponde a esta conta.');if(profile.active!==true)return unauthorized(user,'Sua conta está desativada.');if(!profile.businessId)return unauthorized(user,'Esta conta não possui um negócio vinculado.');allowed(user,profile)}catch(error){console.error('[Firebase auth profile]',{code:error.code,message:error.message});unauthorized(user,'Não foi possível validar seu perfil agora. Verifique sua conexão.')}});
