import {auth,db} from './firebase-config.js';
import {collection,doc,onSnapshot,serverTimestamp,setDoc} from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';

const subscriptions=new Map(),now=()=>new Date().toISOString();
function publicPayload(visit){const settings=DB.carregar().config.catalogSettings||{},campaigns=(DB.carregar().campanhas||[]).filter(c=>c.ativo!==false&&c.publica!==false).map(c=>({id:c.id,nome:c.nome||c.titulo||'Campanha',descricao:c.descricao||''}));return{visitId:visit.id,businessId:window.FirebaseSession?.profile?.businessId||'',publicName:settings.publicName||DB.carregar().config.nome||'Adi Festa',primaryColor:settings.primaryColor||'#31d0ad',welcomeText:settings.welcomeText||visit.descricao||'Veja os produtos disponíveis e faça seu pedido.',local:visit.local,nome:visit.nome,data:visit.data,horarioChegada:visit.horarioChegada,horarioLimite:visit.horarioLimite,status:visit.status,active:visit.status==='recebendo',paymentMethods:settings.paymentMethods||['entrega','pix','dinheiro','cartao'],allowCredit:Boolean(settings.allowCredit),items:(visit.catalogItems||[]).filter(i=>i.active!==false).map(i=>({...i,reservedStock:0})),campaigns,updatedAt:serverTimestamp()}}
async function publish(visit){if(!auth.currentUser||!visit?.publicToken)return;try{const payload=publicPayload(visit),open=(DB.carregar().catalogOrders||[]).filter(o=>o.visitId===visit.id&&!['cancelado','entregue'].includes(o.orderStatus));payload.items=payload.items.map(item=>({...item,reservedStock:open.reduce((sum,o)=>sum+Number(o.items?.find(x=>x.catalogItemId===item.id)?.quantity||0),0)}));await setDoc(doc(db,'publicCatalogs',visit.publicToken),payload,{merge:true});subscribeVisit(visit)}catch(error){console.error('[Catalog publish]',error);Utils.toast?.('Visita salva; publicação aguardando a nuvem.',true)}}
function mergeOrders(visit,docs){const incoming=docs.map(s=>({id:s.id,...s.data(),visitId:visit.id,businessId:window.FirebaseSession?.profile?.businessId||'',updatedAt:s.data().updatedAt?.toDate?.()?.toISOString?.()||s.data().updatedAt||now(),createdAt:s.data().createdAt?.toDate?.()?.toISOString?.()||s.data().createdAt||now()}));let changed=false;DB.alterar(db=>{for(const order of incoming){const index=db.catalogOrders.findIndex(o=>o.id===order.id);if(index<0){db.catalogOrders.push(order);changed=true}else if(!db.catalogOrders[index].convertedSaleId&&new Date(order.updatedAt)>=new Date(db.catalogOrders[index].updatedAt||0)){db.catalogOrders[index]={...db.catalogOrders[index],...order};changed=true}}});if(changed){dispatchEvent(new CustomEvent('catalog-orders-updated',{detail:{visitId:visit.id}}));Utils.toast?.('Novo pedido recebido pelo catálogo.')}}
function subscribeVisit(visit){if(!visit?.publicToken||subscriptions.has(visit.publicToken))return;const unsub=onSnapshot(collection(db,'publicCatalogs',visit.publicToken,'orders'),snap=>mergeOrders(visit,snap.docs),error=>console.error('[Catalog orders listener]',error));subscriptions.set(visit.publicToken,unsub)}
function bindAll(){if(!auth.currentUser)return;for(const visit of DB.carregar().visitas||[]){subscribeVisit(visit);if(visit.publicToken)publish(visit)}}
addEventListener('catalog-publish-request',event=>publish(event.detail.visit));
addEventListener('catalog-orders-updated',event=>{const visit=DB.carregar().visitas.find(v=>v.id===event.detail.visitId);if(visit)publish(visit)});
addEventListener('catalog-order-status-request',event=>{const order=event.detail.order,visit=DB.carregar().visitas.find(v=>v.id===order.visitId);if(!visit?.publicToken)return;setDoc(doc(db,'publicCatalogs',visit.publicToken,'orders',order.id),{orderStatus:order.orderStatus,confirmedAt:order.confirmedAt||null,preparingAt:order.preparingAt||null,dispatchedAt:order.dispatchedAt||null,deliveredAt:order.deliveredAt||null,cancelledAt:order.cancelledAt||null,convertedSaleId:order.convertedSaleId||null,updatedAt:serverTimestamp()},{merge:true}).catch(error=>console.error('[Catalog order status]',error))});
addEventListener('firebase-auth-ready',bindAll);addEventListener('cloud-data-updated',()=>setTimeout(bindAll,200));
