import './sync.js?v=149';

let unsubscribe=null,lastState=null;
const escape=value=>String(value??'').replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]));
const notify=(message,error=false)=>window.Utils?.toast?.(message,error);
const formattedTime=value=>value?new Date(value).toLocaleString('pt-BR'):'Ainda não sincronizado';
function showDuplicates(){const groups=window.BackupManager?.findDuplicates?.(window.DB.carregar())||[];document.querySelector('#modal').innerHTML=`<div class="modal-bg"><section class="modal-box modal-wide"><header class="modal-head"><h3>Verificação de duplicados</h3><button class="icon-btn close" type="button"><i data-lucide="x"></i></button></header><div class="modal-body">${groups.length?`<div class="backup-warning"><b>${groups.length} possível(is) duplicação(ões) encontrada(s).</b> Nenhum registro foi alterado.</div><div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Motivo</th><th>IDs</th></tr></thead><tbody>${groups.slice(0,100).map(group=>`<tr><td>${escape(group.type)}</td><td>${escape(group.reason)}</td><td>${escape(group.ids.join(' / '))}</td></tr>`).join('')}</tbody></table></div>`:'<p>Nenhuma duplicação foi encontrada nos dados locais.</p>'}</div><footer class="modal-foot"><button class="btn btn-primary close" type="button">Fechar</button></footer></section></div>`;document.querySelectorAll('#modal .close').forEach(button=>button.onclick=()=>document.querySelector('#modal').innerHTML='');window.lucide?.createIcons()}

function settingsPanel(){
  const mobileSettings=document.querySelector('.mobile-settings-page');
  if(mobileSettings){
    if(mobileSettings.dataset.firebaseUiBound==='true')return;
    mobileSettings.dataset.firebaseUiBound='true';
    if(lastState)renderState(lastState);
    return;
  }
  const settings=document.querySelector('.settings');if(!settings||document.querySelector('#firebase-cloud-panel'))return;
  const session=window.FirebaseSession,profile=session?.profile||{},uid=session?.user?.uid||'';
  settings.insertAdjacentHTML('beforeend',`<section class="setting firebase-account"><div><b>Conta</b><div class="firebase-account-grid"><span>Nome</span><strong>${escape(profile.name||'Administrador')}</strong><span>E-mail</span><strong>${escape(session?.user?.email||'')}</strong><span>UID</span><strong>${escape(uid?`${uid.slice(0,8)}…`:'')}</strong><span>Perfil</span><strong>${profile.role==='admin'?'Administrador':escape(profile.role||'Usuário')}</strong><span>Negócio</span><strong>${escape(profile.businessId||'—')}</strong><span>Status</span><strong>${profile.active===true?'Ativo':'Inativo'}</strong></div></div><button class="btn btn-danger" id="firebase-logout" type="button">Sair da conta</button></section><section class="setting firebase-setting" id="firebase-cloud-panel"><div class="firebase-copy"><b>Nuvem</b><small>As alterações são salvas primeiro no aparelho e sincronizadas automaticamente.</small><div class="firebase-status" id="firebase-status" role="status">Preparando sincronização…</div><div class="firebase-sync-grid"><span>Última sincronização</span><strong id="firebase-last-sync">—</strong><span>Pendentes</span><strong id="firebase-pending">0</strong><span>Com erro</span><strong id="firebase-errors">0</strong><span>Migração inicial</span><strong>Concluída</strong><span>Modo atual</span><strong>Sincronização automática</strong></div><button class="firebase-details-toggle" id="firebase-details-toggle" type="button">Ver detalhes técnicos</button><dl class="firebase-details" id="firebase-details" hidden></dl></div><div class="actions firebase-actions"><button class="btn btn-dark" id="firebase-sync" type="button">Sincronizar agora</button></div></section>`);
  settings.querySelector('#firebase-cloud-panel .firebase-sync-grid')?.insertAdjacentHTML('beforeend','<span>Operações órfãs / somente locais</span><strong id="firebase-orphans">0</strong>');
  document.querySelector('#firebase-details').insertAdjacentHTML('afterend','<button class="btn btn-light" id="firebase-duplicates" type="button" hidden>Verificar duplicados</button>');
  document.querySelector('#firebase-sync').onclick=manualSync;
  document.querySelector('#firebase-logout').onclick=()=>window.FirebaseAuthActions?.signOut?.();
  document.querySelector('#firebase-details-toggle').onclick=event=>{const details=document.querySelector('#firebase-details');details.hidden=!details.hidden;document.querySelector('#firebase-duplicates').hidden=details.hidden;event.currentTarget.textContent=details.hidden?'Ver detalhes técnicos':'Ocultar detalhes técnicos'};
  document.querySelector('#firebase-duplicates').onclick=showDuplicates;
  if(lastState)renderState(lastState)
}

async function manualSync(){const button=document.querySelector('#firebase-sync')||document.querySelector('#cloud-panel-sync'),original=button?.textContent;if(button){button.disabled=true;button.textContent='Sincronizando…'}try{const result=await window.SyncFirebase.synchronizeNow();notify(window.SyncFirebase.describeResult?.(result)||'Não foi possível confirmar a sincronização.',!result.complete)}catch(error){notify('Não foi possível sincronizar agora.',true);console.error('[Manual sync]',{code:error.code,message:error.message})}finally{if(button){button.disabled=false;button.textContent=original}}}

function renderQueueError(item){const paths=(item.paths||[item.firestorePath]).filter(Boolean).slice(0,12);return `<article><b>${escape(item.entityType)} · ${escape(item.subtype||item.action)}</b><small>${escape(formattedTime(item.createdAt))}</small><p>${escape(item.errorCode||'erro')}: ${escape(item.errorMessage||'A operação precisa de atenção.')}</p><dl class="sync-error-metadata"><dt>Ação</dt><dd>${escape(item.action)}</dd><dt>Documento</dt><dd>${escape(item.documentId||'—')}</dd><dt>Collection/path</dt><dd>${paths.map(escape).join('<br>')}</dd><dt>Empresa da operação</dt><dd>${escape(item.businessId||'—')}</dd><dt>Empresa atual</dt><dd>${escape(item.currentBusinessId||'—')}</dd><dt>Payload / schema</dt><dd>${escape(`${item.payloadVersion||1} / ${item.schemaVersion||1}`)}</dd><dt>Usuário / perfil</dt><dd>${escape(`${item.authUid||'—'} · ${item.role||'—'}`)}</dd><dt>Origem</dt><dd>${escape(item.createdBeforeMultiTenant?'anterior à migração multiempresa':item.origin||'atual')}</dd><dt>Última tentativa</dt><dd>${escape(formattedTime(item.lastAttemptAt||item.createdAt))}</dd></dl><code>${escape(String(item.operationId||'').slice(0,10))}… · ${escape(item.origin)}</code></article>`}

const money=value=>Number(value||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function dataAuditHtml(report){if(!report)return '<section class="sync-data-state"><h4>Estado dos dados</h4><p>Execute a comparação para identificar registros que existem somente neste aparelho.</p></section>';const row=(label,data)=>`<article><b>${escape(label)}</b><span>Local: <strong>${escape(data.local)}</strong></span><span>Nuvem: <strong>${escape(data.remote)}</strong></span><span>Somente neste aparelho: <strong>${escape(data.onlyLocal)}</strong></span><span>Somente na nuvem: <strong>${escape(data.onlyRemote)}</strong></span><span>Divergentes: <strong>${escape(data.divergent)}</strong></span></article>`,balance=report.financial.balanceAudit,clients=new Map((window.DB?.carregar?.().clientes||[]).map(client=>[String(client.id),client.nome]));const balanceHtml=balance?`<section class="sync-financial-audit"><h4>Auditoria dos saldos confirmados</h4><div class="sync-balance-comparison"><span>Total atual na nuvem <b>${escape(money(balance.actualOpenDebt))}</b></span><span>Total esperado pelos movimentos <b>${escape(money(balance.expectedOpenDebt))}</b></span><span>Diferença <b>${escape(money(balance.openDebtDifference))}</b></span></div><p><b>${escape(balance.divergentCount)}</b> cliente(s) divergente(s) · <b>${escape(balance.safeCount)}</b> correção(ões) segura(s) · <b>${escape(balance.unsafeCount)}</b> para revisão manual.</p>${balance.divergent?.length?`<div class="sync-financial-preview">${balance.divergent.slice(0,30).map(item=>`<article class="${item.status==='safe_missing_effects'?'is-safe':'is-warning'}"><b>${escape(clients.get(String(item.clientId))||`Cliente ${String(item.clientId).slice(0,8)}…`)}</b><span>Nuvem: ${escape(money(Math.abs(Math.min(0,item.actualBalance))))}</span><span>Esperado: ${escape(money(Math.abs(Math.min(0,item.expectedBalance))))}</span><small>${item.status==='safe_missing_effects'?`${item.missingEffects.length} efeito(s) ausente(s) identificados`:'Exige revisão manual; não será alterado'}</small></article>`).join('')}</div>`:''}</section>`:'';return `<section class="sync-data-state"><h4>Estado dos dados</h4><small>Comparado em ${escape(formattedTime(report.generatedAt))}</small><div class="sync-data-state-grid">${row('Produtos',report.products)}${row('Clientes',report.clients)}${row('Financeiro',report.financial)}</div><div class="sync-balance-comparison"><span>Saldo local <b>${escape(money(report.financial.localBalance))}</b></span><span>Saldo na nuvem <b>${escape(money(report.financial.remoteBalance))}</b></span><span>Diferença <b>${escape(money(report.financial.balanceDifference))}</b></span></div>${balanceHtml}</section>`}
async function exportDiagnostic(){try{const report=await window.SyncFirebase.exportLocalDiagnostic();window.SyncFirebase.downloadJsonFile(report,`diagnostico-sync-${report.businessId}-${Date.now()}.json`);notify('Diagnóstico exportado sem dados pessoais completos.')}catch(error){notify(error.message||'Não foi possível exportar o diagnóstico.',true)}}
async function compareCloudData(button){const original=button.textContent;button.disabled=true;button.textContent='Comparando…';try{await window.SyncFirebase.compareDeviceWithCloud();notify('Comparação concluída. Nenhum dado local foi alterado.');openQueueDetails()}catch(error){notify(error.message||'Não foi possível comparar com a nuvem.',true);button.disabled=false;button.textContent=original}}
async function recoverLocalData(){const report=lastState?.details?.dataAudit||lastState?.dataAudit;if(!report)return notify('Compare com a nuvem antes de recuperar.',true);const count=report.products.onlyLocal+report.clients.onlyLocal;if(!count)return notify('Nenhum registro ausente para recuperar.');if(!confirm(`Serão enviados ${count} produtos, variações ou clientes ausentes. Um backup será baixado antes. Continuar?`))return;try{const result=await window.SyncFirebase.recoverMissingNonFinancial();notify(`${result.sync.sent||0} operação(ões) confirmada(s) na nuvem.${result.blocked?.length?` ${result.blocked.length} ficaram bloqueadas para revisão.`:''}`,Boolean(result.sync.errors||result.blocked?.length));openQueueDetails()}catch(error){notify(error.message||'A recuperação foi interrompida com segurança.',true)}}
async function reconcileBalances(){const audit=(lastState?.details?.dataAudit||lastState?.dataAudit)?.financial?.balanceAudit;if(!audit)return notify('Execute a comparação com a nuvem antes de reconciliar.',true);if(!audit.safeCount)return notify('Nenhuma correção financeira segura foi identificada.',Boolean(audit.unsafeCount));const summary=`Foram identificados ${audit.safeBalanceCount||0} saldo(s) e ${audit.effectBackfillCount||0} histórico(s) financeiro(s) que podem ser reconciliados com segurança. A diferença de saldo comprovada é ${money(Math.abs(audit.openDebtDifference))}. Um backup será baixado antes. Aplicar somente as correções seguras?`;if(!confirm(summary))return;try{const result=await window.SyncFirebase.reconcileFinancialBalances();notify(`${result.applied.length} cliente(s) reconciliado(s).${result.blocked.length?` ${result.blocked.length} ficaram bloqueados para revisão.`:''}`,Boolean(result.blocked.length));openQueueDetails()}catch(error){notify(error.message||'A reconciliação foi interrompida sem alterar os demais saldos.',true)}}

function onlyLocalSalesHtml(filter={}){
  let sales=[];try{sales=window.SyncFirebase.onlyLocalSaleReport?.()||[]}catch{return ''}
  if(!sales.length)return '';
  const filtered=sales.filter(sale=>!filter.saleId&&!filter.customerId||
    (filter.saleId&&sale.saleId===filter.saleId)||(filter.customerId&&sale.customerId===filter.customerId));
  const rows=filtered.map(sale=>`<article class="sync-orphan-sale"><b>${escape(sale.customer||'Cliente não identificado')}</b><span>${escape(money(sale.amount))} · ${escape(sale.paymentMethod||'Pagamento não informado')} · ${escape(formattedTime(sale.date))}</span><small>${escape(sale.resolved?'Conciliada manualmente; protegida contra nova cobrança':sale.classification==='A'?'Recuperação possível após confirmação':'Pendência antiga exige decisão')} · status ${escape(sale.status||'não informado')}</small><div class="sync-orphan-actions"><button class="btn ${sale.resolved?'btn-light':'btn-primary'}" type="button" data-sale-detail="${escape(sale.saleId)}">${sale.resolved?'Ver conciliação':'Resolver agora'}</button></div></article>`).join('');
  return `<section class="sync-error-list sync-orphan-list"><h4>${escape(sales.length)} venda(s) deste aparelho não estão na nuvem</h4><p>Nenhuma será enviada automaticamente. Revise cliente, itens, saldo e estoque antes de recuperar.</p>${filter.customerId||filter.saleId?`<p>Mostrando ${filtered.length} operação(ões) relacionadas. <button type="button" data-sale-show-all>Ver todas</button></p>`:''}${rows||'<p>Nenhuma venda deste cliente apareceu na última comparação.</p>'}</section>`;
}
function openOnlyLocalSaleDetails(saleId,filter={}){
  const sale=(window.SyncFirebase.onlyLocalSaleReport?.()||[]).find(item=>item.saleId===saleId),root=document.querySelector('#modal');
  if(!sale)return notify('Refaça a comparação; a operação não está mais na lista.',true);
  const itemRows=(sale.items||[]).map(item=>`<li>${escape(item.name||item.productId)} · ${escape(item.quantity)} × ${escape(money(item.unitPrice))}</li>`).join('');
  const owner=['owner','admin'].includes(lastState?.details?.userRole),status=sale.resolved?'Pendência conciliada':'Existe uma pendência antiga';
  root.innerHTML=`<div class="modal-bg"><section class="modal-box modal-wide sync-diagnostics-modal legacy-resolution-sheet"><header class="modal-head"><div><small>${escape(status)}</small><h3>${escape(sale.customer||'Cliente')}</h3></div><button class="icon-btn" type="button" data-sale-back aria-label="Fechar"><i data-lucide="x"></i></button></header><div class="modal-body"><p>${sale.resolved?'Esta operação foi conciliada e não será sincronizada novamente.':'Encontramos uma venda antiga deste cliente que não está confirmada na nuvem.'}</p><div class="legacy-resolution-summary"><span><small>Data</small><b>${escape(formattedTime(sale.date))}</b></span><span><small>Valor da pendência</small><b>${escape(money(sale.amount))}</b></span><span><small>Forma de pagamento</small><b>${escape(sale.paymentMethod||'Não informada')}</b></span><span><small>Saldo atual na nuvem</small><b>${escape(money(Math.abs(Math.min(0,Number(sale.remoteCurrentBalance||0))))) } em aberto</b></span></div>${itemRows?`<h4>Itens registrados</h4><ul>${itemRows}</ul>`:''}<p class="muted">${escape(sale.reason)}</p><details class="sync-technical-ids"><summary>Detalhes técnicos</summary><code>Venda: ${escape(sale.saleId)}</code><code>Operação: ${escape(sale.operationId)}</code></details>${sale.resolved?`<div class="backup-warning"><b>Saldo conciliado:</b> ${escape(money(Math.abs(Math.min(0,Number(sale.reconciledBalanceBefore||0)))))} → ${escape(money(Math.abs(Math.min(0,Number(sale.reconciledBalanceAfter||0)))))} em aberto.</div>`:''}</div><footer class="modal-foot"><button class="btn btn-light" type="button" data-sale-back>${filter.fromCart?'Voltar ao carrinho':'Voltar'}</button>${!sale.resolved&&owner?'<button class="btn btn-light" type="button" data-sale-reconcile>Corrigir saldo manualmente</button>':''}${!sale.resolved&&sale.classification==='A'&&owner?`<button class="btn btn-primary" type="button" data-sale-recover="${escape(sale.saleId)}">Recuperar venda original</button>`:''}</footer></section></div>`;
  root.querySelectorAll('[data-sale-back]').forEach(button=>button.onclick=()=>{
    if(filter.fromCart)root.innerHTML='';else openQueueDetails(filter);
  });
  root.querySelector('[data-sale-recover]')?.addEventListener('click',()=>recoverOnlyLocalSale(sale));
  root.querySelector('[data-sale-reconcile]')?.addEventListener('click',()=>openManualReconciliation(sale,filter));
  window.lucide?.createIcons();
}
function openManualReconciliation(sale,filter={}){
  const root=document.querySelector('#modal'),currentDebt=Math.abs(Math.min(0,Number(sale.remoteCurrentBalance||0)));
  root.innerHTML=`<div class="modal-bg"><section class="modal-box sync-diagnostics-modal legacy-resolution-sheet"><header class="modal-head"><div><small>Corrigir saldo manualmente</small><h3>${escape(sale.customer||'Cliente')}</h3></div><button class="icon-btn" type="button" data-reconcile-back aria-label="Voltar"><i data-lucide="x"></i></button></header><form data-reconciliation-form><div class="modal-body"><div class="legacy-cloud-balance"><small>Saldo atual na nuvem</small><strong>${escape(money(currentDebt))} em aberto</strong></div><label class="field"><span>Saldo correto total em aberto</span><input name="correctDebt" type="number" inputmode="decimal" min="0" step="0.01" placeholder="0,00" required><small>Informe o total que o cliente realmente deve agora, não apenas o valor desta venda.</small></label><label class="field"><span>Motivo</span><textarea name="reason" required>Operação antiga não sincronizada</textarea></label><p class="muted">Isto criará um ajuste de reconciliação auditável. Não será criada uma venda ou receita.</p></div><footer class="modal-foot"><button class="btn btn-light" type="button" data-reconcile-back>Cancelar</button><button class="btn btn-primary" type="submit">Confirmar reconciliação</button></footer></form></section></div>`;
  root.querySelectorAll('[data-reconcile-back]').forEach(button=>button.onclick=()=>openOnlyLocalSaleDetails(sale.saleId,filter));
  root.querySelector('[data-reconciliation-form]').onsubmit=async event=>{
    event.preventDefault();const form=event.currentTarget,button=form.querySelector('[type="submit"]'),debt=Number(form.elements.correctDebt.value),reason=String(form.elements.reason.value||'').trim();
    if(!Number.isFinite(debt)||debt<0)return notify('Informe o saldo correto em aberto.',true);
    const before=money(Math.abs(Math.min(0,Number(sale.remoteCurrentBalance||0)))),after=money(debt);
    if(!confirm(`O saldo de ${sale.customer} será alterado de ${before} para ${after} em aberto.\n\nA operação antiga será marcada como conciliada e não será sincronizada novamente.`))return;
    button.disabled=true;button.textContent='Conciliando…';
    try{const result=await window.SyncFirebase.reconcileOnlyLocalSaleBalance(sale.saleId,debt,reason);root.innerHTML='';window.Checkout?.resumeAfterReconciliation?.(sale.customerId);window.DesktopSales?.refreshClients?.();notify(result.idempotent?'Esta pendência já estava conciliada.':'Saldo conciliado. O carrinho foi atualizado e o fiado deste cliente está liberado.');}
    catch(error){notify(error.message||'Não foi possível confirmar a reconciliação.',true);button.disabled=false;button.textContent='Confirmar reconciliação'}
  };
  window.lucide?.createIcons();
}
async function recoverOnlyLocalSale(sale){
  if(!confirm(`Recuperar somente a venda ${sale.saleId} de ${sale.customer} (${money(sale.amount)})? A nuvem será revalidada antes de qualquer alteração; um backup será baixado.`))return;
  try{const result=await window.SyncFirebase.recoverOnlyLocalSale(sale.saleId);notify(result.idempotent?'Venda já confirmada na nuvem.':'Venda recuperada e confirmada na nuvem.');openQueueDetails({customerId:sale.customerId})}
  catch(error){notify(error.message||'A recuperação foi interrompida sem reenviar outras vendas.',true);openQueueDetails({customerId:sale.customerId})}
}
function exportOnlyLocalSales(){
  try{const sales=window.SyncFirebase.onlyLocalSaleReport();const businessId=lastState?.details?.userBusinessId||'empresa';window.SyncFirebase.downloadJsonFile({version:148,mode:'read-only',generatedAt:new Date().toISOString(),businessId,sales},`auditoria-vendas-somente-locais-${businessId}-${Date.now()}.json`);notify('Auditoria detalhada exportada. O arquivo contém dados de clientes; guarde-o com cuidado.')}
  catch(error){notify(error.message||'Compare com a nuvem antes de exportar.',true)}
}

function openQueueDetails(filter={}){
  const state=lastState||{},details=state.details||{},items=window.SyncFirebase.getQueueDiagnostics?.()||[],errors=items.filter(item=>item.status==='error'),processing=items.filter(item=>item.status==='syncing').length,root=document.querySelector('#modal');
  root.innerHTML=`<div class="modal-bg"><section class="modal-box modal-wide sync-diagnostics-modal"><header class="modal-head"><h3>Sincronização ${state.queueTotal?'incompleta':'dos dados'}</h3><button class="icon-btn close" type="button"><i data-lucide="x"></i></button></header><div class="modal-body"><div class="firebase-sync-grid"><span>Pendentes</span><strong>${escape(state.pending||0)}</strong><span>Com erro</span><strong>${escape(state.errors||0)}</strong><span>Processando</span><strong>${escape(processing)}</strong><span>Última tentativa</span><strong>${escape(formattedTime(details.lastAttemptAt))}</strong><span>Última sincronização completa</span><strong>${escape(formattedTime(details.lastCompleteSyncAt||state.lastSync))}</strong><span>Listener remoto</span><strong>${details.listenerConnected?'Ativo':'Inativo'}</strong><span>BusinessId</span><strong>${escape(details.userBusinessId||'—')}</strong><span>Build</span><strong>${escape(window.AdiFestaBuild?.shortCommit||'local')}</strong><span>Projeto</span><strong>${escape(details.projectId||'—')}</strong></div><section class="sync-error-list"><h4>Erros recentes</h4>${errors.length?errors.slice(0,50).map(item=>`<article><b>${escape(item.entityType)} · ${escape(item.action)}</b><small>${escape(formattedTime(item.createdAt))}</small><p>${escape(item.errorCode||'erro')}: ${escape(item.errorMessage||'A operação precisa de atenção.')}</p><code>${escape(item.operationId.slice(0,10))}… · ${escape(item.origin)}</code></article>`).join(''):'<p>Nenhuma operação marcada com erro neste aparelho.</p>'}</section></div><footer class="modal-foot"><button class="btn btn-light close" type="button">Fechar</button><button class="btn btn-light" type="button" data-open-technical>Ver diagnóstico técnico</button><button class="btn btn-primary" type="button" data-retry-all>${errors.length?'Reprocessar todos':'Tentar novamente'}</button></footer></section></div>`;
  root.querySelector('.sync-diagnostics-modal .firebase-sync-grid')?.insertAdjacentHTML('beforeend',`<span>Órfãs / somente locais</span><strong>${escape(state.orphanOperations||0)}</strong>`);
  const errorSection=root.querySelector('.sync-error-list');if(errorSection&&errors.length)errorSection.innerHTML=`<h4>Erros recentes</h4>${errors.slice(0,50).map(renderQueueError).join('')}`;
  const comparison=details.comparison||state.comparison,local=comparison?.local||{},remote=comparison?.remote||{},mismatches=comparison&&!comparison.ok?[['Clientes',local.clientes,remote.clients],['Produtos',local.produtos,remote.products],['Vendas',local.vendas,remote.sales],['Pagamentos',local.pagamentos,remote.payments],['Fiado',Number(local.fiado||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),Number(remote.fiado||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'})]].filter(([,device,cloud])=>device!==cloud):[];
  if(mismatches.length){root.querySelector('.modal-head h3').textContent='Sincronização incompleta';root.querySelector('.sync-error-list').insertAdjacentHTML('beforebegin',`<section class="sync-error-list"><h4>Diferenças entre aparelho e nuvem</h4>${mismatches.map(([label,device,cloud])=>`<article><b>${escape(label)}</b><p>Aparelho: ${escape(device)} · Nuvem: ${escape(cloud)}</p></article>`).join('')}</section>`)}
  const dataAudit=details.dataAudit||state.dataAudit||null;
  errorSection?.insertAdjacentHTML('beforebegin',dataAuditHtml(dataAudit));
  if(dataAudit?.collections?.sales?.onlyLocal?.length)
    errorSection?.insertAdjacentHTML('beforebegin',onlyLocalSalesHtml(filter));
  const footer=root.querySelector('.modal-foot');
  footer.insertAdjacentHTML('afterbegin','<button class="btn btn-light" type="button" data-export-diagnostic>Exportar diagnóstico</button><button class="btn btn-light" type="button" data-compare-cloud>Comparar com a nuvem</button>');
  if(dataAudit?.products?.onlyLocal||dataAudit?.clients?.onlyLocal)footer.insertAdjacentHTML('afterbegin','<button class="btn btn-primary" type="button" data-recover-local>Recuperar dados locais ausentes</button>');
  if(dataAudit?.collections?.sales?.onlyLocal?.length)footer.insertAdjacentHTML('afterbegin','<button class="btn btn-light" type="button" data-export-only-local>Exportar auditoria das vendas</button>');
  if(dataAudit?.financial?.balanceAudit?.safeCount&&!dataAudit?.financial?.onlyLocal&&!dataAudit?.products?.onlyLocal&&!dataAudit?.clients?.onlyLocal)footer.insertAdjacentHTML('afterbegin','<button class="btn btn-primary" type="button" data-reconcile-balances>Reconciliar saldos</button>');
  const canRefresh=dataAudit&&state.queueTotal===0&&!Object.values(dataAudit.collections||{}).some(item=>item.onlyLocal?.length||item.divergent?.length);
  if(canRefresh)footer.insertAdjacentHTML('afterbegin','<button class="btn btn-light" type="button" data-refresh-server>Atualizar deste servidor</button>');
  root.querySelectorAll('.close').forEach(button=>button.onclick=()=>root.innerHTML='');
  root.querySelector('[data-open-technical]').onclick=event=>{const panel=document.querySelector('.desktop-technical-details'),mobile=document.querySelector('#firebase-details');if(panel||mobile){root.innerHTML='';if(panel)panel.open=true;if(mobile)mobile.hidden=false;return}const existing=root.querySelector('[data-sync-technical]');if(existing){existing.remove();event.currentTarget.textContent='Ver diagnóstico técnico';return}root.querySelector('.modal-body').insertAdjacentHTML('afterbegin',`<details data-sync-technical open><summary>Diagnóstico técnico</summary><dl class="firebase-sync-grid">${technicalDetails({...state.details,lastSyncAt:state.lastSync})}</dl></details>`);event.currentTarget.textContent='Ocultar diagnóstico técnico'};
  const retryAll=root.querySelector('[data-retry-all]');
  if(state.queueTotal){retryAll.textContent=errors.length?'Reprocessar todos':'Sincronizar pendentes';retryAll.onclick=async()=>{await manualSync();openQueueDetails(filter)}}
  else retryAll.remove();
  root.querySelector('[data-export-diagnostic]').onclick=exportDiagnostic;
  root.querySelector('[data-compare-cloud]').onclick=event=>compareCloudData(event.currentTarget);
  root.querySelector('[data-export-only-local]')?.addEventListener('click',exportOnlyLocalSales);
  root.querySelector('[data-sale-show-all]')?.addEventListener('click',()=>openQueueDetails());
  root.querySelectorAll('[data-sale-detail]').forEach(button=>button.onclick=()=>openOnlyLocalSaleDetails(button.dataset.saleDetail,filter));
  root.querySelectorAll('[data-sale-recover]').forEach(button=>button.onclick=()=>{const sale=(window.SyncFirebase.onlyLocalSaleReport?.()||[]).find(item=>item.saleId===button.dataset.saleRecover);if(sale)recoverOnlyLocalSale(sale)});
  root.querySelector('[data-recover-local]')?.addEventListener('click',recoverLocalData);
  root.querySelector('[data-reconcile-balances]')?.addEventListener('click',reconcileBalances);
  root.querySelector('[data-refresh-server]')?.addEventListener('click',async()=>{try{await window.SyncFirebase.refreshSafelyFromServer();notify('Dados deste servidor atualizados com segurança.');openQueueDetails()}catch(error){notify(error.message||'Não foi possível atualizar deste servidor.',true)}});
  window.lucide?.createIcons();
}
function ensureDetailsButton(){
  const syncButton=document.querySelector('#firebase-sync');
  if(!syncButton||document.querySelector('[data-sync-details]'))return;
  const button=document.createElement('button');
  button.type='button';button.className='btn btn-light';button.dataset.syncDetails='true';button.innerHTML='<i data-lucide="list-tree"></i> Ver detalhes';button.onclick=openQueueDetails;
  syncButton.insertAdjacentElement('afterend',button);window.lucide?.createIcons();
}

function technicalDetails(d){const build=window.AdiFestaBuild||{},uid=d.uid?`${String(d.uid).slice(0,6)}…${String(d.uid).slice(-4)}`:'—',common=`<dt>Projeto Firebase</dt><dd>${escape(d.projectId||'—')}</dd><dt>BusinessId atual</dt><dd>${escape(d.userBusinessId||'—')}</dd><dt>UID abreviado</dt><dd>${escape(uid)}</dd><dt>Última sincronização</dt><dd>${escape(formattedTime(d.lastSyncAt))}</dd><dt>Itens pendentes</dt><dd>${escape(d.pendingOperations??0)}</dd><dt>Schema</dt><dd>${escape(d.schemaVersion??3)}</dd><dt>Build</dt><dd>${escape(build.shortCommit||'local')}</dd><dt>Data do build</dt><dd>${escape(build.builtAt?formattedTime(build.builtAt):'—')}</dd>`;if(document.querySelector('.mobile-settings-page'))return `${common}<dt>Migration Version</dt><dd>${escape(window.FirebaseBootstrap?.details?.migrationVersion??'—')}</dd><dt>Perfil</dt><dd>${escape(`${d.userRole||'—'} · ${d.userActive?'ativo':'inativo'}`)}</dd><dt>Listener da empresa</dt><dd>${d.listenerConnected?'ativo':'inativo'}</dd><dt>Cache hidratado</dt><dd>${d.hydrated?'sim':'não'}</dd><dt>Último erro</dt><dd>${escape(d.lastErrorCode?`${d.lastErrorCode}: ${d.lastErrorMessage}`:'nenhum')}</dd>`;return `${common}<dt>Banco</dt><dd>${escape(d.databaseId)}</dd><dt>Perfil</dt><dd>${escape(`${d.userRole||'—'} · ${d.userActive?'ativo':'inativo'}`)}</dd><dt>Negócio localizado</dt><dd>${d.businessDocumentExists?'sim':'não'}</dd><dt>Listener da empresa</dt><dd>${d.listenerConnected?'ativo':'inativo'}</dd><dt>Cache hidratado</dt><dd>${d.hydrated?'sim':'não'}</dd><dt>Leituras nesta sessão</dt><dd>${escape(d.sessionReads??0)}</dd><dt>Gravações nesta sessão</dt><dd>${escape(d.sessionWrites??0)}</dd><dt>Consultas nesta sessão</dt><dd>${escape(d.sessionQueries??0)}</dd><dt>Último erro</dt><dd>${escape(d.lastErrorCode?`${d.lastErrorCode}: ${d.lastErrorMessage}`:'nenhum')}</dd>`}

const setText=(element,value)=>{const text=String(value??'');if(element&&element.textContent!==text)element.textContent=text};
const setHtml=(element,value)=>{if(element&&element.innerHTML!==value)element.innerHTML=value};
function renderState(state){lastState=state;window.SyncFirebaseState=state;const last=formattedTime(state.lastSync),status=document.querySelector('#firebase-status');if(status){const className=`firebase-status is-${state.status}`;if(status.className!==className)status.className=className;setText(status,state.message);setText(document.querySelector('#firebase-last-sync'),last);setText(document.querySelector('#firebase-pending'),state.pending);setText(document.querySelector('#firebase-errors'),state.errors);setText(document.querySelector('#firebase-orphans'),state.orphanOperations||0);setText(document.querySelector('#mobile-sync-pending'),state.pending);setText(document.querySelector('#mobile-sync-last'),last)}setHtml(document.querySelector('#firebase-details'),technicalDetails({...state.details,lastSyncAt:state.lastSync}));const modal=document.querySelector('#cloud-sync-panel');if(modal){setText(modal.querySelector('[data-cloud-status]'),state.message);setText(modal.querySelector('[data-cloud-last]'),last);setText(modal.querySelector('[data-cloud-pending]'),state.queueTotal);setText(modal.querySelector('[data-cloud-errors]'),state.errors);setText(modal.querySelector('[data-cloud-orphans]'),state.orphanOperations||0)}}

function openHeaderPanel(){const state=lastState;if(!state)return;document.querySelector('#modal').innerHTML=`<div class="modal-bg"><section class="modal-box cloud-panel" id="cloud-sync-panel"><header class="modal-head"><h3>Sincronização</h3><button class="icon-btn close" type="button"><i data-lucide="x"></i></button></header><div class="modal-body"><div class="cloud-panel-icon is-${escape(state.status)}"><i data-lucide="cloud"></i></div><h3 data-cloud-status>${escape(state.message)}</h3><div class="firebase-sync-grid"><span>Conexão</span><strong>${navigator.onLine?'Online':'Offline'}</strong><span>Última sincronização</span><strong data-cloud-last>${escape(formattedTime(state.lastSync))}</strong><span>Pendências</span><strong data-cloud-pending>${state.queueTotal}</strong><span>Erros</span><strong data-cloud-errors>${state.errors}</strong><span>Órfãs / somente locais</span><strong data-cloud-orphans>${state.orphanOperations||0}</strong></div></div><footer class="modal-foot"><button class="btn btn-light close" type="button">Fechar</button><button class="btn btn-light" id="cloud-panel-details" type="button">Ver detalhes</button><button class="btn btn-primary" id="cloud-panel-sync" type="button">Sincronizar agora</button></footer></section></div>`;document.querySelectorAll('#cloud-sync-panel .close').forEach(button=>button.onclick=()=>document.querySelector('#modal').innerHTML='');document.querySelector('#cloud-panel-details').onclick=openQueueDetails;document.querySelector('#cloud-panel-sync').onclick=manualSync;window.lucide?.createIcons()}

function bindHeader(){const badge=document.querySelector('.local-badge');if(!badge||badge.dataset.cloudPanelBound)return;badge.dataset.cloudPanelBound='true';badge.onclick=openHeaderPanel;badge.onkeydown=event=>{if(['Enter',' '].includes(event.key)){event.preventDefault();openHeaderPanel()}}}
function mount(){bindHeader();if(location.hash.includes('configuracoes'))queueMicrotask(()=>{settingsPanel();ensureDetailsButton();if(lastState)renderState(lastState)})}
addEventListener('resolve-sale-conflict',async event=>{const filter={customerId:String(event.detail?.customerId||''),saleId:String(event.detail?.saleId||''),fromCart:true};try{await window.SyncFirebase.compareDeviceWithCloud();const sale=(window.SyncFirebase.onlyLocalSaleReport?.()||[]).find(item=>item.saleId===filter.saleId)||(window.SyncFirebase.onlyLocalSaleReport?.()||[]).find(item=>item.customerId===filter.customerId&&!item.resolved);if(sale)openOnlyLocalSaleDetails(sale.saleId,filter);else openQueueDetails(filter)}catch(error){notify(error.message||'Não foi possível comparar com a nuvem. O carrinho foi preservado.',true);openQueueDetails(filter)}});
addEventListener('hashchange',mount);addEventListener('firebase-auth-ready',()=>{unsubscribe?.();unsubscribe=window.SyncFirebase.subscribe(renderState);mount()});new MutationObserver(mount).observe(document.querySelector('main')||document.body,{childList:true,subtree:true});mount();
