import { auth, db, BUSINESS_ID, PROJECT_ID } from './firebase-config.js';
import { collection, doc, getDoc, getDocs, increment, runTransaction, serverTimestamp, setDoc } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';
import { createFirestoreRepository } from './firestore-repository.js';
import { normalizeFirestoreData, sanitizeForFirestore } from './firestore-utils.js';

const QUEUE_KEY='adiFestaSyncQueue_v2',LEGACY_QUEUE_KEY='adiFestaFirestoreQueue_v1',AUTO_SYNC_MS=30000,MAX_WRITES=350;
const SOURCES={clients:{key:'clientes'},products:{key:'produtos'},sales:{key:'vendas'},payments:{key:'pagamentos'},balanceAdjustments:{key:'movimentacoes',filter:item=>item.tipo==='ajuste_saldo'},stockMovements:{key:'movimentacoesEstoque'},campaigns:{key:'campanhas'},campaignProgress:{key:'progressosCampanha'},rewards:{key:'recompensas'},charges:{key:'cobrancas'}};
const REALTIME_NAMES=new Set(['clients','products','settings','campaigns','campaignProgress','rewards']);
const CLOUD_NAMES=[...Object.keys(SOURCES),'settings'];
const repositories=Object.fromEntries(CLOUD_NAMES.map(name=>[name,createFirestoreRepository(name)]));
let currentUser=null,originalAlter=null,applyingCloud=false,processingPromise=null,autoTimer=null,quickTimer=null,unsubscribers=[],subscribers=new Set(),lastError='',lastErrorCode='',currentPath='';
const state={authReady:false,status:navigator.onLine?'idle':'offline',message:navigator.onLine?'Sincronização automática pronta':'Offline — salvo no aparelho',progress:0,testPassed:false,lastSync:localStorage.getItem('adiFestaLastSync')||'',cloudCounts:{},activeListeners:0,userProfile:null,businessDocument:false,businessOwnerId:'',ownerMatches:false,sent:0,received:0,comparison:null};

const now=()=>new Date().toISOString();
const activeBusinessId=()=>{const id=String(state.userProfile?.businessId||window.FirebaseSession?.profile?.businessId||'').trim();if(!id)throw Object.assign(new Error('O perfil não possui um negócio válido.'),{code:'failed-precondition'});return id};
const errorCode=error=>String(error?.code||'').replace('firestore/','');
const friendlyError=error=>({'permission-denied':'Seu usuário não possui permissão.','unavailable':'A nuvem está temporariamente indisponível.','unauthenticated':'Sua sessão expirou.','network-request-failed':'Sem conexão com a internet.','failed-precondition':'A sincronização ainda não está pronta neste aparelho.','invalid-argument':'Uma alteração contém dados inválidos.'}[errorCode(error)]||'Não foi possível sincronizar agora.');
const readQueue=()=>{try{const parsed=JSON.parse(localStorage.getItem(QUEUE_KEY));return Array.isArray(parsed)?parsed:[]}catch{return[]}};
const saveQueue=queue=>{localStorage.setItem(QUEUE_KEY,JSON.stringify(queue));updateQueueState()};
const queueCounts=()=>{const queue=readQueue();return{pending:queue.filter(item=>item.status!=='error').length,errors:queue.filter(item=>item.status==='error').length,total:queue.length}};
const retryDelay=attempts=>[5000,15000,30000,60000][Math.max(0,attempts-1)]??300000;
const canAttempt=(item,force=false)=>force||!item.lastAttemptAt||Date.now()-new Date(item.lastAttemptAt).getTime()>=retryDelay(item.attempts||0);
const normalizeText=value=>String(value||'').trim().toLocaleLowerCase('pt-BR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const sourceItems=(data,name)=>{const source=SOURCES[name],items=Array.isArray(data[source.key])?data[source.key]:[];return source.filter?items.filter(source.filter):items};
const localSummary=()=>{const data=DB.carregar();return{clientes:data.clientes.length,produtos:data.produtos.length,vendas:data.vendas.length,pagamentos:data.pagamentos.length,fiado:data.clientes.reduce((total,item)=>total+Math.abs(Math.min(0,Number(item.saldo||0))),0)}};
const diagnostic=()=>{const q=queueCounts(),local=localSummary(),profile=state.userProfile||{};return{projectId:PROJECT_ID,databaseId:'(default)',authReady:state.authReady,authenticated:Boolean(auth.currentUser),uid:auth.currentUser?.uid||'',email:auth.currentUser?.email||'',userDocumentExists:Boolean(profile.uid),userActive:profile.active===true,userRole:profile.role||'',userBusinessId:profile.businessId||'',businessDocumentExists:state.businessDocument,businessOwnerId:state.businessOwnerId,ownerMatches:state.ownerMatches,targetBusinessId:profile.businessId||'',connection:state.testPassed?'funcionando':'não comprovada',activeListeners:state.activeListeners,pendingOperations:q.total,pending:q.pending,syncErrors:q.errors,lastSyncAt:state.lastSync,lastSync:state.lastSync||'nunca',currentPath:currentPath||`businesses/${profile.businessId||'—'}`,lastErrorCode,lastErrorMessage:lastError,localClients:local.clientes,cloudClients:state.cloudCounts.clients??'—',localProducts:local.produtos,cloudProducts:state.cloudCounts.products??'—'}};
const emit=patch=>{Object.assign(state,patch);const counts=queueCounts(),snapshot={...state,pending:counts.pending,errors:counts.errors,queueTotal:counts.total,details:diagnostic()};subscribers.forEach(callback=>callback(snapshot));dispatchEvent(new CustomEvent('firebase-sync-status',{detail:snapshot}))};
function updateQueueState(){const q=queueCounts();if(!currentUser)return;if(!navigator.onLine)emit({status:'offline',message:q.total?`Offline — ${q.total} alteração(ões) pendente(s)`:'Offline — salvo no aparelho'});else if(q.total&&state.status!=='syncing')emit({status:q.errors?'error':'waiting',message:q.errors?`${q.errors} alteração(ões) precisam de nova tentativa`:`${q.total} alteração(ões) aguardando sincronização`})}
function reportError(error,context='Firebase',extra={}){lastError=friendlyError(error);lastErrorCode=errorCode(error)||'unknown';console.error(`[${context}]`,{...extra,code:error?.code,message:error?.message});emit({status:'error',message:lastError});return lastError}
function enrich(name,item){const clean=sanitizeForFirestore(item)||{};if(name==='clients')Object.assign(clean,{nomeNormalizado:normalizeText(clean.nome),telefoneNormalizado:String(clean.telefone||'').replace(/\D/g,'')});if(name==='products')Object.assign(clean,{nomeNormalizado:normalizeText(clean.nome),controlaEstoque:!clean.semControleEstoque});if(['sales','payments','balanceAdjustments','stockMovements','rewards'].includes(name))clean.operationId=clean.operationId||clean.id;return clean}
function cloudPayload(name,id,data,creating=false){const clean=enrich(name,data),businessId=activeBusinessId();delete clean.version;return{...clean,id:String(id),businessId,ownerId:currentUser.uid,schemaVersion:3,...(creating?{createdAt:clean.createdAt||clean.criadoEm||clean.data||serverTimestamp()}:{ }),updatedAt:serverTimestamp(),version:increment(1)}}
function migrateLegacyQueue(){if(localStorage.getItem(QUEUE_KEY))return;let legacy=[];try{legacy=JSON.parse(localStorage.getItem(LEGACY_QUEUE_KEY))||[]}catch{}if(!legacy.length)return;const groups=new Map();for(const item of legacy){const groupId=item.groupId||item.key||crypto.randomUUID();if(!groups.has(groupId))groups.set(groupId,[]);groups.get(groupId).push(item)}const migrated=[];for(const[groupId,items]of groups)for(let index=0;index<items.length;index+=MAX_WRITES){const part=items.slice(index,index+MAX_WRITES),operationId=items.length>MAX_WRITES?`${groupId}:${index/MAX_WRITES}`:groupId,writes=part.map(item=>({entityType:item.collection,entityId:String(item.id),operation:'update',before:null,data:item.data}));migrated.push({queueId:crypto.randomUUID(),operationId,entityType:writes.length===1?writes[0].entityType:'transaction',entityId:writes.length===1?writes[0].entityId:operationId,operation:writes.length===1?'update':'transaction',payload:{writes,eventKind:'legacy'},createdAtLocal:part[0]?.queuedAt||now(),attempts:0,status:'pending',lastAttemptAt:null,lastErrorCode:null,lastErrorMessage:null})}localStorage.setItem(QUEUE_KEY,JSON.stringify(migrated));localStorage.removeItem(LEGACY_QUEUE_KEY)}
function queueWrites(writes,operationId=crypto.randomUUID(),eventKind='simple'){
  if(!writes.length)return 0;const queue=readQueue();for(let index=0;index<writes.length;index+=MAX_WRITES){const part=writes.slice(index,index+MAX_WRITES),id=writes.length>MAX_WRITES?`${operationId}:${index/MAX_WRITES}`:operationId;queue.push({queueId:crypto.randomUUID(),operationId:id,entityType:part.length===1?part[0].entityType:'transaction',entityId:part.length===1?part[0].entityId:id,operation:part.length===1?part[0].operation:'transaction',payload:{writes:part,eventKind},createdAtLocal:now(),attempts:0,status:'pending',lastAttemptAt:null,lastErrorCode:null,lastErrorMessage:null})}saveQueue(queue);scheduleImmediate();return writes.length
}
function changedFields(previous,item){const patch={};for(const key of new Set([...Object.keys(previous||{}),...Object.keys(item||{})]))if(JSON.stringify(previous?.[key])!==JSON.stringify(item?.[key]))patch[key]=item?.[key];return patch}
function diffWrites(before,after){const writes=[];for(const name of Object.keys(SOURCES)){const previous=new Map(sourceItems(before,name).map(item=>[String(item.id),item])),next=new Map(sourceItems(after,name).map(item=>[String(item.id),item]));for(const[id,item]of next)if(JSON.stringify(item)!==JSON.stringify(previous.get(id))){const exists=previous.has(id);writes.push({entityType:name,entityId:id,operation:exists?'update':'create',before:previous.get(id)||null,data:exists?changedFields(previous.get(id),item):item})}for(const[id,item]of previous)if(!next.has(id))writes.push({entityType:name,entityId:id,operation:'update',before:item,data:{active:false,deletedAt:now()}})}if(JSON.stringify(before.config)!==JSON.stringify(after.config))writes.push({entityType:'settings',entityId:'default',operation:'update',before:before.config,data:changedFields(before.config,after.config)});return writes}
function captureChanges(before,after){if(applyingCloud)return 0;const writes=diffWrites(before,after),eventWrite=writes.find(write=>write.operation==='create'&&write.data?.operationId)||writes.find(write=>write.data?.operationId),stockEvent=writes.find(write=>write.entityType==='stockMovements'&&write.operation==='create'),operationId=eventWrite?.data?.operationId||crypto.randomUUID(),eventKind=writes.some(write=>write.entityType==='sales')?'sale':writes.some(write=>write.entityType==='payments')?'payment':writes.some(write=>write.entityType==='balanceAdjustments')?'balance_adjustment':stockEvent?.data?.tipo==='entrada'?'stock_entry':stockEvent?'stock_adjustment':'simple';return queueWrites(writes,operationId,eventKind)}
function installOfflineFirstStorage(){if(originalAlter)return;originalAlter=DB.alterar.bind(DB);DB.alterar=function(mutator){const before=structuredClone(DB.carregar()),result=originalAlter(mutator),after=structuredClone(result);captureChanges(before,after);return result};DB.__firebaseSyncWrapped=true}

async function validateUser(){if(PROJECT_ID!=='adi-festa-controle')throw Object.assign(new Error('Projeto Firebase incorreto.'),{code:'failed-precondition'});const user=auth.currentUser||currentUser;if(!user)throw Object.assign(new Error('Usuário não autenticado.'),{code:'unauthenticated'});const snapshot=await getDoc(doc(db,'users',user.uid));if(!snapshot.exists())throw Object.assign(new Error('Perfil não encontrado.'),{code:'permission-denied'});const profile=normalizeFirestoreData(snapshot.data());if(profile.uid!==user.uid||profile.active!==true||!profile.businessId)throw Object.assign(new Error('Perfil sem acesso válido.'),{code:'permission-denied'});currentUser=user;state.userProfile=profile;return{user,profile,businessId:profile.businessId}}
async function ensureBusinessDocument(){const{user,businessId}=await validateUser(),reference=doc(db,'businesses',businessId),snapshot=await getDoc(reference);if(!snapshot.exists()){if(businessId!==BUSINESS_ID)throw Object.assign(new Error('O negócio vinculado ao perfil não existe.'),{code:'permission-denied'});await setDoc(reference,{id:businessId,name:'Adi Festa',ownerId:user.uid,active:true,schemaVersion:3,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}const confirmed=await getDoc(reference),business=confirmed.data()||{},ownerMatches=business.ownerId===user.uid;emit({businessDocument:confirmed.exists(),businessOwnerId:business.ownerId||'',ownerMatches});if(!confirmed.exists()||business.active===false)throw Object.assign(new Error('Negócio indisponível.'),{code:'permission-denied'});return reference}
async function testFirestoreConnection(){emit({status:'testing',message:'Verificando a nuvem…'});try{const{user,businessId}=await validateUser();await ensureBusinessDocument();const reference=doc(db,'businesses',businessId,'syncMetadata','connection-test');currentPath=`businesses/${businessId}/syncMetadata/connection-test`;await setDoc(reference,{id:'connection-test',businessId,ownerId:user.uid,status:'ok',projectId:PROJECT_ID,testedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});const snapshot=await getDoc(reference);if(!snapshot.exists()||snapshot.data().status!=='ok')throw Error('A confirmação da gravação não foi recebida.');lastError='';lastErrorCode='';currentPath='';emit({testPassed:true,status:'success',message:'Nuvem verificada'});return true}catch(error){reportError(error,'Connection test',{path:currentPath});throw error}}
async function commitQueueItem(item){const businessId=activeBusinessId(),marker=doc(db,'businesses',businessId,'processedOperations',item.operationId),writes=item.payload.writes||[],transactional=['sale','payment','stock_entry'].includes(item.payload.eventKind);await runTransaction(db,async transaction=>{const processed=await transaction.get(marker);if(processed.exists())return;const snapshots=new Map();if(transactional)for(const write of writes)if(['clients','products'].includes(write.entityType)){const reference=doc(db,'businesses',businessId,write.entityType,String(write.entityId));snapshots.set(`${write.entityType}:${write.entityId}`,await transaction.get(reference))}for(const write of writes){const reference=doc(db,'businesses',businessId,write.entityType,String(write.entityId));let data=write.data;if(transactional&&write.before&&['clients','products'].includes(write.entityType)){const remote=snapshots.get(`${write.entityType}:${write.entityId}`),base=remote?.exists()?remote.data():{},merged={...data};const fields=write.entityType==='clients'?['saldo','totalComprado','quantidadeVendas']:['estoqueAtual','estoque'];for(const field of fields)if(Number.isFinite(Number(data[field]))&&Number.isFinite(Number(write.before[field])))merged[field]=Number(base[field]??write.before[field]??0)+(Number(data[field])-Number(write.before[field]));data=merged}transaction.set(reference,cloudPayload(write.entityType,write.entityId,data,write.operation==='create'),{merge:true})}transaction.set(marker,{id:item.operationId,businessId,ownerId:currentUser.uid,status:'processed',eventKind:item.payload.eventKind||'simple',processedAt:serverTimestamp(),createdAtLocal:item.createdAtLocal})});const confirmation=await getDoc(marker);if(!confirmation.exists())throw Error('A nuvem não confirmou a operação.')}
async function processSyncQueue(options={}){if(processingPromise)return processingPromise;const force=Boolean(options.force);processingPromise=(async()=>{if(!currentUser)return{sent:0,pending:readQueue().length,errors:0};if(!navigator.onLine){updateQueueState();return{sent:0,pending:readQueue().length,errors:queueCounts().errors}}await validateUser();let sent=0,index=0,queue=readQueue();for(const queued of [...queue]){if(!canAttempt(queued,force))continue;const live=readQueue(),position=live.findIndex(item=>item.queueId===queued.queueId);if(position<0)continue;live[position]={...live[position],status:'syncing',lastAttemptAt:now()};saveQueue(live);emit({status:'syncing',message:`Sincronizando ${index+1} de ${queue.length}…`,progress:Math.round(((index+1)/Math.max(1,queue.length))*100)});try{await commitQueueItem(live[position]);const after=readQueue().filter(item=>item.queueId!==queued.queueId);saveQueue(after);sent++}catch(error){const failed=readQueue(),failedIndex=failed.findIndex(item=>item.queueId===queued.queueId);if(failedIndex>=0){const attempts=Number(failed[failedIndex].attempts||0)+1;failed[failedIndex]={...failed[failedIndex],attempts,status:attempts>=3?'error':'pending',lastAttemptAt:now(),lastErrorCode:errorCode(error)||'unknown',lastErrorMessage:friendlyError(error)};saveQueue(failed)}reportError(error,'Queue operation',{queueId:queued.queueId,operationId:queued.operationId});if(['permission-denied','unauthenticated'].includes(errorCode(error)))break}index++}const counts=queueCounts();return{sent,pending:counts.total,errors:counts.errors}})();try{return await processingPromise}finally{processingPromise=null}}
function pendingIds(name){const ids=new Set();for(const item of readQueue())for(const write of item.payload?.writes||[])if(write.entityType===name)ids.add(String(write.entityId));return ids}
function cleanCloudItem(item){const clean=normalizeFirestoreData(item);clean.criadoEm??=clean.createdAt||clean.data;clean.atualizadoEm??=clean.updatedAt||clean.data;return clean}
function applyCloudCollection(name,documents){if(!originalAlter)return 0;const pending=pendingIds(name),source=SOURCES[name];let changed=0;applyingCloud=true;try{originalAlter(data=>{if(name==='settings'){const remote=documents.find(item=>item.id==='default'&&!item.deletedAt);if(!remote||pending.has('default'))return;const{id,businessId,ownerId,schemaVersion,createdAt,updatedAt,version,...config}=cleanCloudItem(remote);data.config={...data.config,...config};changed++;return}data[source.key]=Array.isArray(data[source.key])?data[source.key]:[];for(const raw of documents){const item=cleanCloudItem(raw),id=String(item.id);if(pending.has(id))continue;const current=data[source.key].findIndex(local=>String(local.id)===id);if(item.deletedAt){if(current>=0){data[source.key].splice(current,1);changed++}continue}if(current>=0){if(JSON.stringify(data[source.key][current])!==JSON.stringify({...data[source.key][current],...item})){data[source.key][current]={...data[source.key][current],...item};changed++}}else{data[source.key].push(item);changed++}}})}finally{applyingCloud=false}if(changed)dispatchEvent(new CustomEvent('cloud-data-updated',{detail:{collection:name,count:changed,source:'cloud'}}));return changed}
function startCloudSubscriptions(){stopCloudSubscriptions();if(!currentUser)return;for(const name of CLOUD_NAMES){const recent=!REALTIME_NAMES.has(name),subscribe=recent&&repositories[name].subscribeRecent?repositories[name].subscribeRecent:repositories[name].subscribe;const unsubscribe=subscribe.call(repositories[name],documents=>{state.cloudCounts[name]=documents.filter(item=>!item.deletedAt).length;const received=applyCloudCollection(name,documents);emit({cloudCounts:{...state.cloudCounts},received:state.received+received,activeListeners:unsubscribers.length})},error=>reportError(error,'Realtime listener',{collection:name}));unsubscribers.push(unsubscribe)}emit({activeListeners:unsubscribers.length})}
function stopCloudSubscriptions(){for(const unsubscribe of unsubscribers)try{unsubscribe()}catch{}unsubscribers=[];emit({activeListeners:0})}
async function pullCloudCollections(){await validateUser();let received=0;for(const name of CLOUD_NAMES){const documents=await(repositories[name].listRecent?repositories[name].listRecent():repositories[name].list());state.cloudCounts[name]=documents.length;received+=applyCloudCollection(name,documents)}emit({cloudCounts:{...state.cloudCounts},received});return received}
async function compareLocalAndCloud(){const local=localSummary(),remote={clients:state.cloudCounts.clients??0,products:state.cloudCounts.products??0,sales:state.cloudCounts.sales??0,payments:state.cloudCounts.payments??0};const comparison={local,remote,ok:queueCounts().total===0};emit({comparison});return comparison}
async function synchronizeNow(){if(!navigator.onLine){updateQueueState();return{offline:true,sent:0,received:0,pending:queueCounts().total,errors:queueCounts().errors}}await validateUser();if(!state.testPassed)await testFirestoreConnection();const push=await processSyncQueue({force:true}),received=await pullCloudCollections(),comparison=await compareLocalAndCloud(),time=now(),businessId=activeBusinessId();await setDoc(doc(db,'businesses',businessId,'syncMetadata','last-sync'),{id:'last-sync',businessId,ownerId:currentUser.uid,status:push.errors?'error':'ok',pendingOperations:push.pending,syncedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});localStorage.setItem('adiFestaLastSync',time);emit({status:push.errors?'error':'success',message:push.pending?`${push.pending} alteração(ões) ainda pendente(s)`:(push.sent||received?`Sincronizado às ${new Date(time).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})}`:'Tudo já está sincronizado.'),lastSync:time,progress:100,sent:push.sent,received});return{...push,received,comparison}}
async function automaticSync(){if(!currentUser||!navigator.onLine||processingPromise)return;try{if(!state.testPassed)await testFirestoreConnection();const push=await processSyncQueue(),received=document.visibilityState==='visible'?await pullCloudCollections():0;if(push.sent||received){const time=now();localStorage.setItem('adiFestaLastSync',time);emit({status:queueCounts().total?'waiting':'success',message:queueCounts().total?`${queueCounts().total} alteração(ões) aguardando nova tentativa`:'Dados sincronizados.',lastSync:time,sent:push.sent,received})}else updateQueueState()}catch(error){if(state.status!=='error')reportError(error,'Automatic sync')}}
function scheduleImmediate(){clearTimeout(quickTimer);if(!currentUser)return;quickTimer=setTimeout(automaticSync,500)}
function startAutoSync(){if(autoTimer)return;autoTimer=setInterval(automaticSync,AUTO_SYNC_MS);scheduleImmediate()}
function stopAutoSync(){clearInterval(autoTimer);clearTimeout(quickTimer);autoTimer=null;quickTimer=null}
async function runFirebaseDiagnostic(){await validateUser();await ensureBusinessDocument();await testFirestoreConnection();return diagnostic()}
function captureExternalChange(before,after){return captureChanges(structuredClone(before),structuredClone(after))}
function setUser(user,profile=null){currentUser=user||null;emit({authReady:true,userProfile:profile||null});if(!user){stopAutoSync();stopCloudSubscriptions();emit({testPassed:false,businessDocument:false,status:'idle',message:'Sessão encerrada'});return}migrateLegacyQueue();installOfflineFirstStorage();startCloudSubscriptions();startAutoSync();updateQueueState()}
addEventListener('online',()=>{emit({status:'waiting',message:'Conexão recuperada. Sincronizando…'});scheduleImmediate()});
addEventListener('offline',updateQueueState);
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')scheduleImmediate()});

window.FirestoreRepositories=repositories;
window.dataRepository=repositories;
window.getFirebaseDiagnostic=diagnostic;
window.SyncFirebase={setUser,setAuthReady:value=>emit({authReady:Boolean(value)}),stop:()=>setUser(null),subscribe:callback=>{subscribers.add(callback);callback({...state,...queueCounts(),queueTotal:queueCounts().total,details:diagnostic()});return()=>subscribers.delete(callback)},sanitizeForFirestore,ensureBusinessDocument,testFirestoreConnection,runFirebaseDiagnostic,getFirebaseDiagnostic:diagnostic,processSyncQueue,synchronizeNow,syncAll:synchronizeNow,pushPendingOperations:processSyncQueue,pullCloudCollections,compare:compareLocalAndCloud,startCloudSubscriptions,stopCloudSubscriptions,startAutoSync,stopAutoSync,schedule:scheduleImmediate,captureExternalChange,snapshot:localSummary,diagnostics:diagnostic,isReady:()=>Boolean(currentUser)};
