import { auth, db, BUSINESS_ID } from './firebase-config.js';
import { doc, getDoc, getDocs, setDoc, writeBatch, collection, serverTimestamp } from 'https://www.gstatic.com/firebasejs/10.13.2/firebase-firestore.js';

const PROJECT_ID='adi-festa-controle',BATCH_SIZE=300;
let currentUser=null,timer=null,lastError='',listeners=new Set(),currentCollection='',syncOperation=null;
const state={status:'idle',message:'Aguardando sincronização',progress:0,sent:{},failed:0,testPassed:sessionStorage.getItem('adiFirebaseConnectionOk')==='true'};
const emit=patch=>{Object.assign(state,patch);listeners.forEach(fn=>fn({...state,details:diagnostics()}));dispatchEvent(new CustomEvent('firebase-sync-status',{detail:{...state,details:diagnostics()}}))};
const friendlyError=error=>({'permission-denied':'Seu usuário não possui permissão para enviar dados.','unavailable':'O Firebase está temporariamente indisponível.','unauthenticated':'Sua sessão expirou. Entre novamente.','invalid-argument':'Um registro possui dados inválidos.'}[String(error?.code||'').replace('firestore/','')]||error?.message||'Não foi possível concluir a sincronização.');
const reportError=(error,context='Cloud migration')=>{lastError=friendlyError(error);console.error(`[${context}]`,{code:error?.code,message:error?.message,stack:error?.stack});emit({status:'error',message:lastError,failed:state.failed+1});return lastError};

function sanitizeForFirestore(value,seen=new WeakSet()){
  if(value===undefined||typeof value==='function'||typeof value==='symbol')return undefined;
  if(value===null||typeof value==='string'||typeof value==='boolean')return value;
  if(typeof value==='number')return Number.isFinite(value)?value:0;
  if(value instanceof Date)return value.toISOString();
  if(typeof Element!=='undefined'&&value instanceof Element)return undefined;
  if(Array.isArray(value))return value.map(v=>sanitizeForFirestore(v,seen)).filter(v=>v!==undefined);
  if(typeof value==='object'){
    if(seen.has(value))return undefined;seen.add(value);
    const out={};for(const [key,item] of Object.entries(value)){const clean=sanitizeForFirestore(item,seen);if(clean!==undefined)out[key]=clean}seen.delete(value);return out;
  }
  return undefined;
}
const localSources=()=>{const d=DB.carregar();return[
  ['clients',d.clientes||[],'clientes'],['products',d.produtos||[],'produtos'],['sales',d.vendas||[],'vendas'],['payments',d.pagamentos||[],'pagamentos'],
  ['balanceAdjustments',(d.movimentacoes||[]).filter(x=>x.tipo==='ajuste_saldo'),'ajustes'],['stockMovements',d.movimentacoesEstoque||[],'movimentações de estoque'],
  ['campaigns',d.campanhas||[],'campanhas'],['campaignProgress',d.campaignProgress||d.progressosCampanha||[],'progressos'],['rewards',d.recompensas||d.rewards||[],'recompensas'],['charges',d.cobrancas||[],'cobranças']
]};
const localSummary=()=>{const d=DB.carregar();return{clientes:(d.clientes||[]).length,produtos:(d.produtos||[]).length,vendas:(d.vendas||[]).length,pagamentos:(d.pagamentos||[]).length,fiado:(d.clientes||[]).reduce((s,c)=>s+Math.abs(Math.min(0,Number(c.saldo||0))),0),estoque:(d.produtos||[]).reduce((s,p)=>s+Number(p.estoqueAtual||0),0)}};
const diagnostics=()=>({authenticated:Boolean(auth.currentUser),email:auth.currentUser?.email||'',uid:auth.currentUser?.uid||'',businessId:BUSINESS_ID,projectId:PROJECT_ID,userDocument:Boolean(window.FirebaseSession?.profile),businessDocument:state.businessDocument||false,currentPath:currentCollection?`businesses/${BUSINESS_ID}/${currentCollection}`:`businesses/${BUSINESS_ID}`,lastError,pending:localSources().reduce((s,[,items])=>s+items.length,0)});

async function validateUser(){const user=auth.currentUser||currentUser;if(!user)throw Object.assign(Error('Sua sessão expirou.'),{code:'unauthenticated'});const snap=await getDoc(doc(db,'users',user.uid));if(!snap.exists())throw Object.assign(Error('Seu cadastro não foi encontrado.'),{code:'permission-denied'});const profile=snap.data();if(profile.active!==true||profile.role!=='admin'||profile.businessId!==BUSINESS_ID)throw Object.assign(Error('Seu usuário não está autorizado para este negócio.'),{code:'permission-denied'});currentUser=user;return{user,profile}}
async function ensureBusinessDocument(){const{user}=await validateUser(),ref=doc(db,'businesses',BUSINESS_ID),snap=await getDoc(ref);if(!snap.exists()){await setDoc(ref,{id:BUSINESS_ID,name:'Adi Festa',ownerId:user.uid,active:true,schemaVersion:2,createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}else{const business=snap.data();if(business.ownerId!==user.uid)throw Object.assign(Error('Este negócio pertence a outro usuário.'),{code:'permission-denied'});if(business.active===false)throw Object.assign(Error('Este negócio está inativo.'),{code:'permission-denied'});await setDoc(ref,{id:BUSINESS_ID,active:true,updatedAt:serverTimestamp()},{merge:true})}state.businessDocument=true;return ref}
const cloudDocument=(item,uid)=>{const clean=sanitizeForFirestore(item)||{};return{...clean,id:String(item.id),businessId:BUSINESS_ID,ownerId:uid,schemaVersion:2,createdAt:clean.criadoEm||clean.createdAt||clean.data||new Date().toISOString(),updatedAt:clean.atualizadoEm||clean.updatedAt||clean.data||new Date().toISOString(),deletedAt:clean.deletedAt||null}};
async function writeItems(name,items,label,totalOffset,totalItems){if(!items.length){state.sent[name]=0;emit({sent:{...state.sent}});return}const uid=currentUser.uid;for(let start=0;start<items.length;start+=BATCH_SIZE){const slice=items.slice(start,start+BATCH_SIZE),batch=writeBatch(db);currentCollection=name;for(const item of slice){if(!item?.id)throw Object.assign(Error(`Registro sem ID em ${name}.`),{code:'invalid-argument'});batch.set(doc(db,'businesses',BUSINESS_ID,name,String(item.id)),cloudDocument(item,uid),{merge:true})}await batch.commit();state.sent[name]=(state.sent[name]||0)+slice.length;emit({status:'syncing',message:`Enviando ${label} ${Math.min(start+slice.length,items.length)} de ${items.length}…`,progress:Math.round(((totalOffset+start+slice.length)/Math.max(1,totalItems))*100),sent:{...state.sent}})}}
async function writeSettings(){const config=sanitizeForFirestore(DB.carregar().config)||{};currentCollection='settings';await setDoc(doc(db,'businesses',BUSINESS_ID,'settings','default'),{...config,id:'default',businessId:BUSINESS_ID,ownerId:currentUser.uid,schemaVersion:2,updatedAt:serverTimestamp()},{merge:true});state.sent.settings=1;emit({sent:{...state.sent}})}
async function processSyncQueue(){if(syncOperation)return syncOperation;syncOperation=(async()=>{emit({status:'validating',message:'Validando usuário e negócio…',progress:0,sent:{},failed:0});try{await ensureBusinessDocument();const sources=localSources(),total=sources.reduce((s,[,items])=>s+items.length,0)+1;let offset=0;for(const [name,items,label] of sources){await writeItems(name,items,label,offset,total);offset+=items.length}await writeSettings();currentCollection='';emit({status:'success',message:'Sincronização concluída.',progress:100});return{...state.sent}}catch(error){reportError(error);throw error}})();try{return await syncOperation}finally{syncOperation=null}}
async function testConnection(){emit({status:'testing',message:'Testando conexão e permissões…'});try{await ensureBusinessDocument();const ref=doc(db,'businesses',BUSINESS_ID,'syncMetadata','connection-test');currentCollection='syncMetadata';await setDoc(ref,{id:'connection-test',businessId:BUSINESS_ID,ownerId:currentUser.uid,status:'ok',schemaVersion:2,testedAt:serverTimestamp()},{merge:true});const snap=await getDoc(ref);if(!snap.exists()||snap.data().status!=='ok')throw Error('O teste não pôde ser confirmado.');sessionStorage.setItem('adiFirebaseConnectionOk','true');currentCollection='';emit({status:'success',message:'Conexão e permissões funcionando.',testPassed:true});return true}catch(error){reportError(error,'Cloud connection test');throw error}}
async function compare(){await validateUser();const local=localSummary(),remote={};for(const [name] of localSources()){const snap=await getDocs(collection(db,'businesses',BUSINESS_ID,name));remote[name]=snap.size;if(name==='clients')remote.fiado=snap.docs.reduce((s,d)=>s+Math.abs(Math.min(0,Number(d.data().saldo||0))),0)}return{local,remote,ok:local.clientes===remote.clients&&local.produtos===remote.products&&local.vendas===remote.sales&&local.pagamentos===remote.payments&&Math.abs(local.fiado-(remote.fiado||0))<0.01}}
async function startCloudMigration(){if(!state.testPassed)throw Error('Teste a gravação na nuvem antes de iniciar a migração.');const ref=doc(db,'businesses',BUSINESS_ID,'syncMetadata','migration'),summary=localSummary();try{await ensureBusinessDocument();await setDoc(ref,{id:'migration',businessId:BUSINESS_ID,ownerId:currentUser.uid,source:'localStorage',status:'running',schemaVersion:2,counts:summary,startedAt:serverTimestamp()},{merge:true});const sent=await processSyncQueue(),check=await compare();emit({comparison:check,message:'Conferindo quantidades e saldo em aberto…'});await setDoc(ref,{status:check.ok?'completed':'divergent',sent,comparison:sanitizeForFirestore(check),completedAt:serverTimestamp()},{merge:true});if(!check.ok)throw Error('A conferência encontrou diferenças. Seus dados locais foram preservados.');emit({status:'success',message:'Migração concluída e conferida.',progress:100});return{sent,check}}catch(error){try{await setDoc(ref,{businessId:BUSINESS_ID,ownerId:currentUser?.uid||'',status:'error',error:friendlyError(error),updatedAt:serverTimestamp()},{merge:true})}catch{}reportError(error);throw error}}
function schedule(){clearTimeout(timer);timer=setTimeout(()=>processSyncQueue().catch(()=>{}),1500)}
addEventListener('online',schedule);
window.SyncFirebase={setUser:user=>{currentUser=user},subscribe:fn=>{listeners.add(fn);fn({...state,details:diagnostics()});return()=>listeners.delete(fn)},sanitizeForFirestore,ensureBusinessDocument,testConnection,startCloudMigration,processSyncQueue,syncAll:processSyncQueue,migrate:startCloudMigration,compare,schedule,snapshot:localSummary,diagnostics,isReady:()=>Boolean(currentUser)};
