const test = require("node:test");
const assert = require("node:assert/strict");
const fs = require("node:fs");
const { initializeTestEnvironment, assertSucceeds, assertFails } = require("@firebase/rules-unit-testing");
const {
  collection,
  doc,
  getDoc,
  getDocs,
  deleteDoc,
  limit,
  orderBy,
  query,
  runTransaction,
  setDoc,
  updateDoc,
  where,
  writeBatch,
} = require("firebase/firestore");

let env;
const projectId = "adi-festa-variations-test", businessA = "financial-a", businessB = "financial-b", businessC = "financial-owner-a-second";

test.before(async () => {
  env = await initializeTestEnvironment({ projectId, firestore: { rules: fs.readFileSync("firestore.rules", "utf8") } });
  await env.withSecurityRulesDisabled(async (context) => {
    const db = context.firestore();
    for (const [id, ownerId] of [[businessA, "owner-a"], [businessB, "owner-b"]])
      await setDoc(doc(db, "businesses", id), { id, ownerId, active: true, subscription: { planId: "internal", status: "active" } });
    await setDoc(doc(db, "businesses", businessC), { id: businessC, ownerId: "owner-a", active: true, subscription: { planId: "internal", status: "active" } });
    await setDoc(doc(db, "financialSpaces", "space-owner-a-second"), { id: "space-owner-a-second", name: "Segunda empresa", type: "business", linkedBusinessId: businessC, ownerUid: "owner-a", createdBy: "owner-a", active: true });
    for (const user of [
      { uid: "owner-a", businessId: businessA, role: "owner" },
      { uid: "manager-a", businessId: businessA, role: "manager" },
      { uid: "cashier-a", businessId: businessA, role: "cashier" },
      { uid: "owner-b", businessId: businessB, role: "owner" },
    ]) await setDoc(doc(db, "users", user.uid), { ...user, active: true });
  });
});
test.after(async () => env?.cleanup());

const businessSpace = { id: "space-a", name: "Empresa A", type: "business", linkedBusinessId: businessA, ownerUid: "owner-a", createdBy: "owner-a", active: true };
const entry = { id: "entry-a", financialSpaceId: "space-a", ownerUid: "owner-a", createdBy: "owner-a", operationId: "entry-a", amountCents: 1000, currency: "BRL", direction: "out", status: "pending", sourceType: "expense", sourceId: "entry-a" };

test("proprietário cria espaço empresarial e lançamento canônico", async () => {
  const db = env.authenticatedContext("owner-a").firestore();
  await assertSucceeds(setDoc(doc(db, "financialSpaces", "space-a"), businessSpace));
  await assertSucceeds(setDoc(doc(db, "financialSpaces", "space-a", "entries", "entry-a"), entry));
});

test("cliente não pode forjar lançamento marcado como automático", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), forged = {
    ...entry,
    id: "forged-auto",
    operationId: "forged-auto",
    sourceId: "payment-x",
    direction: "in",
    status: "paid",
    autoGenerated: true,
    generatedBy: "firebase_function",
  };
  await assertFails(setDoc(doc(db, "financialSpaces", "space-a", "entries", forged.id), forged));
});

test("gestor da mesma empresa lê e paga, caixa não altera", async () => {
  const manager = env.authenticatedContext("manager-a").firestore(), cashier = env.authenticatedContext("cashier-a").firestore();
  await assertSucceeds(getDoc(doc(manager, "financialSpaces", "space-a", "entries", "entry-a")));
  await assertSucceeds(updateDoc(doc(manager, "financialSpaces", "space-a", "entries", "entry-a"), { status: "paid" }));
  await assertFails(updateDoc(doc(cashier, "financialSpaces", "space-a", "entries", "entry-a"), { status: "cancelled" }));
});

test("empresa diferente não lê nem escreve", async () => {
  const other = env.authenticatedContext("owner-b").firestore();
  await assertFails(getDoc(doc(other, "financialSpaces", "space-a")));
  await assertFails(getDoc(doc(other, "financialSpaces", "space-a", "entries", "entry-a")));
});

test("visões financeiras salvas pertencem somente ao usuário", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), other = env.authenticatedContext("owner-b").firestore(), reference = doc(owner, "financialViewProfiles", "owner-a"), profile = {
    ownerUid: "owner-a",
    customViews: [{ id: "view_home_car", name: "Casa e Carro", financialSpaceIds: ["personal-a", "car-a"], mode: "custom" }],
    favoriteViewIds: ["view_home_car"],
    defaultViewId: "all_spaces",
    lastViewId: "view_home_car",
    schemaVersion: 1,
    updatedAt: "2026-09-11T12:00:00.000Z",
  };
  await assertSucceeds(setDoc(reference, profile));
  await assertSucceeds(getDoc(reference));
  await assertFails(getDoc(doc(other, "financialViewProfiles", "owner-a")));
  await assertFails(setDoc(doc(other, "financialViewProfiles", "owner-a"), { ...profile, ownerUid: "owner-b" }));
  await assertFails(setDoc(doc(owner, "financialViewProfiles", "owner-a-extra"), profile));
});

test("espaço pessoal é privado mesmo para colega da empresa", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), manager = env.authenticatedContext("manager-a").firestore();
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", "personal-a"), { id: "personal-a", name: "Pessoal", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true }));
  await assertFails(getDoc(doc(manager, "financialSpaces", "personal-a")));
});

test("proprietário acessa espaços das próprias empresas sem expor ao funcionário da empresa atual", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), manager = env.authenticatedContext("manager-a").firestore(), reference = doc(owner, "financialSpaces", "space-owner-a-second");
  await assertSucceeds(getDoc(reference));
  await assertFails(getDoc(doc(manager, "financialSpaces", "space-owner-a-second")));
});

test("conta V3 aceita tipo formal e saldo projetado sem expor o espaço pessoal", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), other = env.authenticatedContext("owner-b").firestore(), reference = doc(owner, "financialSpaces", "personal-a", "financialAccounts", "inter-v3"), account = {
    id: "inter-v3", operationId: "financial_account_inter-v3", financialSpaceId: "personal-a", ownerUid: "owner-a", createdBy: "owner-a",
    name: "Inter", type: "bank_account", institution: "Banco Inter", initialBalanceCents: 100000, currentBalanceCents: 100000,
    includeInAvailableBalance: true, balanceMode: "projected_from_opening_balance", active: true, schemaVersion: 3,
  };
  await assertSucceeds(setDoc(reference, account));
  await assertSucceeds(updateDoc(reference, { currentBalanceCents: 125000, balanceUpdatedAt: "2026-09-12T12:00:00.000Z" }));
  await assertSucceeds(updateDoc(reference, { active: false, archivedAt: "2026-09-12T13:00:00.000Z" }));
  await assertSucceeds(updateDoc(reference, { active: true }));
  await assertFails(updateDoc(reference, { active: "false" }));
  await assertSucceeds(getDoc(reference));
  await assertFails(getDoc(doc(other, "financialSpaces", "personal-a", "financialAccounts", "inter-v3")));
  await assertFails(updateDoc(doc(other, "financialSpaces", "personal-a", "financialAccounts", "inter-v3"), { currentBalanceCents: 999999 }));
});

test("cartões, faturas, contas e pagamentos respeitam o espaço pessoal", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), intruder = env.authenticatedContext("owner-b").firestore(), spaceId = "credit-personal";
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId), { id: spaceId, name: "Casa", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true }));
  const base = { financialSpaceId: spaceId, ownerUid: "owner-a", createdBy: "owner-a", schemaVersion: 3 },
    account = { ...base, id: "account-c6", operationId: "financial_account_account-c6", name: "C6 Bank", type: "checking", institution: "C6 Bank", initialBalanceCents: 0, active: true },
    card = { ...base, id: "card-c6", operationId: "credit_card_card-c6", cardHomeSpaceId: spaceId, name: "C6 Carbon", institution: "C6 Bank", last4: "2429", limitCents: 800000, committedCents: 0, closingDay: 12, dueDay: 20, paymentAccountId: "account-c6", accessMode: "single_space", allowedFinancialSpaceIds: [spaceId], defaultFinancialSpaceId: spaceId, active: true };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId, "financialAccounts", account.id), account));
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), card));
  await assertSucceeds(updateDoc(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), { active: false, archivedAt: "2026-09-12T13:00:00.000Z" }));
  await assertSucceeds(updateDoc(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), { active: true }));
  await assertFails(updateDoc(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), { active: "false" }));
  const invoice = { ...base, id: "card-c6_2026-09", operationId: "invoice_card-c6_2026-09", cardHomeSpaceId: spaceId, creditCardId: card.id, referenceKey: "2026-09", referenceYear: 2026, referenceMonth: 9, openingDate: "2026-08-13T15:00:00.000Z", closingDate: "2026-09-12T15:00:00.000Z", dueDate: "2026-09-20T15:00:00.000Z", purchasesTotalCents: 23800, adjustmentsTotalCents: 0, paidTotalCents: 0, remainingCents: 23800, spaceTotals: { [spaceId]: 23800 }, categoryTotals: { food: 23800 }, spacesUsedIds: [spaceId], status: "open" };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId, "creditCardInvoices", invoice.id), invoice));
  const purchase = { ...base, id: "purchase-1_01", operationId: "purchase-1:1", purchaseOperationId: "purchase-1", cardHomeSpaceId: spaceId, creditCardId: card.id, creditCardInvoiceId: invoice.id, installmentGroupId: "purchase-1", installmentNumber: 1, installmentCount: 1, amountCents: 23800, originalPurchaseAmountCents: 23800, description: "Mercado", purchaseDate: "2026-09-08T15:00:00.000Z", status: "posted" };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId, "creditCardPurchases", purchase.id), purchase));
  const adjustment = { ...base, id: "opening-balance-1", operationId: "opening-balance-1", cardHomeSpaceId: spaceId, creditCardInvoiceId: invoice.id, creditCardId: card.id, kind: "opening_balance", amountCents: 6200, effectCents: 6200, previousTotalCents: 23800, targetTotalCents: 30000, reason: "Conciliação", occurredAt: "2026-09-09T15:00:00.000Z", status: "confirmed" };
  const reconcile = writeBatch(owner);
  reconcile.set(doc(owner, "financialSpaces", spaceId, "creditCardAdjustments", adjustment.id), adjustment);
  reconcile.update(doc(owner, "financialSpaces", spaceId, "creditCardInvoices", invoice.id), { adjustmentsTotalCents: 6200, remainingCents: 30000 });
  reconcile.update(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), { committedCents: 30000 });
  await assertSucceeds(reconcile.commit());
  await assertFails(setDoc(doc(intruder, "financialSpaces", spaceId, "creditCardAdjustments", "forged-opening"), { ...adjustment, id: "forged-opening", operationId: "forged-opening", createdBy: "owner-b" }));
  const payment = { ...base, id: "invoice-pay-1", operationId: "invoice-pay-1", cardHomeSpaceId: spaceId, paymentFinancialSpaceId: spaceId, creditCardInvoiceId: invoice.id, creditCardId: card.id, financialAccountId: account.id, amountCents: 10000, paymentMethod: "pix", paidAt: "2026-09-20T15:00:00.000Z", status: "confirmed" };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", spaceId, "creditCardInvoicePayments", payment.id), payment));
  await assertSucceeds(updateDoc(doc(owner, "financialSpaces", spaceId, "creditCardInvoices", invoice.id), { paidTotalCents: 10000, remainingCents: 20000, status: "closed" }));
  await assertSucceeds(updateDoc(doc(owner, "financialSpaces", spaceId, "creditCards", card.id), { committedCents: 20000 }));
  await assertFails(getDoc(doc(intruder, "financialSpaces", spaceId, "creditCards", card.id)));
  await assertFails(setDoc(doc(intruder, "financialSpaces", spaceId, "creditCards", "forged"), { ...card, id: "forged", operationId: "forged", createdBy: "owner-b" }));
  await assertFails(deleteDoc(doc(owner, "financialSpaces", spaceId, "creditCardPurchases", purchase.id)));
  await assertFails(deleteDoc(doc(owner, "financialSpaces", spaceId, "creditCardInvoicePayments", payment.id)));
});

test("gestor financeiro do business acessa cartões sem transferir a propriedade", async () => {
  const manager = env.authenticatedContext("manager-a").firestore(), card = {
    id: "business-card", financialSpaceId: "space-a", ownerUid: "owner-a", createdBy: "manager-a",
    operationId: "credit_card_business-card", cardHomeSpaceId: "space-a", name: "Cartão empresa", institution: "Banco", last4: "9001",
    limitCents: 100000, committedCents: 0, closingDay: 10, dueDay: 18, paymentAccountId: null, active: true,
    accessMode: "single_space", allowedFinancialSpaceIds: ["space-a"], defaultFinancialSpaceId: "space-a",
  };
  await assertSucceeds(setDoc(doc(manager, "financialSpaces", "space-a", "creditCards", card.id), card));
  assert.equal((await getDoc(doc(manager, "financialSpaces", "space-a", "creditCards", card.id))).data().ownerUid, "owner-a");
});

test("conta pessoal compartilhada serve a dois espaços do owner sem vazar ao business", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), manager = env.authenticatedContext("manager-a").firestore(), other = env.authenticatedContext("owner-b").firestore(), homeId = "shared-account-home", carId = "shared-account-car";
  await env.withSecurityRulesDisabled(async (context) => {
    const admin = context.firestore();
    await setDoc(doc(admin, "financialSpaces", homeId), { id: homeId, name: "IPTV", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
    await setDoc(doc(admin, "financialSpaces", carId), { id: carId, name: "Carro", type: "other", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
  });
  const account = {
    id: "shared-inter", operationId: "financial_account_shared-inter", financialSpaceId: homeId, accountHomeSpaceId: homeId,
    ownerUid: "owner-a", createdBy: "owner-a", name: "Inter", institution: "Banco Inter", institutionKey: "banco_inter", type: "bank_account",
    initialBalanceCents: 0, currentBalanceCents: 0, includeInAvailableBalance: true, active: true, accessMode: "all_spaces",
    allowedFinancialSpaceIds: [], defaultFinancialSpaceId: homeId, schemaVersion: 4,
  };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", homeId, "financialAccounts", account.id), account));
  const carIncome = {
    id: "car-income-shared", financialSpaceId: carId, ownerUid: "owner-a", createdBy: "owner-a", operationId: "car-income-shared",
    amountCents: 7000, currency: "BRL", direction: "in", status: "paid", sourceType: "manual_income", sourceId: "car-income-shared",
    financialAccountId: account.id, financialAccountHomeSpaceId: homeId,
  };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", carId, "entries", carIncome.id), carIncome));
  await assertFails(getDoc(doc(other, "financialSpaces", homeId, "financialAccounts", account.id)));
  await assertFails(getDoc(doc(manager, "financialSpaces", homeId, "financialAccounts", account.id)));
  await assertFails(setDoc(doc(manager, "financialSpaces", "space-a", "entries", "business-using-personal-account"), {
    ...carIncome, id: "business-using-personal-account", operationId: "business-using-personal-account", sourceId: "business-using-personal-account", financialSpaceId: "space-a", createdBy: "manager-a",
  }));
});

test("cartão pessoal compartilhado mantém uma fatura e compras isoladas por espaço", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), manager = env.authenticatedContext("manager-a").firestore(), homeId = "shared-card-home", carId = "shared-card-car";
  await env.withSecurityRulesDisabled(async (context) => {
    const admin = context.firestore();
    await setDoc(doc(admin, "financialSpaces", homeId), { id: homeId, name: "Casa", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
    await setDoc(doc(admin, "financialSpaces", carId), { id: carId, name: "Carro", type: "other", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
  });
  const card = {
    id: "shared-c6", financialSpaceId: homeId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "credit_card_shared-c6", name: "C6 Carbon", institution: "C6", last4: "6357",
    limitCents: 1050000, committedCents: 0, closingDay: 7, dueDay: 13, paymentAccountId: null,
    accessMode: "all_spaces", allowedFinancialSpaceIds: [], defaultFinancialSpaceId: homeId, active: true, schemaVersion: 3,
  };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", homeId, "creditCards", card.id), card));
  const invoice = {
    id: "shared-c6_2026-10", financialSpaceId: homeId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "invoice_shared-c6_2026-10", creditCardId: card.id, referenceKey: "2026-10", referenceYear: 2026, referenceMonth: 10,
    openingDate: "2026-09-08T15:00:00.000Z", closingDate: "2026-10-07T15:00:00.000Z", dueDate: "2026-10-13T15:00:00.000Z",
    purchasesTotalCents: 25000, adjustmentsTotalCents: 0, paidTotalCents: 0, remainingCents: 25000,
    spaceTotals: { [carId]: 25000 }, categoryTotals: { transport: 25000 }, spacesUsedIds: [carId], status: "open", schemaVersion: 3,
  };
  const purchase = {
    id: "fuel_01", financialSpaceId: carId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "fuel:1", purchaseOperationId: "fuel", creditCardId: card.id, creditCardInvoiceId: invoice.id,
    installmentGroupId: "fuel", installmentNumber: 1, installmentCount: 1, amountCents: 25000,
    originalPurchaseAmountCents: 25000, description: "Combustível", purchaseDate: "2026-09-09T15:00:00.000Z", status: "posted", schemaVersion: 3,
  };
  const batch = writeBatch(owner);
  batch.set(doc(owner, "financialSpaces", homeId, "creditCardInvoices", invoice.id), invoice);
  batch.set(doc(owner, "financialSpaces", carId, "creditCardPurchases", purchase.id), purchase);
  batch.update(doc(owner, "financialSpaces", homeId, "creditCards", card.id), { committedCents: 25000 });
  await assertSucceeds(batch.commit());
  assert.equal((await getDoc(doc(owner, "financialSpaces", homeId, "creditCardInvoices", invoice.id))).data().spaceTotals[carId], 25000);
  assert.equal((await getDoc(doc(owner, "financialSpaces", carId, "creditCardPurchases", purchase.id))).data().financialSpaceId, carId);
  await assertFails(getDoc(doc(manager, "financialSpaces", homeId, "creditCards", card.id)));
  await assertFails(setDoc(doc(manager, "financialSpaces", "space-a", "creditCardPurchases", "forged-personal"), { ...purchase, id: "forged-personal", financialSpaceId: "space-a", operationId: "forged-personal", createdBy: "manager-a" }));
});

test("pagamento de conta no crédito exige cartão e fatura e pode ser desfeito sem criar entrada", async () => {
  const owner = env.authenticatedContext("owner-a").firestore(), intruder = env.authenticatedContext("owner-b").firestore();
  const homeId = "bill-card-home", targetId = "bill-card-target", cardId = "bill-card", invoiceId = "bill-card_2026-10", entryId = "condominium-september";
  await env.withSecurityRulesDisabled(async (context) => {
    const admin = context.firestore();
    await setDoc(doc(admin, "financialSpaces", homeId), { id: homeId, name: "Casa", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
    await setDoc(doc(admin, "financialSpaces", targetId), { id: targetId, name: "Apartamento", type: "other", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true });
  });
  const card = {
    id: cardId, financialSpaceId: homeId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    operationId: `credit_card_${cardId}`, name: "C6 Carbon", institution: "C6", last4: "6357",
    limitCents: 1050000, committedCents: 0, closingDay: 3, dueDay: 13, paymentAccountId: null,
    accessMode: "all_spaces", allowedFinancialSpaceIds: [], defaultFinancialSpaceId: homeId, active: true, schemaVersion: 4,
  };
  const bill = {
    id: entryId, financialSpaceId: targetId, ownerUid: "owner-a", createdBy: "owner-a", operationId: entryId,
    amountCents: 35000, currency: "BRL", direction: "out", status: "pending", sourceType: "expense", sourceId: entryId,
    description: "Condomínio", categoryId: "default_personal_home", categoryName: "Casa", dueAt: "2026-09-10T15:00:00.000Z",
  };
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", homeId, "creditCards", cardId), card));
  await assertSucceeds(setDoc(doc(owner, "financialSpaces", targetId, "entries", entryId), bill));
  await assertFails(updateDoc(doc(owner, "financialSpaces", targetId, "entries", entryId), { status: "paid", paymentMethod: "credit_card" }));

  const invoice = {
    id: invoiceId, financialSpaceId: homeId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    operationId: `invoice_${invoiceId}`, creditCardId: cardId, referenceKey: "2026-10", referenceYear: 2026, referenceMonth: 10,
    openingDate: "2026-09-04T15:00:00.000Z", closingDate: "2026-10-03T15:00:00.000Z", dueDate: "2026-10-13T15:00:00.000Z",
    purchasesTotalCents: 36800, adjustmentsTotalCents: 0, paidTotalCents: 0, remainingCents: 36800,
    spaceTotals: { [targetId]: 36800 }, categoryTotals: { default_personal_home: 35000, default_personal_finance: 1800 },
    spacesUsedIds: [targetId], status: "open", schemaVersion: 4,
  };
  const purchaseBase = {
    financialSpaceId: targetId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a", creditCardId: cardId,
    creditCardInvoiceId: invoiceId, installmentGroupId: "bill-pay", installmentNumber: 1, installmentCount: 1,
    purchaseDate: "2026-09-10T15:00:00.000Z", status: "posted", schemaVersion: 4,
  };
  const principalPurchase = { ...purchaseBase, id: "bill-pay_bill", operationId: "bill-pay_bill", purchaseOperationId: "bill-pay", amountCents: 35000, originalPurchaseAmountCents: 35000, description: "Condomínio" };
  const feePurchase = { ...purchaseBase, id: "bill-pay_fee", operationId: "bill-pay_fee", purchaseOperationId: "bill-pay", amountCents: 1800, originalPurchaseAmountCents: 1800, description: "Taxa do pagamento · Condomínio" };
  const feeEntry = {
    id: "bill-pay_fee_entry", financialSpaceId: targetId, ownerUid: "owner-a", createdBy: "owner-a", operationId: "bill-pay_fee_entry",
    amountCents: 1800, currency: "BRL", direction: "out", status: "paid", sourceType: "credit_card_bill_fee", sourceId: entryId,
    description: "Taxa do pagamento · Condomínio", paymentMethod: "credit_card", creditCardId: cardId, cardHomeSpaceId: homeId,
    creditCardInvoiceId: invoiceId, creditCardPurchaseId: feePurchase.id, cashFlowEffect: false, expenseRecognized: true,
  };
  const payBatch = writeBatch(owner);
  payBatch.set(doc(owner, "financialSpaces", homeId, "creditCardInvoices", invoiceId), invoice);
  payBatch.set(doc(owner, "financialSpaces", targetId, "creditCardPurchases", principalPurchase.id), principalPurchase);
  payBatch.set(doc(owner, "financialSpaces", targetId, "creditCardPurchases", feePurchase.id), feePurchase);
  payBatch.set(doc(owner, "financialSpaces", targetId, "entries", feeEntry.id), feeEntry);
  payBatch.update(doc(owner, "financialSpaces", targetId, "entries", entryId), {
    status: "paid", paidAt: "2026-09-10T15:00:00.000Z", paymentMethod: "credit_card", cashFlowEffect: false,
    creditCardId: cardId, cardHomeSpaceId: homeId, creditCardInvoiceId: invoiceId, creditCardPurchaseId: principalPurchase.id,
  });
  payBatch.update(doc(owner, "financialSpaces", homeId, "creditCards", cardId), { committedCents: 36800 });
  payBatch.set(doc(owner, "financialSpaces", targetId, "events", "bill-pay"), { id: "bill-pay", operationId: "bill-pay", financialSpaceId: targetId, ownerUid: "owner-a", createdBy: "owner-a", eventKind: "bill_paid_by_credit_card" });
  await assertSucceeds(payBatch.commit());
  await assertFails(updateDoc(doc(intruder, "financialSpaces", targetId, "entries", entryId), { status: "pending" }));

  const undoneAt = "2026-09-11T15:00:00.000Z", undoId = "undo_bill-pay", undoBatch = writeBatch(owner);
  undoBatch.update(doc(owner, "financialSpaces", homeId, "creditCardInvoices", invoiceId), { adjustmentsTotalCents: -36800, remainingCents: 0, spaceTotals: {}, categoryTotals: {}, status: "open" });
  undoBatch.update(doc(owner, "financialSpaces", homeId, "creditCards", cardId), { committedCents: 0 });
  undoBatch.update(doc(owner, "financialSpaces", targetId, "creditCardPurchases", principalPurchase.id), { status: "voided", voidedAt: undoneAt, voidedByOperationId: undoId, updatedAt: undoneAt });
  undoBatch.update(doc(owner, "financialSpaces", targetId, "creditCardPurchases", feePurchase.id), { status: "voided", voidedAt: undoneAt, voidedByOperationId: undoId, updatedAt: undoneAt });
  undoBatch.update(doc(owner, "financialSpaces", targetId, "entries", feeEntry.id), { status: "reversed", expenseRecognized: false });
  undoBatch.update(doc(owner, "financialSpaces", targetId, "entries", entryId), { status: "pending", paidAt: null, paymentMethod: null, creditCardId: null, cardHomeSpaceId: null, creditCardInvoiceId: null, creditCardPurchaseId: null });
  undoBatch.set(doc(owner, "financialSpaces", homeId, "creditCardAdjustments", undoId), {
    id: undoId, operationId: undoId, financialSpaceId: homeId, cardHomeSpaceId: homeId, ownerUid: "owner-a", createdBy: "owner-a",
    purchaseFinancialSpaceId: targetId, creditCardInvoiceId: invoiceId, creditCardId: cardId, creditCardPurchaseId: principalPurchase.id,
    kind: "bill_payment_void", amountCents: 36800, effectCents: -36800, status: "confirmed",
  });
  undoBatch.set(doc(owner, "financialSpaces", targetId, "events", undoId), { id: undoId, operationId: undoId, financialSpaceId: targetId, ownerUid: "owner-a", createdBy: "owner-a", eventKind: "credit_card_bill_payment_undone" });
  await assertSucceeds(undoBatch.commit());
  assert.equal((await getDoc(doc(owner, "financialSpaces", targetId, "entries", entryId))).data().status, "pending");
  assert.equal((await getDoc(doc(owner, "financialSpaces", homeId, "creditCardInvoices", invoiceId))).data().remainingCents, 0);
});

test("categoria e subcategoria customizadas ficam isoladas no espaço", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), other = env.authenticatedContext("owner-b").firestore();
  for (const id of ["category-space-a", "category-space-b"])
    await assertSucceeds(setDoc(doc(db, "financialSpaces", id), { id, name: id, type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true }));
  const macro = {
    id: "custom-printing", financialSpaceId: "category-space-a", ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "category:macro", name: "Impressão 3D", type: "category", parentCategoryId: null,
    isDefault: false, active: true,
  };
  const subcategory = {
    id: "custom-filament", financialSpaceId: "category-space-a", ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "category:sub", name: "Filamentos", type: "subcategory", parentCategoryId: "custom-printing",
    isDefault: false, active: true,
  };
  await assertSucceeds(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", macro.id), macro));
  await assertSucceeds(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", subcategory.id), subcategory));
  assert.equal((await getDocs(collection(db, "financialSpaces", "category-space-a", "categories"))).size, 2);
  assert.equal((await getDocs(collection(db, "financialSpaces", "category-space-b", "categories"))).size, 0);
  await assertFails(getDoc(doc(other, "financialSpaces", "category-space-a", "categories", macro.id)));
  await assertFails(setDoc(doc(other, "financialSpaces", "category-space-a", "categories", "intruder"), { ...macro, id: "intruder", createdBy: "owner-b" }));
});

test("Rules rejeitam hierarquia de categoria malformada", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), base = {
    financialSpaceId: "category-space-a", ownerUid: "owner-a", createdBy: "owner-a",
    operationId: "category:invalid", name: "Inválida", isDefault: false, active: true,
  };
  await assertFails(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", "invalid-type"), { ...base, id: "invalid-type", type: "expense", parentCategoryId: null }));
  await assertFails(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", "invalid-parent"), { ...base, id: "invalid-parent", type: "subcategory", parentCategoryId: null }));
  await assertFails(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", "missing-parent"), { ...base, id: "missing-parent", type: "subcategory", parentCategoryId: "custom-does-not-exist" }));
  await assertSucceeds(setDoc(doc(db, "financialSpaces", "category-space-a", "categories", "default-child"), { ...base, id: "default-child", type: "subcategory", parentCategoryId: "default_personal_home" }));
});

test("query real da tela lista espaços próprios", async () => {
  const db = env.authenticatedContext("owner-a").firestore();
  await assertSucceeds(getDocs(query(
    collection(db, "financialSpaces"),
    where("ownerUid", "==", "owner-a"),
    where("type", "==", "personal"),
    where("active", "==", true),
    limit(100),
  )));
  await assertSucceeds(getDocs(query(
    collection(db, "financialSpaces"),
    where("ownerUid", "==", "owner-a"),
    where("type", "==", "other"),
    where("active", "==", true),
    limit(100),
  )));
});

test("query real da tela lista espaços da empresa", async () => {
  const db = env.authenticatedContext("owner-a").firestore();
  await assertSucceeds(getDocs(query(
    collection(db, "financialSpaces"),
    where("linkedBusinessId", "==", businessA),
    where("type", "==", "business"),
    where("active", "==", true),
    limit(20),
  )));
});

test("consulta mensal de contas usa dueAt e não traz outubro em setembro", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), entries = collection(db, "financialSpaces", "space-a", "entries");
  await assertSucceeds(setDoc(doc(entries, "rent-september"), { ...entry, id: "rent-september", operationId: "rent-september", sourceId: "rent-september", dueAt: "2026-09-10T12:00:00.000Z", periodKey: "2026-09" }));
  await assertSucceeds(setDoc(doc(entries, "rent-october"), { ...entry, id: "rent-october", operationId: "rent-october", sourceId: "rent-october", dueAt: "2026-10-10T12:00:00.000Z", periodKey: "2026-10" }));
  const snapshot = await assertSucceeds(getDocs(query(
    entries,
    where("dueAt", ">=", "2026-09-01T03:00:00.000Z"),
    where("dueAt", "<", "2026-10-01T03:00:00.000Z"),
    orderBy("dueAt", "asc"),
    limit(500),
  )));
  assert.deepEqual(snapshot.docs.map((item) => item.id), ["rent-september"]);
});

test("ocorrência e série recorrente podem ser canceladas sem apagar histórico pago", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), recurrenceRef = doc(db, "financialSpaces", "space-a", "recurrences", "rent-series"),
    septemberRef = doc(db, "financialSpaces", "space-a", "entries", "series-september"), octoberRef = doc(db, "financialSpaces", "space-a", "entries", "series-october"),
    novemberRef = doc(db, "financialSpaces", "space-a", "entries", "series-november");
  await assertSucceeds(setDoc(recurrenceRef, { id: "rent-series", financialSpaceId: "space-a", ownerUid: "owner-a", createdBy: "owner-a", operationId: "rent-series", active: true, frequency: "monthly", seriesStartAt: "2026-09-10T12:00:00.000Z", seriesEndAt: null }));
  await assertSucceeds(setDoc(septemberRef, { ...entry, id: "series-september", operationId: "series-september", sourceId: "series-september", amountCents: 150000, status: "paid", dueAt: "2026-09-10T12:00:00.000Z", recurrenceId: "rent-series" }));
  await assertSucceeds(setDoc(octoberRef, { ...entry, id: "series-october", operationId: "series-october", sourceId: "series-october", amountCents: 150000, dueAt: "2026-10-10T12:00:00.000Z", recurrenceId: "rent-series" }));
  await assertSucceeds(setDoc(novemberRef, { ...entry, id: "series-november", operationId: "series-november", sourceId: "series-november", amountCents: 150000, dueAt: "2026-11-10T12:00:00.000Z", recurrenceId: "rent-series" }));
  await assertSucceeds(updateDoc(octoberRef, { amountCents: 165000 }));
  await assertSucceeds(updateDoc(recurrenceRef, { overrideOccurrenceKeys: ["2026-10-10"] }));
  assert.equal((await getDoc(septemberRef)).data().amountCents, 150000);
  assert.equal((await getDoc(octoberRef)).data().amountCents, 165000);
  assert.equal((await getDoc(novemberRef)).data().amountCents, 150000);
  const seriesEdit = writeBatch(db);
  seriesEdit.update(octoberRef, { amountCents: 170000 });
  seriesEdit.update(novemberRef, { amountCents: 170000 });
  seriesEdit.update(recurrenceRef, { amountCents: 170000, effectiveFrom: "2026-10-10T12:00:00.000Z" });
  await assertSucceeds(seriesEdit.commit());
  assert.equal((await getDoc(septemberRef)).data().amountCents, 150000);
  assert.equal((await getDoc(octoberRef)).data().amountCents, 170000);
  assert.equal((await getDoc(novemberRef)).data().amountCents, 170000);
  const batch = writeBatch(db);
  batch.update(octoberRef, { status: "cancelled", cancellationScope: "this_and_future" });
  batch.update(novemberRef, { status: "cancelled", cancellationScope: "this_and_future" });
  batch.update(recurrenceRef, { active: false, seriesEndAt: "2026-10-10T12:00:00.000Z" });
  await assertSucceeds(batch.commit());
  assert.equal((await getDoc(septemberRef)).data().status, "paid");
  assert.equal((await getDoc(octoberRef)).data().status, "cancelled");
  assert.equal((await getDoc(novemberRef)).data().status, "cancelled");
  await assertFails(deleteDoc(septemberRef));
});

test("lançamento pago não pode ser apagado nem ter valor reescrito", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), ref = doc(db, "financialSpaces", "space-a", "entries", "entry-a");
  await assertFails(deleteDoc(ref));
  await assertFails(updateDoc(ref, { amountCents: 1 }));
});

test("migração conservadora pode classificar sem alterar o valor financeiro", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), other = env.authenticatedContext("owner-b").firestore(), ref = doc(db, "financialSpaces", "space-a", "entries", "entry-a");
  await assertSucceeds(updateDoc(ref, {
    categoryId: "default_business_structure", categoryName: "Estrutura", categoryIcon: "store",
    subcategoryId: "default_business_structure_rent", subcategoryName: "Aluguel",
    categorySchemaVersion: 2, categoryMigrationStatus: "migrated",
  }));
  assert.equal((await getDoc(ref)).data().amountCents, 1000);
  await assertFails(updateDoc(doc(other, "financialSpaces", "space-a", "entries", "entry-a"), { categoryName: "Outro negócio" }));
});

test("pagamento transacional é idempotente e preserva um único evento", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), entryRef = doc(db, "financialSpaces", "space-a", "entries", "retry-account"),
    eventRef = doc(db, "financialSpaces", "space-a", "events", "payment_retry-account");
  await assertSucceeds(setDoc(entryRef, { ...entry, id: "retry-account", operationId: "retry-account", sourceId: "retry-account" }));
  const pay = () => runTransaction(db, async (transaction) => {
    const snapshot = await transaction.get(entryRef);
    if (snapshot.data().status === "paid") return;
    transaction.update(entryRef, { status: "paid", paidAt: "2026-09-04T12:00:00.000Z" });
    transaction.set(eventRef, { id: "payment_retry-account", operationId: "payment_retry-account", financialSpaceId: "space-a", ownerUid: "owner-a", createdBy: "owner-a", entryId: "retry-account", eventKind: "account_payment", transition: "paid", status: "applied", amountCents: 1000 });
  });
  await assertSucceeds(pay());
  await assertSucceeds(pay());
  assert.equal((await getDoc(entryRef)).data().status, "paid");
  assert.equal((await getDoc(eventRef)).data().eventKind, "account_payment");
});

test("transferência grava os dois lados atomicamente e não pode ser alterada", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), transferId = "transfer-a", personalId = "personal-transfer";
  await assertSucceeds(setDoc(doc(db, "financialSpaces", personalId), { id: personalId, name: "Pessoal", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true }));
  const batch = writeBatch(db), transferRef = doc(db, "financialTransfers", transferId);
  batch.set(transferRef, { id: transferId, operationId: transferId, fromSpaceId: personalId, toSpaceId: "space-a", amountCents: 50000, createdBy: "owner-a" });
  batch.set(doc(db, "financialSpaces", personalId, "entries", `${transferId}_out`), { id: `${transferId}_out`, financialSpaceId: personalId, ownerUid: "owner-a", createdBy: "owner-a", operationId: `${transferId}:out`, amountCents: 50000, currency: "BRL", direction: "out", status: "paid", sourceType: "transfer", sourceId: transferId });
  batch.set(doc(db, "financialSpaces", "space-a", "entries", `${transferId}_in`), { id: `${transferId}_in`, financialSpaceId: "space-a", ownerUid: "owner-a", createdBy: "owner-a", operationId: `${transferId}:in`, amountCents: 50000, currency: "BRL", direction: "in", status: "paid", sourceType: "transfer", sourceId: transferId });
  await assertSucceeds(batch.commit());
  await assertFails(updateDoc(transferRef, { amountCents: 1 }));
  await assertFails(getDoc(doc(env.authenticatedContext("owner-b").firestore(), "financialTransfers", transferId)));
});

test("transferência entre contas do mesmo espaço exige contas distintas e autorizadas", async () => {
  const db = env.authenticatedContext("owner-a").firestore(), spaceId = "internal-transfer", transferId = "transfer-internal";
  const space = { id: spaceId, name: "Caixa pessoal", type: "personal", linkedBusinessId: null, ownerUid: "owner-a", createdBy: "owner-a", active: true };
  await assertSucceeds(setDoc(doc(db, "financialSpaces", spaceId), space));

  const accountBase = { financialSpaceId: spaceId, ownerUid: "owner-a", createdBy: "owner-a", type: "checking", initialBalanceCents: 0, active: true };
  await assertSucceeds(setDoc(doc(db, "financialSpaces", spaceId, "financialAccounts", "checking-a"), { ...accountBase, id: "checking-a", operationId: "financial_account_checking-a", name: "Conta A" }));
  await assertSucceeds(setDoc(doc(db, "financialSpaces", spaceId, "financialAccounts", "checking-b"), { ...accountBase, id: "checking-b", operationId: "financial_account_checking-b", name: "Conta B" }));

  const transfer = {
    id: transferId,
    operationId: transferId,
    fromSpaceId: spaceId,
    toSpaceId: spaceId,
    fromFinancialAccountId: "checking-a",
    toFinancialAccountId: "checking-b",
    amountCents: 12500,
    createdBy: "owner-a",
  };
  await assertSucceeds(setDoc(doc(db, "financialTransfers", transferId), transfer));
  await assertFails(setDoc(doc(db, "financialTransfers", "transfer-same-account"), {
    ...transfer,
    id: "transfer-same-account",
    operationId: "transfer-same-account",
    fromFinancialAccountId: "checking-a",
    toFinancialAccountId: "checking-a",
  }));
  await assertFails(setDoc(doc(db, "financialTransfers", "transfer-missing-account"), {
    ...transfer,
    id: "transfer-missing-account",
    operationId: "transfer-missing-account",
    toFinancialAccountId: "missing",
  }));
});
